import Foundation

// MARK: - ChezActivityLog (Phase 85 PR 5c)
//
// Append-only log of Chez actions per household. Powers the
// Dashboard "This week with Chez" card + full activity history view.
//
// Rows are written by:
//   • handyman-provider ingestion post-visit
//   • chez-concierge case lifecycle handlers
//   • maintenance_tasks completion (when chez_owned)
//   • routine_visits state changes
//
// Schema lives in supabase/migrations/20261213_chez_activity_log.sql.

enum ChezActivityType: String, Codable {
    case taskCompleted = "task_completed"
    case visitScheduled = "visit_scheduled"
    case visitCompleted = "visit_completed"
    case assessmentCompleted = "assessment_completed"
    case caseOpened = "case_opened"
    case caseResolved = "case_resolved"
    case vendorContacted = "vendor_contacted"
    case quoteReceived = "quote_received"
    case systemAdded = "system_added"
    case recommendationLogged = "recommendation_logged"
    case reminderCompleted = "reminder_completed"
    case spend = "spend"
}

struct ChezActivityLogRow: Codable, Identifiable {
    let id: UUID
    let householdId: UUID
    let activityType: ChezActivityType
    let entityType: String?
    let entityId: UUID?
    let title: String
    let description: String?
    let costCents: Int64?
    let occurredAt: Date
    let surfaceOnDashboard: Bool
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case householdId = "household_id"
        case activityType = "activity_type"
        case entityType = "entity_type"
        case entityId = "entity_id"
        case title, description
        case costCents = "cost_cents"
        case occurredAt = "occurred_at"
        case surfaceOnDashboard = "surface_on_dashboard"
        case createdAt = "created_at"
    }

    /// Resilient decoder per CLAUDE.md rule for externally-fed Codable
    /// types. Unknown activity_type values fall back gracefully so a
    /// new server-side type doesn't crash older clients.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(UUID.self, forKey: .id)
        self.householdId = try c.decode(UUID.self, forKey: .householdId)

        let typeRaw = (try? c.decode(String.self, forKey: .activityType)) ?? "task_completed"
        self.activityType = ChezActivityType(rawValue: typeRaw) ?? .taskCompleted

        self.entityType = try? c.decodeIfPresent(String.self, forKey: .entityType)
        self.entityId = try? c.decodeIfPresent(UUID.self, forKey: .entityId)
        self.title = (try? c.decode(String.self, forKey: .title)) ?? ""
        self.description = try? c.decodeIfPresent(String.self, forKey: .description)
        self.costCents = try? c.decodeIfPresent(Int64.self, forKey: .costCents)
        self.occurredAt = (try? c.decode(Date.self, forKey: .occurredAt)) ?? Date()
        self.surfaceOnDashboard = (try? c.decode(Bool.self, forKey: .surfaceOnDashboard)) ?? true
        self.createdAt = (try? c.decode(Date.self, forKey: .createdAt)) ?? Date()
    }
}

// MARK: - Display helpers

extension ChezActivityType {
    /// SF Symbol for the icon column in the activity row.
    var icon: String {
        switch self {
        case .taskCompleted, .visitCompleted, .assessmentCompleted, .reminderCompleted:
            return "checkmark.circle.fill"
        case .visitScheduled:
            return "calendar.badge.plus"
        case .caseOpened, .caseResolved:
            return "bubble.left.and.bubble.right.fill"
        case .vendorContacted, .quoteReceived:
            return "phone.fill"
        case .systemAdded:
            return "house.fill"
        case .recommendationLogged:
            return "lightbulb.fill"
        case .spend:
            return "dollarsign.circle.fill"
        }
    }

    /// Short, glanceable label for tally rows.
    var bucketLabel: String {
        switch self {
        case .taskCompleted: return "Tasks completed"
        case .visitScheduled: return "Visits scheduled"
        case .visitCompleted: return "Visits completed"
        case .assessmentCompleted: return "Assessments"
        case .caseOpened: return "Cases opened"
        case .caseResolved: return "Cases resolved"
        case .vendorContacted: return "Vendors contacted"
        case .quoteReceived: return "Quotes received"
        case .systemAdded: return "Systems added"
        case .recommendationLogged: return "Recommendations"
        case .reminderCompleted: return "Reminders cleared"
        case .spend: return "Spent"
        }
    }
}

// MARK: - ChezMonthlySummaryRow

/// Phase 85 — Pre-aggregated monthly rollup, generated by the
/// chez-monthly-summary scheduled function on the 1st of each month.
/// Read by `MonthlySummaryCard` on the iOS dashboard.
struct ChezMonthlySummaryRow: Codable, Identifiable {
    let id: UUID
    let householdId: UUID
    let periodStart: Date
    let periodEnd: Date
    let tasksCompleted: Int
    let visitsCoordinated: Int
    let quotesReceived: Int
    let recommendationsLogged: Int
    let recommendationsApproved: Int
    let totalSpendCents: Int64
    let spendByCategory: [String: Int64]
    let headline: String?
    let viewedAt: Date?
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case householdId = "household_id"
        case periodStart = "period_start"
        case periodEnd = "period_end"
        case tasksCompleted = "tasks_completed"
        case visitsCoordinated = "visits_coordinated"
        case quotesReceived = "quotes_received"
        case recommendationsLogged = "recommendations_logged"
        case recommendationsApproved = "recommendations_approved"
        case totalSpendCents = "total_spend_cents"
        case spendByCategory = "spend_by_category"
        case headline
        case viewedAt = "viewed_at"
        case createdAt = "created_at"
    }

    /// Resilient decoder per CLAUDE.md.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(UUID.self, forKey: .id)
        self.householdId = try c.decode(UUID.self, forKey: .householdId)
        self.periodStart = (try? c.decode(Date.self, forKey: .periodStart)) ?? Date()
        self.periodEnd = (try? c.decode(Date.self, forKey: .periodEnd)) ?? Date()
        self.tasksCompleted = (try? c.decode(Int.self, forKey: .tasksCompleted)) ?? 0
        self.visitsCoordinated = (try? c.decode(Int.self, forKey: .visitsCoordinated)) ?? 0
        self.quotesReceived = (try? c.decode(Int.self, forKey: .quotesReceived)) ?? 0
        self.recommendationsLogged = (try? c.decode(Int.self, forKey: .recommendationsLogged)) ?? 0
        self.recommendationsApproved = (try? c.decode(Int.self, forKey: .recommendationsApproved)) ?? 0
        self.totalSpendCents = (try? c.decode(Int64.self, forKey: .totalSpendCents)) ?? 0
        self.spendByCategory = (try? c.decodeIfPresent([String: Int64].self, forKey: .spendByCategory)) ?? [:]
        self.headline = try? c.decodeIfPresent(String.self, forKey: .headline)
        self.viewedAt = try? c.decodeIfPresent(Date.self, forKey: .viewedAt)
        self.createdAt = (try? c.decode(Date.self, forKey: .createdAt)) ?? Date()
    }
}

// MARK: - This-week tally for the Dashboard card

/// Aggregated counts derived from a list of `ChezActivityLogRow` rows
/// over a window (default 7 days). Powers the Dashboard card's
/// glanceable rollup.
struct ChezActivityWeeklyTally {
    let tasksCompleted: Int
    let visitsScheduled: Int
    let visitsCompleted: Int
    let quotesReceived: Int
    let totalSpendCents: Int64
    let totalEvents: Int

    var hasAnything: Bool {
        totalEvents > 0 || totalSpendCents > 0
    }

    static let empty = ChezActivityWeeklyTally(
        tasksCompleted: 0,
        visitsScheduled: 0,
        visitsCompleted: 0,
        quotesReceived: 0,
        totalSpendCents: 0,
        totalEvents: 0
    )

    static func from(_ rows: [ChezActivityLogRow]) -> ChezActivityWeeklyTally {
        var tasksCompleted = 0
        var visitsScheduled = 0
        var visitsCompleted = 0
        var quotesReceived = 0
        var totalSpendCents: Int64 = 0
        for row in rows {
            switch row.activityType {
            case .taskCompleted: tasksCompleted += 1
            case .visitScheduled: visitsScheduled += 1
            case .visitCompleted: visitsCompleted += 1
            case .quoteReceived: quotesReceived += 1
            default: break
            }
            if let cost = row.costCents { totalSpendCents += cost }
        }
        return ChezActivityWeeklyTally(
            tasksCompleted: tasksCompleted,
            visitsScheduled: visitsScheduled,
            visitsCompleted: visitsCompleted,
            quotesReceived: quotesReceived,
            totalSpendCents: totalSpendCents,
            totalEvents: rows.count
        )
    }
}
