import SwiftUI

@MainActor
final class HouseQuizViewModel: ObservableObject {
    /// Phase 60.1: made `@Published` (was `let`) so edits from the new
    /// `PropertyRecapCard` on the first quiz screen write back through and
    /// every downstream reader (Q4 prefill, ATTOM-source caption, etc.)
    /// sees the corrected value immediately without a view rebuild.
    @Published var property: PropertyRow
    @Published private(set) var allQuestions: [HouseQuizQuestion]

    /// Phase 60.1: Home systems detected at property-creation time. Powers
    /// the "What we detected at your home" list inside the new
    /// `PropertyRecapCard`. Loaded once on init and refreshed if the view
    /// re-enters.
    @Published var detectedSystems: [HomeSystemRow] = []

    @Published var state: HouseQuizState
    @Published var currentIndex: Int = 0
    @Published var pendingFeedback: AnswerFeedback?
    @Published var showMilestoneCard: Bool = false
    @Published var showSkipForeverConfirm: Bool = false
    @Published var isSaving: Bool = false
    @Published var providerCaptureForAnswerId: String?
    @Published var providerCaptureText: String = ""

    /// Phase 19 — set to true after `saveAndExit()` successfully persists state
    /// to Supabase. The view's confirmation dialog watches this to decide
    /// whether to dismiss. Reset to false at the start of each save.
    @Published var savedAndReady: Bool = false
    /// Phase 19 — populated when `saveAndExit()` fails so the view can render
    /// an inline error banner with a Retry action. Cleared on retry success.
    @Published var saveErrorMessage: String?

    /// Phase 17b — running totals from `MaintenanceTaskReconciler`. Each
    /// answer that touches a system subtype merges its result into this; the
    /// final `runFinalReconciliation()` pass after the last question merges
    /// the orphan/whole-property cleanup. The completion view reads this to
    /// show "we added X, removed Y" with REAL numbers, never fakes them.
    @Published var reconciliationTotals: MaintenanceTaskReconciler.ReconciliationResult = .empty
    /// Set to `true` after `runFinalReconciliation()` finishes so the
    /// completion view can swap from a brief loading caption to the real
    /// summary. Defaults to `false` so an unfinished quiz never shows stale
    /// numbers.
    @Published var finalReconciliationDidRun: Bool = false

    /// Build 90 fix: handle to the detached completion-time reconciler so
    /// `loadFinaleTotals()` can await it. Without this the cinematic reveal
    /// renders before the reconciler writes home_systems / contractors /
    /// maintenance_tasks rows, and the user sees "$0 protection / 0 tasks
    /// scheduled / 2 vendors" instead of their actual numbers.
    private var finalReconcileTask: Task<Void, Never>?

    /// Chez v1: post-completion install-date sweep. When the
    /// reconciler + Day1Curator + ATTOM pre-fill have finished, the
    /// view model checks for unverified systems and flips
    /// `installDateSweepNeeded` true. The view routes to
    /// SystemCoverageFlow before rendering the cinematic reveal.
    /// `installDateSweepDone` flips when the user finishes the sweep
    /// (either by working through every card or by closing it via
    /// the toolbar Close button).
    @Published var installDateSweepNeeded: Bool = false
    @Published var installDateSweepDone: Bool = false
    /// Systems that need the user's confirmation. Includes both rows
    /// with no `install_date_source` AND ATTOM-pre-filled rows that
    /// haven't been confirmed yet. Filled in by `prepareInstallDateSweep`.
    @Published var unverifiedSystemsForSweep: [HomeSystemRow] = []
    /// Counter the cinematic reveal can read to add a "verified [N]
    /// install dates" line to the summary. Set in the sweep's
    /// onComplete closure.
    @Published var installDatesVerifiedInSweep: Int = 0

    /// Phase 16c — when the user picks an auto carrier that also offers home
    /// insurance (per `bundles_with_home`), we stash the row here so the q27
    /// render can show a "Looks like {name} also does home" suggestion card
    /// instead of forcing a duplicate search.
    @Published var bundledHomeSuggestion: UtilityProviderRow?
    /// Mirror flow for the reverse direction: if the user somehow answers q27
    /// before q26, the home carrier with `bundles_with_auto` becomes the
    /// suggestion shown above q26's auto picker.
    @Published var bundledAutoSuggestion: UtilityProviderRow?

    /// Build 84 — forwarding email address fetched once on view appear and
    /// surfaced inside the Q17 milestone card. Cached here so the view doesn't
    /// have to re-fetch or handle loading state at milestone time. The address
    /// is auto-generated by the `household_email_addresses` DB trigger when
    /// the household is created, so it always exists by the time the user
    /// reaches the quiz.
    @Published var cachedHouseholdEmail: String?

    /// Build 85 — true when the user is viewing the saved-for-later review
    /// list instead of a question screen. Toggled by the trailing toolbar
    /// pill and auto-set when the user reaches the end of fresh questions
    /// with saved items still pending. Cleared when the user taps a saved
    /// question to jump into it or taps "Keep going forward instead" to
    /// resume the normal flow.
    @Published var showSavedReviewScreen: Bool = false

    /// Build 86 — Q28 dedup. Cached snapshot of `family_members` for the
    /// household, loaded once on init via the background refresh path so
    /// `caretakersBody` can check whether a spouse / partner / child was
    /// already added (e.g. via the dashboard household strip "+" button or
    /// the AccountCreationStep spouse invite flow) BEFORE re-showing the
    /// Q28 sub-steps that would create a duplicate. Empty until the fetch
    /// resolves; views should fail open and render the spouse / kids form
    /// when the cache hasn't loaded yet.
    @Published var existingFamilyMembers: [FamilyMemberRow] = []

    // MARK: - Phase 60.3: protection meter + chapter state

    /// Phase 60.3: Running total of 10-year protection value the user has
    /// locked in so far. Accretes per answer according to the delta table
    /// in `HouseQuizValueMeter`. Starts at $0 on Q1; lands near
    /// `OnboardingScheduleGenerator.computeValueProtection(from:)` at
    /// the last question.
    @Published private(set) var protectedValue: Double = 0

    /// Phase 60.3: Set of chapters the user has already seen the intro
    /// card for in the current session. Prevents the card from re-firing
    /// between every question within the same chapter.
    @Published var shownChapterIntros: Set<HouseQuizChapter> = []

    /// Phase 60.3: Accumulating payload describing questions that were
    /// auto-skipped since the last user-visible question render. The
    /// view reads this to show a small toast so the jump never feels
    /// silent, then clears it on dismiss.
    @Published var pendingSkipToast: SkipToastPayload?

    /// Phase 60.3: Reasons the quiz can skip a question — drives the
    /// toast message so the user gets a plain-English explanation.
    enum SkipReason: Equatable {
        case attomKnowsIt
        case previousAnswerMakesItIrrelevant
        case chipNotApplicable
    }

    struct SkipToastPayload: Equatable {
        var skippedCount: Int
        var reason: SkipReason
        var message: String {
            let n = skippedCount
            let questions = n == 1 ? "question" : "questions"
            switch reason {
            case .attomKnowsIt:
                return "Skipped \(n) \(questions). Your property records already cover this."
            case .previousAnswerMakesItIrrelevant:
                return "Skipped \(n) \(questions) based on your earlier answers."
            case .chipNotApplicable:
                return "Skipped \(n) \(questions) that didn't apply to your home."
            }
        }
    }

    /// Phase 60.3: The chapter containing the current question. Defaults
    /// to `.yourHome` when `currentQuestion` is nil (end of quiz / between
    /// screens).
    var currentChapter: HouseQuizChapter {
        currentQuestion?.chapter ?? .yourHome
    }

    /// Phase 60.3: Count of questions in the given chapter across the
    /// entire library (including any dynamically-skippable ones — the
    /// chapter progress pill shows worst-case count so the N/M ratio
    /// doesn't rearrange mid-chapter).
    func questionsInChapter(_ chapter: HouseQuizChapter) -> Int {
        allQuestions.filter { $0.chapter == chapter }.count
    }

    /// Phase 60.3: 1-indexed position of the current question within its
    /// chapter. Returns 0 when `currentQuestion` is nil.
    func positionInCurrentChapter() -> Int {
        guard let current = currentQuestion else { return 0 }
        let qs = allQuestions.filter { $0.chapter == current.chapter }
        return (qs.firstIndex(where: { $0.id == current.id }) ?? 0) + 1
    }

    /// Phase 60.3: Approximate protection value the user is about to
    /// unlock in the upcoming chapter. Shown in the chapter intro card so
    /// users see the reward before they commit to the work.
    func expectedValueForChapter(_ chapter: HouseQuizChapter) -> Double {
        HouseQuizValueMeter.expectedValueForChapter(chapter, property: property)
    }

    // MARK: - Phase 60.4: personalization tokens

    /// Phase 60.4: Token bundle for personalized question titles. Built
    /// from the `PropertyRow` (ATTOM-enriched) + the captured roof
    /// answer. Passed into `HouseQuizQuestion.personalizedTitle(using:)`
    /// at render time so titles read as "Your 1987 Putnam Park roof —
    /// what's on top?" instead of "What's your roof made of?" whenever
    /// ATTOM has the data to ground the question.
    var propertyFactBundle: PropertyFactBundle {
        let roofAnswer = state.answers["q1_roof_material"]?.answerId
        return PropertyFactBundle(property: property, roofAnswerId: roofAnswer)
    }

    // MARK: - Phase 60.5: end-of-quiz finale totals

    /// Phase 60.5: Counts + examples for the cinematic reveal + summary.
    /// Populated asynchronously by `loadFinaleTotals()` the moment the
    /// completion view renders. `hasLoaded` gates the summary's render
    /// so the user doesn't flash "0 vendors on file" for the half-
    /// second it takes the contractors fetch to resolve.
    @Published private(set) var finaleTotals: QuizFinaleTotals = .empty

    /// Phase 60.5: Fetch fresh counts of contractors + home systems,
    /// merge with `reconciliationTotals.added` (tasks added this quiz
    /// session), compute the projected protection value, and publish
    /// the result to `finaleTotals`. Idempotent — the completion view
    /// calls this in `.task` and we guard against re-firing via
    /// `finaleTotals.hasLoaded`.
    func loadFinaleTotals() async {
        guard !finaleTotals.hasLoaded else { return }

        // Build 90 fix: wait for the detached completion reconciler before
        // reading any counts. Without this we render "$0 / 0 tasks /
        // 2 vendors" because the reconciler's writes haven't landed yet.
        // `finalReconcileTask` is non-nil whenever `state.completedAt`
        // flipped during this session.
        await finalReconcileTask?.value

        var totals = QuizFinaleTotals()
        totals.hasLoaded = true

        // Build 90 fix: refresh the property from DB so any AVM that
        // ATTOM populated AFTER quiz init lands in `currentEstimatedValue`
        // for the projection below. The in-memory `property` is the
        // snapshot that was passed in at quiz start; address-hook
        // enrichment may have written newer values since.
        if let fresh = try? await db.fetchProperty(id: property.id) {
            self.property = fresh
        }

        // Build 90 fix: count `maintenance_tasks` from the DB rather than
        // the reconciler's in-session running total. The running total
        // misses tasks created inline (vehicle maintenance, hardscape, the
        // Phase 54A auto-created systems) and is empty when the user
        // resumes a quiz that crossed completion in a prior session.
        if let tasks = try? await db.fetchMaintenanceTasks(propertyId: property.id) {
            // `fetchMaintenanceTasks` already filters out archived rows
            // by default. The remaining set is what the user has on
            // their schedule going forward.
            totals.tasksScheduled = tasks.count
            totals.taskExamples = tasks
                .sorted { ($0.createdAt ?? .distantPast) > ($1.createdAt ?? .distantPast) }
                .prefix(3)
                .map(\.title)
        }

        // Gaps closed — we reuse the reconciler's "preserved" bucket
        // as a proxy for items the user explicitly confirmed the quiz
        // accounted for. Not perfect, but the count is a real number
        // pulled from real data rather than a fabrication.
        let preservedTitles = reconciliationTotals.preserved
        totals.gapsClosed = preservedTitles.count
        totals.gapExamples = Array(preservedTitles.suffix(3).reversed())

        // Vendors on file — fresh snapshot of the household's
        // contractors table. Captures everything the quiz captured
        // PLUS anything added before or alongside (e.g. vendor
        // mirrors from utility captures).
        if let contractors = try? await db.fetchContractors() {
            totals.vendorsOnFile = contractors.count
            totals.vendorExamples = contractors
                .sorted { ($0.createdAt ?? .distantPast) > ($1.createdAt ?? .distantPast) }
                .prefix(3)
                .map(\.companyName)
        }

        // Systems confirmed — same treatment for home_systems. The
        // reconciler + ensureAutoCreatedSystems collectively populate
        // this table during the quiz.
        if let systems = try? await db.fetchHomeSystems(propertyId: property.id) {
            let topLevel = systems.filter { $0.parentSystemId == nil }
            totals.systemsConfirmed = topLevel.count
            totals.systemExamples = topLevel
                .prefix(3)
                .map { "\($0.name) · \($0.category)" }
        }

        // Projected protection value — `estimatedValue × 0.12` per the
        // Remodeling Magazine + NAR maintenance-vs-neglect study (same
        // 12% figure codified in
        // `OnboardingScheduleGenerator.computeValueProtection`). Inlined
        // here rather than synthesizing a `PropertyLookupResult` since
        // the struct now has a custom `init(from:)` that suppresses the
        // memberwise initializer.
        //
        // Phase 95.1 fix: re-fetch the property here because
        // `currentEstimatedValue` is written by the property-lookup edge
        // function asynchronously after the onboarding initial property
        // insert. The `property` snapshot held by the view model is taken
        // at quiz-init time and may pre-date the ATTOM write — leaving
        // currentEstimatedValue nil and the cinematic reveal showing $0
        // for the entire HNW audience the reveal exists to delight.
        // Caught by overnight E2E test (Tests/e2e UI Wave 1 Subagent 5).
        let freshProperty = (try? await db.fetchProperty(id: property.id)) ?? property
        if let value = freshProperty.currentEstimatedValue, value > 0 {
            totals.projectedValueProtected = value * 0.12
        } else if let salePrice = freshProperty.purchasePrice, salePrice > 0 {
            // Fallback: project the last sale price forward at ~5%
            // appreciation/year when the canonical AVM is missing.
            // Matches the ladder in `computeValueProtection(from:)`.
            let yearsHeld = Self.yearsSince(freshProperty.purchaseDate) ?? 0
            let projected = salePrice * pow(1.05, Double(yearsHeld))
            totals.projectedValueProtected = projected * 0.12
        }

        finaleTotals = totals
    }

    /// Phase 60.5: Parse a "yyyy-MM-dd" / "MM/dd/yyyy" / "yyyy" date
    /// string into a full-year delta from today. Mirrors the helper
    /// on `OnboardingScheduleGenerator`. Used for the value-projection
    /// fallback when only a last-sale signal is available.
    private static func yearsSince(_ dateString: String?) -> Int? {
        guard let dateString else { return nil }
        let formatter = DateFormatter()
        for format in ["yyyy-MM-dd", "MM/dd/yyyy", "yyyy"] {
            formatter.dateFormat = format
            if let date = formatter.date(from: dateString) {
                let years = Calendar.current.dateComponents([.year], from: date, to: Date()).year ?? 0
                return max(0, years)
            }
        }
        return nil
    }

    /// Phase 60.3: Internal helper called from `persist(...)` right
    /// after the answer lands in state. Bumps `protectedValue` by the
    /// per-question delta and fires a soft haptic. SwiftUI animates the
    /// numeric transition via `.contentTransition(.numericText(...))` in
    /// the view.
    fileprivate func accreteValueMeter(for questionId: String, answer: HouseQuizAnswer) {
        let delta = HouseQuizValueMeter.delta(
            forQuestion: questionId,
            answer: answer,
            property: property,
            detectedSystems: detectedSystems
        )
        // Monotonic increase — never decrement the meter on answer edit.
        // If a user edits an earlier answer with a smaller delta, the
        // meter reflects the MAX earned across all answers rather than
        // the sum of current answers.
        protectedValue += delta
        Haptics.light()
    }

    /// Phase 67D (B1): bump the meter when the user confirms the ATTOM
    /// recap card. The "we already know your home" trust moment earns
    /// 5% of the home's estimated value as "Property baseline confirmed."
    /// Fires once per recap confirm; subsequent confirms (e.g. when a
    /// user back-navigates to the recap and re-confirms) are idempotent
    /// via `recapConfirmedDidAccrete` — we never double-count.
    func accreteAttomConfirmation() {
        guard !recapConfirmedDidAccrete else { return }
        recapConfirmedDidAccrete = true
        let baseline = (property.currentEstimatedValue ?? 500_000) * 0.05
        protectedValue += baseline
        Haptics.light()
    }

    /// Phase 67D (B1): one-shot guard so `accreteAttomConfirmation()`
    /// can't double-count if the user re-enters the recap surface.
    @Published private(set) var recapConfirmedDidAccrete: Bool = false

    private let mapper: HouseQuizAnswerMapper
    private let db = DatabaseService.shared

    init(property: PropertyRow) {
        self.property = property
        self.allQuestions = HouseQuizQuestionLibrary.allQuestions
        self.state = property.houseQuizState ?? HouseQuizState(startedAt: Date())
        self.mapper = HouseQuizAnswerMapper(householdId: property.householdId, propertyId: property.id)

        // Resume at the first unanswered+unsaved+unskipped question.
        self.currentIndex = firstUnresolvedIndex()
        // Phase 18b: A resumed quiz might land on a question whose dynamic
        // provider types resolve to empty (e.g. Q19 when Q3 was electric).
        // Mark it skipped and advance immediately so the user never sees a
        // dead picker.
        skipDynamicallyUnreachableQuestion()
        // Phase 19j: Same idea for dynamicSkip — if the resume cursor lands
        // on Q11b/Q14 but the user already answered Q11 with no_lawn, skip
        // those questions on resume too.
        skipDynamicallyHiddenQuestion()

        // Phase 19 — defensive background refresh: the dashboard's cached
        // PropertyRow may be stale (e.g. multi-device, fast resume). Adopt
        // any canonical DB state change, even when the answer count is the
        // same, so same-question edits do not keep showing stale local data.
        Task { @MainActor [weak self] in
            await self?.refreshAdminCatalog()
        }

        Task { @MainActor [weak self] in
            await self?.refreshPropertyStateFromDB()
        }

        // Build 86 — load the household's existing family members so the
        // Q28 caretakers flow can skip the spouse sub-step (and pre-populate
        // kids) when the user already added them via the dashboard "+"
        // button or the spouse invite flow on AccountCreationStep. Failures
        // leave the cache empty, which fails open: the view falls back to
        // showing the full Q28 flow as if no one was on file.
        Task { @MainActor [weak self] in
            await self?.refreshExistingFamilyMembers()
        }

        // Phase 60.1 — load the detected home systems so the new recap
        // card's "What we detected at your home" list renders without a
        // second network round trip from the view.
        Task { @MainActor [weak self] in
            await self?.loadDetectedSystemsIfNeeded()
        }

        // Phase 60.3 — restore the protection meter from persisted answers
        // so save-for-later resume lands the user back at the same value
        // they saw when they left. Silent (no haptic / animation) since
        // this is state hydration, not a user action.
        self.protectedValue = Self.restoreProtectedValue(
            from: state,
            property: property
        )
    }

    private func refreshAdminCatalog() async {
        let items = await AdminCatalogService.shared.refreshPublishedCatalog()
        let nextQuestions = AdminCatalogService.shared.quizQuestions(
            applying: items,
            to: HouseQuizQuestionLibrary.allQuestions
        )
        guard quizFingerprint(nextQuestions) != quizFingerprint(allQuestions) else { return }

        let currentQuestionId = currentQuestion?.id
        allQuestions = nextQuestions

        if let currentQuestionId,
           let retainedIndex = allQuestions.firstIndex(where: { $0.id == currentQuestionId }) {
            currentIndex = retainedIndex
        } else {
            currentIndex = firstUnresolvedIndex()
        }

        skipDynamicallyUnreachableQuestion()
        skipDynamicallyHiddenQuestion()
    }

    private func quizFingerprint(_ questions: [HouseQuizQuestion]) -> String {
        questions.map { question in
            [
                question.id,
                question.title,
                question.subtitle ?? "",
                question.kind.rawValue,
                question.chapter.rawValue,
                question.section.rawValue,
                question.answerOptions.map { "\($0.id):\($0.label)" }.joined(separator: "|"),
            ].joined(separator: "§")
        }.joined(separator: "¶")
    }

    /// Phase 60.3: Sum the `HouseQuizValueMeter.delta` for every answer in
    /// the persisted state so the running total rehydrates on view
    /// model init. Called from the designated initializer only — user-
    /// driven accretion happens via `accreteValueMeter(...)`.
    private static func restoreProtectedValue(
        from state: HouseQuizState,
        property: PropertyRow
    ) -> Double {
        guard !state.answers.isEmpty else { return 0 }
        return state.answers.reduce(0.0) { total, entry in
            total + HouseQuizValueMeter.delta(
                forQuestion: entry.key,
                answer: entry.value,
                property: property,
                detectedSystems: []
            )
        }
    }

    /// Phase 60.1: Load (or re-load) the detected home systems for this
    /// property. Silent failure leaves the array empty, which simply
    /// suppresses the detected-systems block on the recap card instead
    /// of blocking the quiz.
    func loadDetectedSystemsIfNeeded() async {
        do {
            detectedSystems = try await db.fetchHomeSystems(propertyId: property.id)
        } catch {
            print("[HouseQuiz] Failed to load detected systems: \(error)")
        }
    }

    /// Phase 60.1: Re-fetch the `PropertyRow` from the DB. Called by the
    /// `PropertyRecapEditSheet` after a save so every downstream reader
    /// (Q4 prefill, source caption, etc.) picks up the corrected value.
    /// Silent failure leaves the in-memory row untouched — the sheet has
    /// already surfaced the error if the update itself failed.
    func reloadProperty() async {
        do {
            property = try await db.fetchProperty(id: property.id)
        } catch {
            print("[HouseQuiz] Failed to reload property after edit: \(error)")
        }
    }

    /// Phase 60.1: Apply a fresh `PropertyRow` that the edit sheet already
    /// fetched from the DB. Use this when the updater returned the row —
    /// avoids a second fetch for the same data.
    func applyUpdatedProperty(_ fresh: PropertyRow) {
        property = fresh
    }

    private func refreshPropertyStateFromDB() async {
        do {
            let fresh = try await db.fetchProperty(id: property.id)
            guard let freshState = fresh.houseQuizState else { return }
            guard freshState != state else { return }

            property = fresh
            state = freshState
            currentIndex = firstUnresolvedIndex()
            skipDynamicallyUnreachableQuestion()
            // Phase 19j — same protection on the background refresh path.
            skipDynamicallyHiddenQuestion()
            print("[HouseQuiz] Refreshed state from DB: \(freshState.answers.count) answers, resume index \(currentIndex)")
        } catch {
            print("[HouseQuiz] Background state refresh failed: \(error)")
        }
    }

    /// Build 86 — refreshes the cached snapshot of `family_members` for the
    /// household. Called once on init so `caretakersBody` (Q28) can detect a
    /// pre-existing spouse / partner / child added via the dashboard "+"
    /// button or the AccountCreationStep invite flow and skip the
    /// duplicate-creating sub-steps. Silent failure leaves the cache empty,
    /// which fails open to showing the full Q28 form.
    func refreshExistingFamilyMembers() async {
        do {
            existingFamilyMembers = try await db.fetchFamilyMembers(householdId: property.householdId)
        } catch {
            print("[HouseQuiz] Failed to fetch existing family members: \(error)")
        }
    }

    /// Build 86 — true when the household already has at least one
    /// spouse-shaped relationship on file. Drives Q28's decision to skip the
    /// `QuizSpouseInviteInlineForm` sub-step entirely so re-running Q28
    /// doesn't create a second "Tom Burke" alongside an existing "Tom".
    var existingSpouseCount: Int {
        existingFamilyMembers.filter { member in
            let r = member.relationship.lowercased()
            return r == "spouse"
                || r == "partner"
                || r == "spouse/partner"
                || r == "husband"
                || r == "wife"
        }.count
    }

    /// Build 86 — pre-existing children on the household, sorted oldest
    /// first via the existing `sortedByAge` extension. Q28's kids sub-step
    /// uses this to seed `householdPendingKids` so the user sees their
    /// existing children as editable rows instead of being asked to add
    /// them all over again.
    var existingChildren: [FamilyMemberRow] {
        existingFamilyMembers.filter { member in
            let r = member.relationship.lowercased()
            return r == "child" || r == "son" || r == "daughter"
        }.sortedByAge()
    }

    // MARK: - Derived

    var currentQuestion: HouseQuizQuestion? {
        guard currentIndex >= 0, currentIndex < allQuestions.count else { return nil }
        return allQuestions[currentIndex]
    }

    var progress: Double {
        let total = allQuestions.count - state.skipped.count
        guard total > 0 else { return 1 }
        let answered = state.answers.count
        return min(1.0, Double(answered) / Double(total))
    }

    var progressLabel: String {
        // Apr 7, 2026 (build 82): switched from "X of Y done" to
        // "Question N of Y" so the user sees their CURRENT POSITION in
        // the quiz (1-indexed), not just a count of completed answers.
        // The previous label was easy to misread because the answer
        // count and the current position diverged once the user went
        // back to edit a previous question.
        //
        // Build 85: clamp position to total. When the quiz completes or the
        // user is in saved-review mode, currentIndex can reach or exceed
        // allQuestions.count (34), which made the label read "Question 35
        // of 34". Clamping keeps the math sane in every state. The view
        // also hides the toolbar progress bar entirely on completion and
        // saved-review screens, so this clamp is the belt to the toolbar
        // visibility's suspenders.
        let total = allQuestions.count
        let position = min(max(1, currentIndex + 1), total)
        let saved = state.savedForLater.count
        if saved > 0 {
            return "Question \(position) of \(total) · \(saved) saved"
        }
        return "Question \(position) of \(total)"
    }

    var isAtMilestone: Bool {
        HouseQuizQuestionLibrary.milestoneIndices.contains(currentIndex - 1)
    }

    /// Phase 85 (back-compat): "isComplete" historically meant "the quiz is
    /// fully done" and gated the cinematic reveal. With the intake/walk-
    /// through split, the cinematic only fires when the WALK-THROUGH
    /// completes — not at intake. So `isComplete` now reflects that
    /// stricter milestone. Surfaces that want the older "all questions
    /// answered" semantic should read `state.isIntakeComplete` instead.
    var isComplete: Bool {
        state.isWalkthroughComplete
    }

    /// Phase 85: every intake question answered (or skipped). Kept
    /// separately from `isComplete` so the path-decision screen can
    /// render after intake without triggering the cinematic.
    var isIntakeComplete: Bool {
        state.isIntakeComplete
    }

    /// Phase 85: should the path-decision screen render right now?
    var shouldShowPathDecision: Bool {
        state.shouldShowPathDecision
    }

    // MARK: - Actions

    /// Persist a single-choice or yes/no answer and advance.
    ///
    /// Apr 7, 2026 (build 82): added a brief 0.35-second pause AFTER
    /// persisting the answer but BEFORE advancing or showing the insight
    /// overlay. This gives the user a moment to register the visual
    /// selection feedback (the chip turning navy + checkmark) so they
    /// don't feel like the screen jumped past their tap. Without this
    /// the chip selection animation runs while the next state is already
    /// rendering, which is jarring.
    func recordAnswer(
        _ answerId: String,
        customText: String? = nil,
        selectedProviderId: UUID? = nil,
        selectedIds: [String]? = nil,
        customEntries: [String]? = nil,
        payload: [String: String]? = nil
    ) async {
        // Phase 67D: `selectedIds` / `customEntries` / `payload` added so
        // progressive-disclosure kinds (trashWithDays day chips,
        // dualInsurance customEntries fallback, the lawn/pool/garage
        // payload-extended captures) can commit a single rich answer
        // without each kind needing its own dedicated record* method.
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: answerId,
            customText: customText,
            selectedIds: selectedIds,
            customEntries: customEntries,
            selectedProviderId: selectedProviderId,
            payload: payload,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)

        // Brief pause so the user sees the chip selection state.
        try? await Task.sleep(nanoseconds: 350_000_000)

        // Show feedback if available; otherwise advance.
        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: answerId) {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": answerId,
            ])
        } else {
            advance()
        }
    }

    /// Phase 16c — variant that captures the full provider row alongside the
    /// answer. Lets us inspect bundle flags for auto/home insurance questions
    /// so q27 (home) can pre-fill from a q26 (auto) selection and vice versa.
    ///
    /// Phase 18e — also persists the catalog `provider.id` on the answer so
    /// the answer mapper can re-fetch the full record (logo, brand color,
    /// website, phone) at apply time and snapshot it onto the resulting
    /// utility_account row.
    func recordProviderAnswer(provider: UtilityProviderRow) async {
        guard let q = currentQuestion else { return }
        // Insurance bundle hint plumbing happens BEFORE persist so the q27
        // render after persist's advance() can read the flag immediately.
        switch q.id {
        case "q26_auto_insurance":
            if provider.bundlesWithHome == true {
                bundledHomeSuggestion = provider
            } else {
                bundledHomeSuggestion = nil
            }
        case "q27_homeowners_insurance":
            if provider.bundlesWithAuto == true {
                bundledAutoSuggestion = provider
            } else {
                bundledAutoSuggestion = nil
            }
        default:
            break
        }
        let answer = HouseQuizAnswer(
            answerId: "selected",
            customText: provider.name,
            selectedProviderId: provider.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)

        // Build 86: brief pause so the user sees the picker row's navy
        // tint + checkmark feedback before the quiz transitions away.
        // Mirrors the pause `recordAnswer` already has — Tom's wife
        // reported tapping a provider produced no visual change because
        // the picker tore down before the row's selected state had time
        // to render. The visual update happens in
        // `UtilityProviderSearchPicker.providerRow` via `tappedProviderId`.
        try? await Task.sleep(nanoseconds: 350_000_000)

        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: "selected") {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": "selected",
            ])
        } else {
            advance()
        }
    }

    /// Phase 16c — user accepts the bundled suggestion at q27 (or q26 in the
    /// reverse case). Records the answer with the suggested provider's name
    /// and clears the suggestion so it doesn't bleed into a future quiz pass.
    func acceptBundledSuggestion() async {
        guard let q = currentQuestion else { return }
        let suggestion: UtilityProviderRow?
        switch q.id {
        case "q27_homeowners_insurance":
            suggestion = bundledHomeSuggestion
        case "q26_auto_insurance":
            suggestion = bundledAutoSuggestion
        default:
            suggestion = nil
        }
        guard let provider = suggestion else { return }
        bundledHomeSuggestion = nil
        bundledAutoSuggestion = nil
        await recordAnswer("selected", customText: provider.name)
    }

    /// Phase 16c — user rejected the bundled suggestion. Clear it so the
    /// regular search picker takes over without re-rendering the card.
    func dismissBundledSuggestion() {
        bundledHomeSuggestion = nil
        bundledAutoSuggestion = nil
    }

    /// Persist a multi-select answer and advance. `customEntries` carries any
    /// free-form values typed into an "Other"-style option (e.g. q10 appliances
    /// where users can add Sauna, Pellet stove, etc).
    ///
    /// Phase 18c: `secondaryFuelProvider` carries the propane supplier picked
    /// inline on Q20 when the user selected any propane option AND their
    /// primary heating fuel from Q3 isn't already propane. The mapper reads
    /// this at apply time to create a fresh propane utility_account row.
    func recordMultiSelect(
        _ ids: [String],
        customEntries: [String]? = nil,
        secondaryFuelProvider: UtilityProviderRow? = nil
    ) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: nil,
            customText: secondaryFuelProvider?.name,
            selectedIds: ids,
            customEntries: customEntries,
            secondaryFuelProviderId: secondaryFuelProvider?.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Phase 19i — Q22 generator inline form. Persists the generator type
    /// (whole_home / portable / none), the fuel (natural_gas / propane /
    /// diesel), and an optional explicit provider. The mapper reads all three
    /// to create the right system + fuel attribute + utility_account.
    func recordGeneratorAnswer(
        type: String,
        fuelType: String?,
        provider: UtilityProviderRow?
    ) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: type,
            customText: provider?.name,
            generatorFuelType: fuelType,
            generatorProviderId: provider?.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: type) {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": type,
            ])
        } else {
            advance()
        }
    }

    /// Phase 16d — Q28 specific: persist the household answer along with the
    /// kids and expecting entries captured by QuizKidsInlineForm. Caretakers
    /// already flow through `recordMultiSelect` after the inline form
    /// completes — this method only captures the residents type plus the
    /// kid/expecting payload, since those create real family_member rows.
    ///
    /// Build 87 (Home Manager expansion): now also accepts an optional
    /// `homeManagerEntry` captured by `QuizHomeManagerInviteInlineForm`.
    /// The entry is purely a hydration breadcrumb — the actual
    /// `family_members` row + invite is created at form submit time
    /// directly via `HouseholdInviteCoordinator`, so this method only
    /// stashes it on the answer for resume / back-nav.
    func recordHouseholdAnswer(
        residentsId: String,
        kids: [QuizKidEntry],
        expecting: [QuizExpectingEntry],
        homeManagerEntry: HomeManagerEntry? = nil,
        petsAnswerId: String? = nil
    ) async {
        // Phase 67D (A10): `petsAnswerId` is the pets sub-step folded
        // into the Q28 caretakers chain. The mapper reads
        // `payload["petsAnswerId"]` to stamp `pets` + `has_pets`
        // attributes and re-reconcile synthetic-turf.
        guard let q = currentQuestion else { return }
        var payload: [String: String]? = nil
        if let petsAnswerId {
            payload = ["petsAnswerId": petsAnswerId]
        }
        let answer = HouseQuizAnswer(
            answerId: residentsId,
            customText: nil,
            selectedIds: nil,
            customEntries: nil,
            kids: kids.isEmpty ? nil : kids,
            expectingEntries: expecting.isEmpty ? nil : expecting,
            homeManagerEntry: homeManagerEntry,
            payload: payload,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Persist a currency-style answer (purchase price) and advance.
    func recordCurrencyAnswer(answerId: String, amount: Double) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: answerId,
            customText: String(Int(amount)),
            selectedIds: nil,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Save the current question for later - appears in the dashboard
    /// "X saved questions" hint and resurfaces next launch.
    func saveForLater() {
        guard let q = currentQuestion else { return }
        if !state.savedForLater.contains(q.id) {
            state.savedForLater.append(q.id)
        }
        Analytics.track(.quizSavedForLater, ["question_id": q.id])
        Task { await persistState() }
        advance()
    }

    /// Exit path for the visible "Save for later" action.
    func saveCurrentQuestionForLaterAndExit() async {
        guard let q = currentQuestion else { return }
        isSaving = true
        savedAndReady = false
        saveErrorMessage = nil
        defer { isSaving = false }

        if !state.savedForLater.contains(q.id) {
            state.savedForLater.append(q.id)
        }
        state.skipped.removeAll { $0 == q.id }

        do {
            try await persistStateThrowing()
            savedAndReady = true
            Analytics.track(.quizSavedForLater, ["question_id": q.id])
            Analytics.track(.quizSavedAndExited, [
                "answered": state.answers.count,
                "saved_for_later": state.savedForLater.count,
            ])
        } catch {
            saveErrorMessage = "Couldn't save your progress. Check your connection and try again."
            Analytics.track(.quizSaveAndExitFailed, ["error": "\(error)"])
        }
    }

    /// Skip forever - never resurface, user will add the data manually.
    func skipForever() {
        guard let q = currentQuestion else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        // Remove from savedForLater if present.
        state.savedForLater.removeAll { $0 == q.id }
        Analytics.track(.quizSkippedForever, ["question_id": q.id])
        Task { await persistState() }
        advance()
    }

    /// Dismiss the inline feedback card and advance to the next question.
    func dismissFeedback() {
        pendingFeedback = nil
        advance()
    }

    /// Phase 60.4 (F8): Dismiss a per-chip inline feedback pill WITHOUT
    /// advancing the quiz. Chip toggling on multi-select questions like
    /// Q15b doesn't advance on its own — the user keeps selecting — so
    /// the dismiss path must clear the pill and stop there.
    func dismissChipFeedback() {
        pendingFeedback = nil
    }

    /// Phase 60.4 (F8): Surface a per-chip feedback pill from a
    /// multi-select question. Tracks which chip's feedback is currently
    /// showing so the view doesn't stack pills when the user fires
    /// several selections in a row — a new chip selection replaces the
    /// previous pill instead of queuing.
    func presentInlineChipFeedback(_ feedback: AnswerFeedback, chipId: String) {
        pendingFeedback = feedback
        lastChipFeedbackId = chipId
        Analytics.track(.quizChipFeedbackShown, [
            "question_id": currentQuestion?.id ?? "",
            "chip_id": chipId,
        ])
    }

    /// Phase 60.4 (F8): Chip id whose feedback is currently pinned in
    /// `pendingFeedback`. The view uses this in combination with the
    /// "current question is a chip question" check to route through
    /// `dismissChipFeedback` (no advance) instead of `dismissFeedback`
    /// (advance).
    @Published var lastChipFeedbackId: String? = nil

    func goBack() {
        guard currentIndex > 0 else { return }
        currentIndex -= 1
        pendingFeedback = nil
    }

    func skipQuestionsAfterZeroVehicles() {
        // If user picked "0 cars" on Q23, skip Q24 (vehicle add) automatically.
        guard let q = currentQuestion, q.id == "q24_vehicle_add" else { return }
        if let prior = state.answers["q23_vehicle_count"], prior.answerId == "0" {
            state.skipped.append("q24_vehicle_add")
            advance()
        }
    }

    /// Phase 18b: Auto-skip provider-search questions whose
    /// `dynamicProviderTypes` resolves to an empty array. Used by Q19 (heating
    /// fuel provider) when the user answered Q3 with electric / geothermal /
    /// not_sure — there's no fuel delivery contract to capture, so the
    /// question silently disappears from the flow. Marks the question as
    /// skipped (not saved-for-later) so the progress label still totals
    /// correctly and `firstUnresolvedIndex()` doesn't try to resume here.
    ///
    /// Phase 60.3: also accumulates a `pendingSkipToast` so the next
    /// rendered question acknowledges the auto-skip rather than feeling
    /// like the quiz jumped.
    func skipDynamicallyUnreachableQuestion() {
        guard let q = currentQuestion else { return }
        guard q.kind == .providerSearch, q.dynamicProviderTypes != nil else { return }
        let resolved = q.resolvedProviderTypes(state: state)
        guard resolved.isEmpty else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        recordSkipForToast(reason: .previousAnswerMakesItIrrelevant)
        Task { await persistState() }
        advance()
    }

    // MARK: - Internals

    private func persist(answer: HouseQuizAnswer, for question: HouseQuizQuestion) async {
        isSaving = true
        defer { isSaving = false }

        // Apr 7, 2026 (build 82): capture the prior answer BEFORE we
        // overwrite local state. If the user is CHANGING a previously
        // answered question (e.g. asphalt → tile roof), we need to run
        // the reconciler after the new answer is applied so stale
        // home_systems / maintenance_tasks from the old answer get
        // cleaned up. Without this, switching answers leaves orphan
        // tasks in the property — the user ends up with both asphalt
        // AND tile roof inspections on their schedule. The reconciler
        // is idempotent and knows how to soft-delete tasks whose
        // template doesn't match the current confirmed subtype.
        let priorAnswer = state.answers[question.id]
        let isAnswerChange = priorAnswer != nil
            && (priorAnswer?.answerId != answer.answerId
                || priorAnswer?.selectedIds != answer.selectedIds
                || priorAnswer?.customText != answer.customText)

        // 1. Update local state immediately.
        state.answers[question.id] = answer
        state.savedForLater.removeAll { $0 == question.id }
        state.skipped.removeAll { $0 == question.id }

        // Phase 60.3: accrete the protection meter by the per-question
        // delta. Only fires on FIRST answer (not when the user edits an
        // answer they've already locked in) so the meter is monotonic.
        if priorAnswer == nil {
            accreteValueMeter(for: question.id, answer: answer)
        }

        // 2. Fire the answer mapper for DB side-effects. Capture any
        //    reconciler changes so the completion summary can show real
        //    numbers without faking them.
        let result = await mapper.apply(question: question, answer: answer)
        if !result.isEmpty {
            reconciliationTotals = reconciliationTotals.merging(result)
        }

        // 3. Persist quiz state JSONB.
        await persistState()

        // 4. Phase 17b — once the user has answered everything, run a
        //    full-property reconcile pass to catch any system whose subtype
        //    was inferred from sibling answers but never directly confirmed,
        //    plus orphaned legacy tasks. Notification posts so the dashboard
        //    refreshes its task counts.
        if state.completedAt != nil && !finalReconciliationDidRun {
            // Build 90: detach the reconciler so the completion screen
            // appears immediately instead of hanging for 10-15 seconds.
            //
            // Build 90 fix: keep a handle on the task (was fire-and-forget)
            // so `loadFinaleTotals()` can `await` it before reading the
            // counts that drive the cinematic reveal.
            finalReconciliationDidRun = true
            let propId = property.id
            let hhId = property.householdId
            finalReconcileTask = Task.detached(priority: .utility) { [weak self] in
                // Phase 54A: ensure the Vendor-Coverage-known-but-
                // quiz-silent systems (Handyman, Mosquito & Tick, Pet
                // Waste / Chimney / Snow Removal where applicable)
                // exist BEFORE the reconciler runs so their templates
                // get attached on this same pass.
                await HouseQuizAnswerMapper.ensureAutoCreatedSystems(
                    propertyId: propId,
                    householdId: hhId
                )
                let result = await MaintenanceTaskReconciler.reconcileAll(
                    propertyId: propId,
                    householdId: hhId
                )
                // Phase 66: Day1TaskCurator runs after reconcileAll so it
                // sees every freshly-seeded template task. Idempotent via
                // UserDefaults gate (hasRunDay1Curator_<propertyId>_v1) so
                // back-nav / re-completions don't re-route tasks that
                // already have a parent routine assigned.
                let day1 = await Day1TaskCurator.runIfNeeded(
                    propertyId: propId,
                    householdId: hhId
                )

                // Chez v1: ATTOM pre-fill runs RIGHT after Day1Curator
                // so the structural categories (roof, foundation,
                // crawl space) land with `source = 'estimated'` BEFORE
                // we compute the sweep list. The sweep then surfaces
                // these as one-tap confirms first, with everything
                // else queued behind.
                if let yearBuilt = await Self.fetchYearBuilt(for: propId) {
                    _ = await InstallDatePrefiller.prefill(
                        propertyId: propId,
                        yearBuilt: yearBuilt
                    )
                }

                // Compute which systems still need the user's
                // confirmation. Two cohorts:
                //   1. install_date_source IS NULL — never been asked
                //   2. ATTOM pre-fill landed and hasn't been confirmed
                //      yet (source = 'estimated' AND attom_prefilled
                //      AND confirmed_at IS NULL). One-tap accept first.
                let allSystems = (try? await DatabaseService.shared.fetchHomeSystems(propertyId: propId)) ?? []
                let unverified = allSystems
                    .filter { $0.parentSystemId == nil }
                    .filter { !SystemGroup.isServiceCategory($0.category) }
                    .filter { sys in
                        if sys.installDateSource == nil { return true }
                        if sys.installDateSource == "estimated"
                            && sys.installDateAttomPrefilled == true
                            && sys.installDateConfirmedAt == nil {
                            return true
                        }
                        return false
                    }
                    .sorted { lhs, rhs in
                        // ATTOM-prefilled rows (one-tap confirms) come
                        // first so the user gets early wins.
                        let lhsPrefilled = lhs.installDateAttomPrefilled == true
                        let rhsPrefilled = rhs.installDateAttomPrefilled == true
                        if lhsPrefilled != rhsPrefilled { return lhsPrefilled }
                        return lhs.displayName < rhs.displayName
                    }

                // Hop back to the actor and apply the results in one
                // method call. Calling `self?.applyReconcileResult(...)`
                // crosses the isolation boundary cleanly, so Swift 6
                // doesn't flag a captured-var-self read across an
                // await like an inline `MainActor.run` would.
                await self?.applyReconcileResult(
                    result: result,
                    day1: day1,
                    unverified: unverified
                )
            }
        } else if isAnswerChange {
            // Build 82 (Apr 7, 2026): the user changed a previously
            // committed answer. Run the reconciler in the background to
            // clean up tasks that match the OLD answer but not the new
            // one. Detached so the user doesn't wait for it; the
            // notification still fires when it completes so the
            // dashboard refreshes.
            let priorId: String = priorAnswer?.answerId ?? "nil"
            let newId: String = answer.answerId ?? "nil"
            print("[HouseQuiz] Answer changed for \(question.id) (\(priorId) → \(newId)). Running reconciler")
            let propId = property.id
            let hhId = property.householdId
            Task.detached(priority: .utility) {
                let result = await MaintenanceTaskReconciler.reconcileAll(
                    propertyId: propId,
                    householdId: hhId
                )
                print("[HouseQuiz] Change reconciler completed: \(result)")
                NotificationCenter.default.post(name: .maintenanceTaskChanged, object: nil)
            }
        }

        Analytics.track(.quizQuestionAnswered, [
            "question_id": question.id,
            "section": question.section.rawValue,
        ])
    }

    /// Phase 19 — throwing variant so callers (saveAndExit) can react to
    /// failures and surface them in the UI rather than silently dropping
    /// state on the floor.
    ///
    /// Build 85: completion now also requires that there are no
    /// unanswered saved-for-later questions. The user has to either
    /// answer or explicitly skip every saved item before
    /// `state.completedAt` flips. This is what stops the quiz from
    /// silently rendering "Quiz complete" while saved questions are
    /// still parked in `state.savedForLater` and would otherwise be
    /// invisible.
    private func persistStateThrowing() async throws {
        let total = allQuestions.count - state.skipped.count
        let hasUnresolvedSaved = state.savedForLater.contains { state.answers[$0] == nil }

        // Phase 85: when all intake questions are resolved, flip
        // intakeCompletedAt. The legacy `completedAt` field stays nil
        // until the WALKTHROUGH completes (per the new two-phase model)
        // — that's what gates the cinematic reveal.
        //
        // Back-compat: pre-Phase-85 rows have completedAt populated and
        // intakeCompletedAt copied forward by the model's resilient
        // decoder, so the quiz won't appear to "regress" for users who
        // already finished the old single-pass quiz.
        if state.answers.count >= total, total > 0, !hasUnresolvedSaved, state.intakeCompletedAt == nil {
            state.intakeCompletedAt = Date()
            Analytics.track(.quizCompleted)  // existing event — fires at intake completion
        }

        var update = PropertyUpdate()
        update.houseQuizState = state
        _ = try await db.updateProperty(id: property.id, update)
        NotificationCenter.default.post(name: .propertyChanged, object: nil)
    }

    // MARK: - Phase 85 path-decision API

    /// Records the homeowner's choice of path after intake completes.
    /// Persists the state immediately; subsequent UI routing decisions
    /// read `state.typedChosenPath`.
    func choosePath(_ path: HouseQuizPath) async {
        state.typedChosenPath = path
        state.typedWalkthroughMode = path == .selfServe ? .selfServe : .handymanAssessment
        Analytics.track(.quizPathChosen, ["path": path.rawValue])
        await persistState()
    }

    /// Marks the walk-through completed (self-serve path only — the
    /// handyman path flips this from the chez-concierge ingestion
    /// pipeline server-side). Also sets `completedAt` for back-compat
    /// with surfaces that still read the old field.
    func markWalkthroughComplete() async {
        guard state.walkthroughCompletedAt == nil else { return }
        state.walkthroughCompletedAt = Date()
        if state.completedAt == nil {
            state.completedAt = state.walkthroughCompletedAt
        }
        Analytics.track(.quizWalkthroughCompleted, [
            "mode": state.walkthroughMode ?? "unknown",
        ])
        await persistState()
    }

    /// Backwards-compatible wrapper used by the per-answer auto-save path.
    /// Logs failures but never throws.
    private func persistState() async {
        do {
            try await persistStateThrowing()
        } catch {
            print("[HouseQuizViewModel] persistState failed: \(error)")
            Analytics.track(.quizPersistFailed, ["error": "\(error)"])
        }
    }

    /// Phase 19 — explicit save the X button confirmation dialog awaits
    /// before dismissing. On success sets `savedAndReady = true`. On failure
    /// sets `saveErrorMessage` so the view can show a Retry banner. The
    /// in-memory `state` is left intact either way so the user never loses
    /// their answers in front of them.
    func saveAndExit() async {
        isSaving = true
        savedAndReady = false
        saveErrorMessage = nil
        defer { isSaving = false }
        do {
            try await persistStateThrowing()
            savedAndReady = true
            Analytics.track(.quizSavedAndExited, [
                "answered": state.answers.count,
                "saved_for_later": state.savedForLater.count,
            ])
        } catch {
            saveErrorMessage = "Couldn't save your progress. Check your connection and try again."
            Analytics.track(.quizSaveAndExitFailed, ["error": "\(error)"])
        }
    }

    /// Phase 95 (gap #7) — mid-quiz handover to handyman mode.
    ///
    /// Saves whatever answers the user has so far, fires the
    /// `requestHomeAssessment` Edge Function for the active property,
    /// stamps `assessment_mode = "handyman"` on `properties.attributes`
    /// so the Dashboard's HomeAssessmentPendingCard renders. Mirrors
    /// the OnboardingViewModel.applyModeChoice(.handyman) flow except
    /// the user is mid-quiz, not on the mode-fork screen.
    ///
    /// On success, sets `savedAndReady = true` so the view can dismiss
    /// the same way it does after a normal save+exit. Failures fall
    /// through to `saveErrorMessage` like the regular saveAndExit path.
    func switchToHandymanMode() async {
        isSaving = true
        savedAndReady = false
        saveErrorMessage = nil
        defer { isSaving = false }

        // Always persist quiz answers first. If the user backs out of
        // handyman later or the API call fails, their work is preserved.
        do {
            try await persistStateThrowing()
        } catch {
            saveErrorMessage = "Couldn't save your progress before switching. Check your connection and try again."
            Analytics.track(.quizMidQuizHandymanFailed, ["error": "\(error)", "stage": "persist"])
            return
        }

        // Stamp the mode attribute (best-effort — same pattern as
        // OnboardingViewModel).
        do {
            _ = try await DatabaseService.shared.updatePropertyAttribute(
                propertyId: property.id,
                key: "assessment_mode",
                value: .string("handyman")
            )
        } catch {
            print("[HouseQuiz] mid-quiz handyman: assessment_mode stamp failed: \(error)")
        }

        // Fire the request. On hard failure surface a banner; the user
        // can retry from the dialog.
        do {
            _ = try await HavenSupabase.requestHomeAssessment(
                propertyId: property.id.uuidString,
                householdId: property.householdId.uuidString,
                homeownerConcerns: nil,
                homeownerPresent: true,
                homeownerAccessNotes: nil,
                isExistingUserSupplement: false
            )
            savedAndReady = true
            Analytics.track(.quizMidQuizHandymanSwitched, [
                "answered": state.answers.count,
            ])
        } catch {
            saveErrorMessage = "Couldn't request the Chez handyman visit. Try again."
            Analytics.track(.quizMidQuizHandymanFailed, ["error": "\(error)", "stage": "request"])
        }
    }

    /// Chez v1: lightweight helper to read a property's `year_built`
    /// for ATTOM pre-fill in the post-quiz sweep prep. Returns nil if
    /// the row is missing or the column is null.
    private static func fetchYearBuilt(for propertyId: UUID) async -> Int? {
        let property = try? await DatabaseService.shared.fetchProperty(id: propertyId)
        return property?.yearBuilt
    }

    /// Phase 17b — runs `MaintenanceTaskReconciler.reconcileAll` on the
    /// quiz's property, merges the result into `reconciliationTotals`, and
    /// flips `finalReconciliationDidRun` so the completion view can render
    /// its real-numbers summary. Idempotent: subsequent calls are no-ops
    /// because of the flag check in `persist`.
    ///
    /// Build 87 note: the one-time chore-tracker template cleanup moved to
    /// `AppState.purgeDroppedTemplatesOnce()` so it runs once per device on
    /// auth resolution, not once per quiz completion. This path is now
    /// purely the reconcile pass.
    // Build 90: runFinalReconciliation inlined + detached in persistStateThrowing
    // to eliminate the 10-15s UI hang on quiz completion.

    private func advance() {
        // Show milestone card after questions 5, 10, 15, 20, 25, 30.
        if HouseQuizQuestionLibrary.milestoneIndices.contains(currentIndex) {
            showMilestoneCard = true
            return
        }
        moveNext()

        // Build 85: after moving forward, if there are no more fresh
        // questions but there are still saved-for-later questions on
        // file, route to the saved review screen instead of letting the
        // view fall through to the completion view (which would
        // misleadingly say "Quiz complete" while saved items are
        // parked invisibly). The same dead-end check fires from the
        // view's routing branch as a belt-and-suspenders for cases
        // where moveNext didn't go through advance() (e.g., goBack →
        // forward navigation, or a resume that landed past the end).
        if currentQuestion == nil && hasUnresolvedSavedQuestions {
            showSavedReviewScreen = true
        }
    }

    func dismissMilestoneAndContinue() {
        showMilestoneCard = false
        moveNext()
    }

    /// Build 84 — Fetches the forwarding email address for the current
    /// household via `DatabaseService.shared.fetchHouseholdEmailAddress()`
    /// and caches it for the Q17 milestone reveal. Called from the view's
    /// `.task` block on first appear so the address is loaded well before
    /// the user reaches Q17. Silent fail on error — if the fetch errors
    /// out, the Q17 milestone falls back to the generic milestone card.
    func loadForwardingEmailIfNeeded() async {
        guard cachedHouseholdEmail == nil else { return }
        do {
            cachedHouseholdEmail = try await db.fetchHouseholdEmailAddress()
        } catch {
            print("[HouseQuiz] Failed to fetch forwarding email: \(error)")
        }
    }

    /// Build 85: clear the persisted answer for a specific question. Used
    /// when the user taps the "Currently selected" pinned card on a
    /// providerSearch question to start over. The maintenance-task
    /// reconciler from earlier builds handles task cleanup; per-question
    /// cleanup of `utility_accounts` / `family_members` rows when
    /// re-answering is the Build 86 mapper-idempotency item.
    func clearAnswer(for questionId: String) async {
        state.answers.removeValue(forKey: questionId)
        await persistState()
    }

    // MARK: - Build 85: Saved-for-later review flow

    /// Build 85: true when the user has at least one saved-for-later
    /// question that hasn't been answered yet. Drives the trailing
    /// toolbar pill visibility and the dead-end auto-routing in
    /// `advance()` and the view body.
    var hasUnresolvedSavedQuestions: Bool {
        state.savedForLater.contains { questionId in
            state.answers[questionId] == nil
        }
    }

    /// Build 85: the list of saved-for-later questions that the user
    /// hasn't answered yet, resolved into the full HouseQuizQuestion
    /// objects so the saved review list can render section + title +
    /// chevron without re-looking-up the library on every cell render.
    var unresolvedSavedQuestions: [HouseQuizQuestion] {
        state.savedForLater.compactMap { questionId in
            guard state.answers[questionId] == nil else { return nil }
            return allQuestions.first(where: { $0.id == questionId })
        }
    }

    /// Build 85: returns the index of the next unanswered, non-saved,
    /// non-skipped question, or nil if every fresh question is resolved.
    /// Used by the saved review list's "Keep going forward instead"
    /// escape — when nil, that button hides because there's nowhere
    /// forward to go and the only paths are tap-a-saved-question or
    /// skip-all-and-finish.
    var firstUnresolvedFreshIndex: Int? {
        for (index, q) in allQuestions.enumerated() {
            if state.answers[q.id] == nil
                && !state.skipped.contains(q.id)
                && !state.savedForLater.contains(q.id) {
                return index
            }
        }
        return nil
    }

    /// Build 85: jump to a specific saved question from the review list.
    /// Removes it from `savedForLater` (it's no longer "saved", it's
    /// being actively answered now) and sets `currentIndex` to its
    /// position. Clears `showSavedReviewScreen` so the view routes back
    /// to the question screen.
    func jumpToSavedQuestion(_ question: HouseQuizQuestion) {
        state.savedForLater.removeAll { $0 == question.id }
        if let index = allQuestions.firstIndex(where: { $0.id == question.id }) {
            currentIndex = index
        }
        showSavedReviewScreen = false
        Task { await persistState() }
        Analytics.track(.quizSavedResumed, ["question_id": question.id])
    }

    /// Build 85: skip all remaining saved questions so the quiz can
    /// finish. Used from the saved review list's "Skip these and finish
    /// the quiz" footer button after a confirmation dialog. Adds every
    /// remaining unanswered saved question to `state.skipped`, clears
    /// the saved list, and re-fires persistence so the completion check
    /// runs against the updated state.
    func skipAllSavedAndFinish() {
        for questionId in state.savedForLater where state.answers[questionId] == nil {
            if !state.skipped.contains(questionId) {
                state.skipped.append(questionId)
            }
        }
        state.savedForLater.removeAll { state.answers[$0] == nil }
        showSavedReviewScreen = false
        Task {
            await persistState()
            // After persistence the completion check inside
            // persistStateThrowing has had its chance to flip
            // completedAt — but in case the user hadn't yet hit the
            // total threshold and now does post-skips, fall through to
            // the same check here so the second persist actually fires.
            let total = allQuestions.count - state.skipped.count
            let stillUnresolved = state.savedForLater.contains { state.answers[$0] == nil }
            if state.answers.count >= total, total > 0, !stillUnresolved, state.completedAt == nil {
                state.completedAt = Date()
                await persistState()
            }
        }
        Analytics.track(.quizSavedSkippedAll)
    }

    private func moveNext() {
        currentIndex += 1
        skipQuestionsAfterZeroVehicles()
        // Phase 18b: After advancing, also skip any provider-search question
        // whose dynamic types resolved to empty (Q19 with electric heat).
        skipDynamicallyUnreachableQuestion()
        // Phase 19j: also skip any question whose dynamicSkip closure
        // returns true based on prior answers (Q11b after no_lawn,
        // Q14 after no_lawn).
        skipDynamicallyHiddenQuestion()
    }

    /// Phase 19j — checks the current question's dynamicSkip closure and,
    /// if it returns true, marks it skipped and advances. Loops via
    /// moveNext() so consecutive skip-eligible questions all flush in one
    /// pass (e.g. Q11b and Q14 after a no_lawn answer).
    ///
    /// Phase 60.3: also accumulates a `pendingSkipToast` so the next
    /// rendered question acknowledges the auto-skip.
    func skipDynamicallyHiddenQuestion() {
        guard let q = currentQuestion else { return }
        guard let skipClosure = q.dynamicSkip else { return }
        guard skipClosure(state) else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        recordSkipForToast(reason: .previousAnswerMakesItIrrelevant)
        Task { await persistState() }
        moveNext()
    }

    /// Phase 60.3: Accumulate a skip into `pendingSkipToast` so the next
    /// question render shows "Skipped N questions" messaging. Merging
    /// same-reason skips lets consecutive dynamicSkip advances (e.g.
    /// Q11b + Q14 after no_lawn) surface as one toast instead of two.
    private func recordSkipForToast(reason: SkipReason) {
        if let existing = pendingSkipToast, existing.reason == reason {
            pendingSkipToast = SkipToastPayload(
                skippedCount: existing.skippedCount + 1,
                reason: reason
            )
        } else {
            pendingSkipToast = SkipToastPayload(skippedCount: 1, reason: reason)
        }
    }

    private func firstUnresolvedIndex() -> Int {
        // Phase 19 — also skip savedForLater questions, otherwise resume
        // lands the user back on the question they explicitly chose to defer.
        for (index, q) in allQuestions.enumerated() {
            if state.answers[q.id] == nil
                && !state.skipped.contains(q.id)
                && !state.savedForLater.contains(q.id) {
                return index
            }
        }
        return allQuestions.count
    }

    /// Apply the post-quiz reconcile + Day1 routing results onto the
    /// view-model. Pulled out of the inline `MainActor.run` so the
    /// outer `Task.detached { [weak self] in ... }` doesn't read a
    /// captured-var `self` across an await — that's the Swift 6
    /// strict-concurrency warning the compiler flags.
    @MainActor
    fileprivate func applyReconcileResult(
        result: MaintenanceTaskReconciler.ReconciliationResult,
        day1: Day1TaskCurator.Result,
        unverified: [HomeSystemRow]
    ) {
        if !result.isEmpty {
            reconciliationTotals = reconciliationTotals.merging(result)
        }
        if !day1.isEmpty {
            print("[HouseQuiz] Day1Curator: vendor=\(day1.vendorRouted) pendingVendor=\(day1.pendingVendorRouted) handyman=\(day1.handymanRouted) thisSeason=\(day1.remainingInThisSeason) routinesCreated=\(day1.routinesCreated)")
        }
        unverifiedSystemsForSweep = unverified
        installDateSweepNeeded = !unverified.isEmpty
        if unverified.isEmpty {
            installDateSweepDone = true
        }
        NotificationCenter.default.post(name: .maintenanceTaskChanged, object: nil)
        NotificationCenter.default.post(name: .routineChanged, object: nil)
    }
}
