import SwiftUI

@MainActor
final class HouseQuizViewModel: ObservableObject {
    let property: PropertyRow
    let allQuestions: [HouseQuizQuestion]

    @Published var state: HouseQuizState
    @Published var currentIndex: Int = 0
    @Published var pendingFeedback: AnswerFeedback?
    @Published var showMilestoneCard: Bool = false
    @Published var showSkipForeverConfirm: Bool = false
    @Published var isSaving: Bool = false
    @Published var providerCaptureForAnswerId: String?
    @Published var providerCaptureText: String = ""

    /// Phase 19 — set to true after `saveAndExit()` successfully persists state
    /// to Supabase. The view's confirmation dialog watches this to decide
    /// whether to dismiss. Reset to false at the start of each save.
    @Published var savedAndReady: Bool = false
    /// Phase 19 — populated when `saveAndExit()` fails so the view can render
    /// an inline error banner with a Retry action. Cleared on retry success.
    @Published var saveErrorMessage: String?

    /// Phase 17b — running totals from `MaintenanceTaskReconciler`. Each
    /// answer that touches a system subtype merges its result into this; the
    /// final `runFinalReconciliation()` pass after the last question merges
    /// the orphan/whole-property cleanup. The completion view reads this to
    /// show "we added X, removed Y" with REAL numbers, never fakes them.
    @Published var reconciliationTotals: MaintenanceTaskReconciler.ReconciliationResult = .empty
    /// Set to `true` after `runFinalReconciliation()` finishes so the
    /// completion view can swap from a brief loading caption to the real
    /// summary. Defaults to `false` so an unfinished quiz never shows stale
    /// numbers.
    @Published var finalReconciliationDidRun: Bool = false

    /// Phase 16c — when the user picks an auto carrier that also offers home
    /// insurance (per `bundles_with_home`), we stash the row here so the q27
    /// render can show a "Looks like {name} also does home" suggestion card
    /// instead of forcing a duplicate search.
    @Published var bundledHomeSuggestion: UtilityProviderRow?
    /// Mirror flow for the reverse direction: if the user somehow answers q27
    /// before q26, the home carrier with `bundles_with_auto` becomes the
    /// suggestion shown above q26's auto picker.
    @Published var bundledAutoSuggestion: UtilityProviderRow?

    /// Build 84 — forwarding email address fetched once on view appear and
    /// surfaced inside the Q17 milestone card. Cached here so the view doesn't
    /// have to re-fetch or handle loading state at milestone time. The address
    /// is auto-generated by the `household_email_addresses` DB trigger when
    /// the household is created, so it always exists by the time the user
    /// reaches the quiz.
    @Published var cachedHouseholdEmail: String?

    /// Build 85 — true when the user is viewing the saved-for-later review
    /// list instead of a question screen. Toggled by the trailing toolbar
    /// pill and auto-set when the user reaches the end of fresh questions
    /// with saved items still pending. Cleared when the user taps a saved
    /// question to jump into it or taps "Keep going forward instead" to
    /// resume the normal flow.
    @Published var showSavedReviewScreen: Bool = false

    /// Build 86 — Q28 dedup. Cached snapshot of `family_members` for the
    /// household, loaded once on init via the background refresh path so
    /// `caretakersBody` can check whether a spouse / partner / child was
    /// already added (e.g. via the dashboard household strip "+" button or
    /// the AccountCreationStep spouse invite flow) BEFORE re-showing the
    /// Q28 sub-steps that would create a duplicate. Empty until the fetch
    /// resolves; views should fail open and render the spouse / kids form
    /// when the cache hasn't loaded yet.
    @Published var existingFamilyMembers: [FamilyMemberRow] = []

    private let mapper: HouseQuizAnswerMapper
    private let db = DatabaseService.shared

    init(property: PropertyRow) {
        self.property = property
        self.allQuestions = HouseQuizQuestionLibrary.allQuestions
        self.state = property.houseQuizState ?? HouseQuizState(startedAt: Date())
        self.mapper = HouseQuizAnswerMapper(householdId: property.householdId, propertyId: property.id)

        // Resume at the first unanswered+unsaved+unskipped question.
        self.currentIndex = firstUnresolvedIndex()
        // Phase 18b: A resumed quiz might land on a question whose dynamic
        // provider types resolve to empty (e.g. Q19 when Q3 was electric).
        // Mark it skipped and advance immediately so the user never sees a
        // dead picker.
        skipDynamicallyUnreachableQuestion()
        // Phase 19j: Same idea for dynamicSkip — if the resume cursor lands
        // on Q11b/Q14 but the user already answered Q11 with no_lawn, skip
        // those questions on resume too.
        skipDynamicallyHiddenQuestion()

        // Phase 19 — defensive background refresh: the dashboard's cached
        // PropertyRow may be stale (e.g. multi-device, fast resume). If the
        // DB has more answers than our in-memory state, adopt the DB state
        // and re-resolve our cursor.
        Task { @MainActor [weak self] in
            await self?.refreshPropertyStateFromDB()
        }

        // Build 86 — load the household's existing family members so the
        // Q28 caretakers flow can skip the spouse sub-step (and pre-populate
        // kids) when the user already added them via the dashboard "+"
        // button or the spouse invite flow on AccountCreationStep. Failures
        // leave the cache empty, which fails open: the view falls back to
        // showing the full Q28 flow as if no one was on file.
        Task { @MainActor [weak self] in
            await self?.refreshExistingFamilyMembers()
        }
    }

    private func refreshPropertyStateFromDB() async {
        do {
            let fresh = try await db.fetchProperty(id: property.id)
            guard let freshState = fresh.houseQuizState else { return }
            if freshState.answers.count > state.answers.count {
                state = freshState
                currentIndex = firstUnresolvedIndex()
                skipDynamicallyUnreachableQuestion()
                // Phase 19j — same protection on the background refresh path.
                skipDynamicallyHiddenQuestion()
                print("[HouseQuiz] Refreshed state from DB: \(freshState.answers.count) answers, resume index \(currentIndex)")
            }
        } catch {
            print("[HouseQuiz] Background state refresh failed: \(error)")
        }
    }

    /// Build 86 — refreshes the cached snapshot of `family_members` for the
    /// household. Called once on init so `caretakersBody` (Q28) can detect a
    /// pre-existing spouse / partner / child added via the dashboard "+"
    /// button or the AccountCreationStep invite flow and skip the
    /// duplicate-creating sub-steps. Silent failure leaves the cache empty,
    /// which fails open to showing the full Q28 form.
    func refreshExistingFamilyMembers() async {
        do {
            existingFamilyMembers = try await db.fetchFamilyMembers(householdId: property.householdId)
        } catch {
            print("[HouseQuiz] Failed to fetch existing family members: \(error)")
        }
    }

    /// Build 86 — true when the household already has at least one
    /// spouse-shaped relationship on file. Drives Q28's decision to skip the
    /// `QuizSpouseInviteInlineForm` sub-step entirely so re-running Q28
    /// doesn't create a second "Tom Burke" alongside an existing "Tom".
    var existingSpouseCount: Int {
        existingFamilyMembers.filter { member in
            let r = member.relationship.lowercased()
            return r == "spouse"
                || r == "partner"
                || r == "spouse/partner"
                || r == "husband"
                || r == "wife"
        }.count
    }

    /// Build 86 — pre-existing children on the household, sorted oldest
    /// first via the existing `sortedByAge` extension. Q28's kids sub-step
    /// uses this to seed `householdPendingKids` so the user sees their
    /// existing children as editable rows instead of being asked to add
    /// them all over again.
    var existingChildren: [FamilyMemberRow] {
        existingFamilyMembers.filter { member in
            let r = member.relationship.lowercased()
            return r == "child" || r == "son" || r == "daughter"
        }.sortedByAge()
    }

    // MARK: - Derived

    var currentQuestion: HouseQuizQuestion? {
        guard currentIndex >= 0, currentIndex < allQuestions.count else { return nil }
        return allQuestions[currentIndex]
    }

    var progress: Double {
        let total = allQuestions.count - state.skipped.count
        guard total > 0 else { return 1 }
        let answered = state.answers.count
        return min(1.0, Double(answered) / Double(total))
    }

    var progressLabel: String {
        // Apr 7, 2026 (build 82): switched from "X of Y done" to
        // "Question N of Y" so the user sees their CURRENT POSITION in
        // the quiz (1-indexed), not just a count of completed answers.
        // The previous label was easy to misread because the answer
        // count and the current position diverged once the user went
        // back to edit a previous question.
        //
        // Build 85: clamp position to total. When the quiz completes or the
        // user is in saved-review mode, currentIndex can reach or exceed
        // allQuestions.count (34), which made the label read "Question 35
        // of 34". Clamping keeps the math sane in every state. The view
        // also hides the toolbar progress bar entirely on completion and
        // saved-review screens, so this clamp is the belt to the toolbar
        // visibility's suspenders.
        let total = allQuestions.count
        let position = min(max(1, currentIndex + 1), total)
        let saved = state.savedForLater.count
        if saved > 0 {
            return "Question \(position) of \(total) · \(saved) saved"
        }
        return "Question \(position) of \(total)"
    }

    var isAtMilestone: Bool {
        HouseQuizQuestionLibrary.milestoneIndices.contains(currentIndex - 1)
    }

    var isComplete: Bool {
        state.completedAt != nil
    }

    // MARK: - Actions

    /// Persist a single-choice or yes/no answer and advance.
    ///
    /// Apr 7, 2026 (build 82): added a brief 0.35-second pause AFTER
    /// persisting the answer but BEFORE advancing or showing the insight
    /// overlay. This gives the user a moment to register the visual
    /// selection feedback (the chip turning navy + checkmark) so they
    /// don't feel like the screen jumped past their tap. Without this
    /// the chip selection animation runs while the next state is already
    /// rendering, which is jarring.
    func recordAnswer(_ answerId: String, customText: String? = nil, selectedProviderId: UUID? = nil) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: answerId,
            customText: customText,
            selectedIds: nil,
            selectedProviderId: selectedProviderId,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)

        // Brief pause so the user sees the chip selection state.
        try? await Task.sleep(nanoseconds: 350_000_000)

        // Show feedback if available; otherwise advance.
        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: answerId) {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": answerId,
            ])
        } else {
            advance()
        }
    }

    /// Phase 16c — variant that captures the full provider row alongside the
    /// answer. Lets us inspect bundle flags for auto/home insurance questions
    /// so q27 (home) can pre-fill from a q26 (auto) selection and vice versa.
    ///
    /// Phase 18e — also persists the catalog `provider.id` on the answer so
    /// the answer mapper can re-fetch the full record (logo, brand color,
    /// website, phone) at apply time and snapshot it onto the resulting
    /// utility_account row.
    func recordProviderAnswer(provider: UtilityProviderRow) async {
        guard let q = currentQuestion else { return }
        // Insurance bundle hint plumbing happens BEFORE persist so the q27
        // render after persist's advance() can read the flag immediately.
        switch q.id {
        case "q26_auto_insurance":
            if provider.bundlesWithHome == true {
                bundledHomeSuggestion = provider
            } else {
                bundledHomeSuggestion = nil
            }
        case "q27_homeowners_insurance":
            if provider.bundlesWithAuto == true {
                bundledAutoSuggestion = provider
            } else {
                bundledAutoSuggestion = nil
            }
        default:
            break
        }
        let answer = HouseQuizAnswer(
            answerId: "selected",
            customText: provider.name,
            selectedProviderId: provider.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)

        // Build 86: brief pause so the user sees the picker row's navy
        // tint + checkmark feedback before the quiz transitions away.
        // Mirrors the pause `recordAnswer` already has — Tom's wife
        // reported tapping a provider produced no visual change because
        // the picker tore down before the row's selected state had time
        // to render. The visual update happens in
        // `UtilityProviderSearchPicker.providerRow` via `tappedProviderId`.
        try? await Task.sleep(nanoseconds: 350_000_000)

        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: "selected") {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": "selected",
            ])
        } else {
            advance()
        }
    }

    /// Phase 16c — user accepts the bundled suggestion at q27 (or q26 in the
    /// reverse case). Records the answer with the suggested provider's name
    /// and clears the suggestion so it doesn't bleed into a future quiz pass.
    func acceptBundledSuggestion() async {
        guard let q = currentQuestion else { return }
        let suggestion: UtilityProviderRow?
        switch q.id {
        case "q27_homeowners_insurance":
            suggestion = bundledHomeSuggestion
        case "q26_auto_insurance":
            suggestion = bundledAutoSuggestion
        default:
            suggestion = nil
        }
        guard let provider = suggestion else { return }
        bundledHomeSuggestion = nil
        bundledAutoSuggestion = nil
        await recordAnswer("selected", customText: provider.name)
    }

    /// Phase 16c — user rejected the bundled suggestion. Clear it so the
    /// regular search picker takes over without re-rendering the card.
    func dismissBundledSuggestion() {
        bundledHomeSuggestion = nil
        bundledAutoSuggestion = nil
    }

    /// Persist a multi-select answer and advance. `customEntries` carries any
    /// free-form values typed into an "Other"-style option (e.g. q10 appliances
    /// where users can add Sauna, Pellet stove, etc).
    ///
    /// Phase 18c: `secondaryFuelProvider` carries the propane supplier picked
    /// inline on Q20 when the user selected any propane option AND their
    /// primary heating fuel from Q3 isn't already propane. The mapper reads
    /// this at apply time to create a fresh propane utility_account row.
    func recordMultiSelect(
        _ ids: [String],
        customEntries: [String]? = nil,
        secondaryFuelProvider: UtilityProviderRow? = nil
    ) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: nil,
            customText: secondaryFuelProvider?.name,
            selectedIds: ids,
            customEntries: customEntries,
            secondaryFuelProviderId: secondaryFuelProvider?.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Phase 19i — Q22 generator inline form. Persists the generator type
    /// (whole_home / portable / none), the fuel (natural_gas / propane /
    /// diesel), and an optional explicit provider. The mapper reads all three
    /// to create the right system + fuel attribute + utility_account.
    func recordGeneratorAnswer(
        type: String,
        fuelType: String?,
        provider: UtilityProviderRow?
    ) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: type,
            customText: provider?.name,
            generatorFuelType: fuelType,
            generatorProviderId: provider?.id,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        if let fb = HouseQuizFeedbackLibrary.feedback(for: q.id, answerId: type) {
            pendingFeedback = fb
            Analytics.track(.quizFeedbackShown, [
                "question_id": q.id,
                "answer_id": type,
            ])
        } else {
            advance()
        }
    }

    /// Phase 16d — Q28 specific: persist the household answer along with the
    /// kids and expecting entries captured by QuizKidsInlineForm. Caretakers
    /// already flow through `recordMultiSelect` after the inline form
    /// completes — this method only captures the residents type plus the
    /// kid/expecting payload, since those create real family_member rows.
    ///
    /// Build 87 (Home Manager expansion): now also accepts an optional
    /// `homeManagerEntry` captured by `QuizHomeManagerInviteInlineForm`.
    /// The entry is purely a hydration breadcrumb — the actual
    /// `family_members` row + invite is created at form submit time
    /// directly via `HouseholdInviteCoordinator`, so this method only
    /// stashes it on the answer for resume / back-nav.
    func recordHouseholdAnswer(
        residentsId: String,
        kids: [QuizKidEntry],
        expecting: [QuizExpectingEntry],
        homeManagerEntry: HomeManagerEntry? = nil
    ) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: residentsId,
            customText: nil,
            selectedIds: nil,
            customEntries: nil,
            kids: kids.isEmpty ? nil : kids,
            expectingEntries: expecting.isEmpty ? nil : expecting,
            homeManagerEntry: homeManagerEntry,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Persist a currency-style answer (purchase price) and advance.
    func recordCurrencyAnswer(answerId: String, amount: Double) async {
        guard let q = currentQuestion else { return }
        let answer = HouseQuizAnswer(
            answerId: answerId,
            customText: String(Int(amount)),
            selectedIds: nil,
            answeredAt: Date()
        )
        await persist(answer: answer, for: q)
        advance()
    }

    /// Save the current question for later — appears in the dashboard
    /// "X saved questions" hint and resurfaces next launch.
    func saveForLater() {
        guard let q = currentQuestion else { return }
        if !state.savedForLater.contains(q.id) {
            state.savedForLater.append(q.id)
        }
        Analytics.track(.quizSavedForLater, ["question_id": q.id])
        Task { await persistState() }
        advance()
    }

    /// Skip forever — never resurface, user will add the data manually.
    func skipForever() {
        guard let q = currentQuestion else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        // Remove from savedForLater if present.
        state.savedForLater.removeAll { $0 == q.id }
        Analytics.track(.quizSkippedForever, ["question_id": q.id])
        Task { await persistState() }
        advance()
    }

    /// Dismiss the inline feedback card and advance to the next question.
    func dismissFeedback() {
        pendingFeedback = nil
        advance()
    }

    func goBack() {
        guard currentIndex > 0 else { return }
        currentIndex -= 1
        pendingFeedback = nil
    }

    func skipQuestionsAfterZeroVehicles() {
        // If user picked "0 cars" on Q23, skip Q24 (vehicle add) automatically.
        guard let q = currentQuestion, q.id == "q24_vehicle_add" else { return }
        if let prior = state.answers["q23_vehicle_count"], prior.answerId == "0" {
            state.skipped.append("q24_vehicle_add")
            advance()
        }
    }

    /// Phase 18b: Auto-skip provider-search questions whose
    /// `dynamicProviderTypes` resolves to an empty array. Used by Q19 (heating
    /// fuel provider) when the user answered Q3 with electric / geothermal /
    /// not_sure — there's no fuel delivery contract to capture, so the
    /// question silently disappears from the flow. Marks the question as
    /// skipped (not saved-for-later) so the progress label still totals
    /// correctly and `firstUnresolvedIndex()` doesn't try to resume here.
    func skipDynamicallyUnreachableQuestion() {
        guard let q = currentQuestion else { return }
        guard q.kind == .providerSearch, q.dynamicProviderTypes != nil else { return }
        let resolved = q.resolvedProviderTypes(state: state)
        guard resolved.isEmpty else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        Task { await persistState() }
        advance()
    }

    // MARK: - Internals

    private func persist(answer: HouseQuizAnswer, for question: HouseQuizQuestion) async {
        isSaving = true
        defer { isSaving = false }

        // Apr 7, 2026 (build 82): capture the prior answer BEFORE we
        // overwrite local state. If the user is CHANGING a previously
        // answered question (e.g. asphalt → tile roof), we need to run
        // the reconciler after the new answer is applied so stale
        // home_systems / maintenance_tasks from the old answer get
        // cleaned up. Without this, switching answers leaves orphan
        // tasks in the property — the user ends up with both asphalt
        // AND tile roof inspections on their schedule. The reconciler
        // is idempotent and knows how to soft-delete tasks whose
        // template doesn't match the current confirmed subtype.
        let priorAnswer = state.answers[question.id]
        let isAnswerChange = priorAnswer != nil
            && (priorAnswer?.answerId != answer.answerId
                || priorAnswer?.selectedIds != answer.selectedIds
                || priorAnswer?.customText != answer.customText)

        // 1. Update local state immediately.
        state.answers[question.id] = answer
        state.savedForLater.removeAll { $0 == question.id }
        state.skipped.removeAll { $0 == question.id }

        // 2. Fire the answer mapper for DB side-effects. Capture any
        //    reconciler changes so the completion summary can show real
        //    numbers without faking them.
        let result = await mapper.apply(question: question, answer: answer)
        if !result.isEmpty {
            reconciliationTotals = reconciliationTotals.merging(result)
        }

        // 3. Persist quiz state JSONB.
        await persistState()

        // 4. Phase 17b — once the user has answered everything, run a
        //    full-property reconcile pass to catch any system whose subtype
        //    was inferred from sibling answers but never directly confirmed,
        //    plus orphaned legacy tasks. Notification posts so the dashboard
        //    refreshes its task counts.
        if state.completedAt != nil && !finalReconciliationDidRun {
            await runFinalReconciliation()
            NotificationCenter.default.post(name: .maintenanceTaskChanged, object: nil)
        } else if isAnswerChange {
            // Build 82 (Apr 7, 2026): the user changed a previously
            // committed answer. Run the reconciler in the background to
            // clean up tasks that match the OLD answer but not the new
            // one. Detached so the user doesn't wait for it; the
            // notification still fires when it completes so the
            // dashboard refreshes.
            let priorId: String = priorAnswer?.answerId ?? "nil"
            let newId: String = answer.answerId ?? "nil"
            print("[HouseQuiz] Answer changed for \(question.id) (\(priorId) → \(newId)) — running reconciler")
            let propId = property.id
            let hhId = property.householdId
            Task.detached(priority: .utility) {
                let result = await MaintenanceTaskReconciler.reconcileAll(
                    propertyId: propId,
                    householdId: hhId
                )
                print("[HouseQuiz] Change reconciler completed: \(result)")
                NotificationCenter.default.post(name: .maintenanceTaskChanged, object: nil)
            }
        }

        Analytics.track(.quizQuestionAnswered, [
            "question_id": question.id,
            "section": question.section.rawValue,
        ])
    }

    /// Phase 19 — throwing variant so callers (saveAndExit) can react to
    /// failures and surface them in the UI rather than silently dropping
    /// state on the floor.
    ///
    /// Build 85: completion now also requires that there are no
    /// unanswered saved-for-later questions. The user has to either
    /// answer or explicitly skip every saved item before
    /// `state.completedAt` flips. This is what stops the quiz from
    /// silently rendering "Quiz complete" while saved questions are
    /// still parked in `state.savedForLater` and would otherwise be
    /// invisible.
    private func persistStateThrowing() async throws {
        let total = allQuestions.count - state.skipped.count
        let hasUnresolvedSaved = state.savedForLater.contains { state.answers[$0] == nil }
        if state.answers.count >= total, total > 0, !hasUnresolvedSaved, state.completedAt == nil {
            state.completedAt = Date()
            Analytics.track(.quizCompleted)
        }

        var update = PropertyUpdate()
        update.houseQuizState = state
        _ = try await db.updateProperty(id: property.id, update)
        NotificationCenter.default.post(name: .propertyChanged, object: nil)
    }

    /// Backwards-compatible wrapper used by the per-answer auto-save path.
    /// Logs failures but never throws.
    private func persistState() async {
        do {
            try await persistStateThrowing()
        } catch {
            print("[HouseQuizViewModel] persistState failed: \(error)")
            Analytics.track(.quizPersistFailed, ["error": "\(error)"])
        }
    }

    /// Phase 19 — explicit save the X button confirmation dialog awaits
    /// before dismissing. On success sets `savedAndReady = true`. On failure
    /// sets `saveErrorMessage` so the view can show a Retry banner. The
    /// in-memory `state` is left intact either way so the user never loses
    /// their answers in front of them.
    func saveAndExit() async {
        isSaving = true
        savedAndReady = false
        saveErrorMessage = nil
        defer { isSaving = false }
        do {
            try await persistStateThrowing()
            savedAndReady = true
            Analytics.track(.quizSavedAndExited, [
                "answered": state.answers.count,
                "saved_for_later": state.savedForLater.count,
            ])
        } catch {
            saveErrorMessage = "Couldn't save your progress. Check your connection and try again."
            Analytics.track(.quizSaveAndExitFailed, ["error": "\(error)"])
        }
    }

    /// Phase 17b — runs `MaintenanceTaskReconciler.reconcileAll` on the
    /// quiz's property, merges the result into `reconciliationTotals`, and
    /// flips `finalReconciliationDidRun` so the completion view can render
    /// its real-numbers summary. Idempotent: subsequent calls are no-ops
    /// because of the flag check in `persist`.
    ///
    /// Build 87 note: the one-time chore-tracker template cleanup moved to
    /// `AppState.purgeDroppedTemplatesOnce()` so it runs once per device on
    /// auth resolution, not once per quiz completion. This path is now
    /// purely the reconcile pass.
    private func runFinalReconciliation() async {
        let result = await MaintenanceTaskReconciler.reconcileAll(
            propertyId: property.id,
            householdId: property.householdId
        )
        if !result.isEmpty {
            reconciliationTotals = reconciliationTotals.merging(result)
        }
        finalReconciliationDidRun = true
    }

    private func advance() {
        // Show milestone card after questions 5, 10, 15, 20, 25, 30.
        if HouseQuizQuestionLibrary.milestoneIndices.contains(currentIndex) {
            showMilestoneCard = true
            return
        }
        moveNext()

        // Build 85: after moving forward, if there are no more fresh
        // questions but there are still saved-for-later questions on
        // file, route to the saved review screen instead of letting the
        // view fall through to the completion view (which would
        // misleadingly say "Quiz complete" while saved items are
        // parked invisibly). The same dead-end check fires from the
        // view's routing branch as a belt-and-suspenders for cases
        // where moveNext didn't go through advance() (e.g., goBack →
        // forward navigation, or a resume that landed past the end).
        if currentQuestion == nil && hasUnresolvedSavedQuestions {
            showSavedReviewScreen = true
        }
    }

    func dismissMilestoneAndContinue() {
        showMilestoneCard = false
        moveNext()
    }

    /// Build 84 — Fetches the forwarding email address for the current
    /// household via `DatabaseService.shared.fetchHouseholdEmailAddress()`
    /// and caches it for the Q17 milestone reveal. Called from the view's
    /// `.task` block on first appear so the address is loaded well before
    /// the user reaches Q17. Silent fail on error — if the fetch errors
    /// out, the Q17 milestone falls back to the generic milestone card.
    func loadForwardingEmailIfNeeded() async {
        guard cachedHouseholdEmail == nil else { return }
        do {
            cachedHouseholdEmail = try await db.fetchHouseholdEmailAddress()
        } catch {
            print("[HouseQuiz] Failed to fetch forwarding email: \(error)")
        }
    }

    /// Build 85: clear the persisted answer for a specific question. Used
    /// when the user taps the "Currently selected" pinned card on a
    /// providerSearch question to start over. The maintenance-task
    /// reconciler from earlier builds handles task cleanup; per-question
    /// cleanup of `utility_accounts` / `family_members` rows when
    /// re-answering is the Build 86 mapper-idempotency item.
    func clearAnswer(for questionId: String) async {
        state.answers.removeValue(forKey: questionId)
        await persistState()
    }

    // MARK: - Build 85: Saved-for-later review flow

    /// Build 85: true when the user has at least one saved-for-later
    /// question that hasn't been answered yet. Drives the trailing
    /// toolbar pill visibility and the dead-end auto-routing in
    /// `advance()` and the view body.
    var hasUnresolvedSavedQuestions: Bool {
        state.savedForLater.contains { questionId in
            state.answers[questionId] == nil
        }
    }

    /// Build 85: the list of saved-for-later questions that the user
    /// hasn't answered yet, resolved into the full HouseQuizQuestion
    /// objects so the saved review list can render section + title +
    /// chevron without re-looking-up the library on every cell render.
    var unresolvedSavedQuestions: [HouseQuizQuestion] {
        state.savedForLater.compactMap { questionId in
            guard state.answers[questionId] == nil else { return nil }
            return allQuestions.first(where: { $0.id == questionId })
        }
    }

    /// Build 85: returns the index of the next unanswered, non-saved,
    /// non-skipped question, or nil if every fresh question is resolved.
    /// Used by the saved review list's "Keep going forward instead"
    /// escape — when nil, that button hides because there's nowhere
    /// forward to go and the only paths are tap-a-saved-question or
    /// skip-all-and-finish.
    var firstUnresolvedFreshIndex: Int? {
        for (index, q) in allQuestions.enumerated() {
            if state.answers[q.id] == nil
                && !state.skipped.contains(q.id)
                && !state.savedForLater.contains(q.id) {
                return index
            }
        }
        return nil
    }

    /// Build 85: jump to a specific saved question from the review list.
    /// Removes it from `savedForLater` (it's no longer "saved", it's
    /// being actively answered now) and sets `currentIndex` to its
    /// position. Clears `showSavedReviewScreen` so the view routes back
    /// to the question screen.
    func jumpToSavedQuestion(_ question: HouseQuizQuestion) {
        state.savedForLater.removeAll { $0 == question.id }
        if let index = allQuestions.firstIndex(where: { $0.id == question.id }) {
            currentIndex = index
        }
        showSavedReviewScreen = false
        Task { await persistState() }
        Analytics.track(.quizSavedResumed, ["question_id": question.id])
    }

    /// Build 85: skip all remaining saved questions so the quiz can
    /// finish. Used from the saved review list's "Skip these and finish
    /// the quiz" footer button after a confirmation dialog. Adds every
    /// remaining unanswered saved question to `state.skipped`, clears
    /// the saved list, and re-fires persistence so the completion check
    /// runs against the updated state.
    func skipAllSavedAndFinish() {
        for questionId in state.savedForLater where state.answers[questionId] == nil {
            if !state.skipped.contains(questionId) {
                state.skipped.append(questionId)
            }
        }
        state.savedForLater.removeAll { state.answers[$0] == nil }
        showSavedReviewScreen = false
        Task {
            await persistState()
            // After persistence the completion check inside
            // persistStateThrowing has had its chance to flip
            // completedAt — but in case the user hadn't yet hit the
            // total threshold and now does post-skips, fall through to
            // the same check here so the second persist actually fires.
            let total = allQuestions.count - state.skipped.count
            let stillUnresolved = state.savedForLater.contains { state.answers[$0] == nil }
            if state.answers.count >= total, total > 0, !stillUnresolved, state.completedAt == nil {
                state.completedAt = Date()
                await persistState()
            }
        }
        Analytics.track(.quizSavedSkippedAll)
    }

    private func moveNext() {
        currentIndex += 1
        skipQuestionsAfterZeroVehicles()
        // Phase 18b: After advancing, also skip any provider-search question
        // whose dynamic types resolved to empty (Q19 with electric heat).
        skipDynamicallyUnreachableQuestion()
        // Phase 19j: also skip any question whose dynamicSkip closure
        // returns true based on prior answers (Q11b after no_lawn,
        // Q14 after no_lawn).
        skipDynamicallyHiddenQuestion()
    }

    /// Phase 19j — checks the current question's dynamicSkip closure and,
    /// if it returns true, marks it skipped and advances. Loops via
    /// moveNext() so consecutive skip-eligible questions all flush in one
    /// pass (e.g. Q11b and Q14 after a no_lawn answer).
    func skipDynamicallyHiddenQuestion() {
        guard let q = currentQuestion else { return }
        guard let skipClosure = q.dynamicSkip else { return }
        guard skipClosure(state) else { return }
        if !state.skipped.contains(q.id) {
            state.skipped.append(q.id)
        }
        Task { await persistState() }
        moveNext()
    }

    private func firstUnresolvedIndex() -> Int {
        // Phase 19 — also skip savedForLater questions, otherwise resume
        // lands the user back on the question they explicitly chose to defer.
        for (index, q) in allQuestions.enumerated() {
            if state.answers[q.id] == nil
                && !state.skipped.contains(q.id)
                && !state.savedForLater.contains(q.id) {
                return index
            }
        }
        return allQuestions.count
    }
}
