-- Phase 16a: Seed top 50 US auto insurance + top 50 US home insurance providers.
-- Many carriers offer both, resulting in ~75 unique companies and 100 rows total
-- (one row per (company, provider_type) pair). Logos are NULL at seed time and
-- enriched lazily via the `enrich-provider-logos` edge function (which calls
-- `brand-logo` per row) or on first picker render.
--
-- Slug convention: lowercase, hyphen-separated, suffixed with -auto or -home so
-- State Farm ends up as state-farm-auto AND state-farm-home, avoiding slug
-- collisions across provider types. Provider type values intentionally use
-- `home_insurance` (not `homeowners_insurance`) so the iOS quiz library and
-- the catalog speak the same vocabulary.

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    -- ── Auto insurance (top 50) ──
    ('State Farm', 'state-farm-auto', 'auto_insurance', 'https://statefarm.com', ARRAY['US'], NULL),
    ('Geico', 'geico-auto', 'auto_insurance', 'https://geico.com', ARRAY['US'], NULL),
    ('Progressive', 'progressive-auto', 'auto_insurance', 'https://progressive.com', ARRAY['US'], NULL),
    ('Allstate', 'allstate-auto', 'auto_insurance', 'https://allstate.com', ARRAY['US'], NULL),
    ('USAA', 'usaa-auto', 'auto_insurance', 'https://usaa.com', ARRAY['US'], NULL),
    ('Liberty Mutual', 'liberty-mutual-auto', 'auto_insurance', 'https://libertymutual.com', ARRAY['US'], NULL),
    ('Farmers', 'farmers-auto', 'auto_insurance', 'https://farmers.com', ARRAY['US'], NULL),
    ('Nationwide', 'nationwide-auto', 'auto_insurance', 'https://nationwide.com', ARRAY['US'], NULL),
    ('American Family', 'american-family-auto', 'auto_insurance', 'https://amfam.com', ARRAY['US'], NULL),
    ('Travelers', 'travelers-auto', 'auto_insurance', 'https://travelers.com', ARRAY['US'], NULL),
    ('Erie Insurance', 'erie-insurance-auto', 'auto_insurance', 'https://erieinsurance.com', ARRAY['US'], NULL),
    ('Auto-Owners', 'auto-owners-auto', 'auto_insurance', 'https://auto-owners.com', ARRAY['US'], NULL),
    ('The Hartford', 'the-hartford-auto', 'auto_insurance', 'https://thehartford.com', ARRAY['US'], NULL),
    ('MetLife', 'metlife-auto', 'auto_insurance', 'https://metlife.com', ARRAY['US'], NULL),
    ('Mercury Insurance', 'mercury-insurance-auto', 'auto_insurance', 'https://mercuryinsurance.com', ARRAY['US'], NULL),
    ('Kemper', 'kemper-auto', 'auto_insurance', 'https://kemper.com', ARRAY['US'], NULL),
    ('National General', 'national-general-auto', 'auto_insurance', 'https://nationalgeneral.com', ARRAY['US'], NULL),
    ('The General', 'the-general-auto', 'auto_insurance', 'https://thegeneral.com', ARRAY['US'], NULL),
    ('Esurance', 'esurance-auto', 'auto_insurance', 'https://esurance.com', ARRAY['US'], NULL),
    ('Amica', 'amica-auto', 'auto_insurance', 'https://amica.com', ARRAY['US'], NULL),
    ('Chubb', 'chubb-auto', 'auto_insurance', 'https://chubb.com', ARRAY['US'], NULL),
    ('AIG', 'aig-auto', 'auto_insurance', 'https://aig.com', ARRAY['US'], NULL),
    ('The Hanover', 'the-hanover-auto', 'auto_insurance', 'https://hanover.com', ARRAY['US'], NULL),
    ('MAPFRE', 'mapfre-auto', 'auto_insurance', 'https://mapfreinsurance.com', ARRAY['US'], NULL),
    ('Safeco', 'safeco-auto', 'auto_insurance', 'https://safeco.com', ARRAY['US'], NULL),
    ('AAA Auto Club', 'aaa-auto-club-auto', 'auto_insurance', 'https://aaa.com', ARRAY['US'], NULL),
    ('Plymouth Rock', 'plymouth-rock-auto', 'auto_insurance', 'https://plymouthrock.com', ARRAY['US'], NULL),
    ('Infinity Insurance', 'infinity-insurance-auto', 'auto_insurance', 'https://infinityauto.com', ARRAY['US'], NULL),
    ('CSAA Insurance', 'csaa-insurance-auto', 'auto_insurance', 'https://csaa-insurance.aaa.com', ARRAY['US'], NULL),
    ('Root Insurance', 'root-insurance-auto', 'auto_insurance', 'https://joinroot.com', ARRAY['US'], NULL),
    ('Lemonade', 'lemonade-auto', 'auto_insurance', 'https://lemonade.com', ARRAY['US'], NULL),
    ('Metromile', 'metromile-auto', 'auto_insurance', 'https://metromile.com', ARRAY['US'], NULL),
    ('Direct Auto', 'direct-auto-auto', 'auto_insurance', 'https://directauto.com', ARRAY['US'], NULL),
    ('Acuity Insurance', 'acuity-insurance-auto', 'auto_insurance', 'https://acuity.com', ARRAY['US'], NULL),
    ('Pekin Insurance', 'pekin-insurance-auto', 'auto_insurance', 'https://pekininsurance.com', ARRAY['US'], NULL),
    ('Shelter Insurance', 'shelter-insurance-auto', 'auto_insurance', 'https://shelterinsurance.com', ARRAY['US'], NULL),
    ('Titan Insurance', 'titan-insurance-auto', 'auto_insurance', 'https://titaninsurance.com', ARRAY['US'], NULL),
    ('Western National', 'western-national-auto', 'auto_insurance', 'https://wnins.com', ARRAY['US'], NULL),
    ('Cincinnati Insurance', 'cincinnati-insurance-auto', 'auto_insurance', 'https://cinfin.com', ARRAY['US'], NULL),
    ('Westfield Insurance', 'westfield-insurance-auto', 'auto_insurance', 'https://westfieldinsurance.com', ARRAY['US'], NULL),
    ('Safeway Insurance', 'safeway-insurance-auto', 'auto_insurance', 'https://safewayinsurance.com', ARRAY['US'], NULL),
    ('Ally Auto', 'ally-auto', 'auto_insurance', 'https://ally.com', ARRAY['US'], NULL),
    ('Elephant Insurance', 'elephant-insurance-auto', 'auto_insurance', 'https://elephant.com', ARRAY['US'], NULL),
    ('COUNTRY Financial', 'country-financial-auto', 'auto_insurance', 'https://countryfinancial.com', ARRAY['US'], NULL),
    ('Grange Insurance', 'grange-insurance-auto', 'auto_insurance', 'https://grangeinsurance.com', ARRAY['US'], NULL),
    ('Sentry Insurance', 'sentry-insurance-auto', 'auto_insurance', 'https://sentry.com', ARRAY['US'], NULL),
    ('Zurich North America', 'zurich-north-america-auto', 'auto_insurance', 'https://zurichna.com', ARRAY['US'], NULL),
    ('Clearcover', 'clearcover-auto', 'auto_insurance', 'https://clearcover.com', ARRAY['US'], NULL),
    ('Gainsco', 'gainsco-auto', 'auto_insurance', 'https://gainsco.com', ARRAY['US'], NULL),
    ('NJM Insurance', 'njm-insurance-auto', 'auto_insurance', 'https://njm.com', ARRAY['US'], NULL),

    -- ── Home insurance (top 50) ──
    ('State Farm', 'state-farm-home', 'home_insurance', 'https://statefarm.com', ARRAY['US'], NULL),
    ('Allstate', 'allstate-home', 'home_insurance', 'https://allstate.com', ARRAY['US'], NULL),
    ('USAA', 'usaa-home', 'home_insurance', 'https://usaa.com', ARRAY['US'], NULL),
    ('Farmers', 'farmers-home', 'home_insurance', 'https://farmers.com', ARRAY['US'], NULL),
    ('Liberty Mutual', 'liberty-mutual-home', 'home_insurance', 'https://libertymutual.com', ARRAY['US'], NULL),
    ('Nationwide', 'nationwide-home', 'home_insurance', 'https://nationwide.com', ARRAY['US'], NULL),
    ('Travelers', 'travelers-home', 'home_insurance', 'https://travelers.com', ARRAY['US'], NULL),
    ('American Family', 'american-family-home', 'home_insurance', 'https://amfam.com', ARRAY['US'], NULL),
    ('Chubb', 'chubb-home', 'home_insurance', 'https://chubb.com', ARRAY['US'], NULL),
    ('Progressive', 'progressive-home', 'home_insurance', 'https://progressive.com', ARRAY['US'], NULL),
    ('Erie Insurance', 'erie-insurance-home', 'home_insurance', 'https://erieinsurance.com', ARRAY['US'], NULL),
    ('Auto-Owners', 'auto-owners-home', 'home_insurance', 'https://auto-owners.com', ARRAY['US'], NULL),
    ('The Hartford', 'the-hartford-home', 'home_insurance', 'https://thehartford.com', ARRAY['US'], NULL),
    ('MetLife', 'metlife-home', 'home_insurance', 'https://metlife.com', ARRAY['US'], NULL),
    ('Amica', 'amica-home', 'home_insurance', 'https://amica.com', ARRAY['US'], NULL),
    ('Safeco', 'safeco-home', 'home_insurance', 'https://safeco.com', ARRAY['US'], NULL),
    ('MAPFRE', 'mapfre-home', 'home_insurance', 'https://mapfreinsurance.com', ARRAY['US'], NULL),
    ('Mercury Insurance', 'mercury-insurance-home', 'home_insurance', 'https://mercuryinsurance.com', ARRAY['US'], NULL),
    ('Homesite', 'homesite-home', 'home_insurance', 'https://homesite.com', ARRAY['US'], NULL),
    ('Lemonade', 'lemonade-home', 'home_insurance', 'https://lemonade.com', ARRAY['US'], NULL),
    ('Kin Insurance', 'kin-insurance-home', 'home_insurance', 'https://kin.com', ARRAY['US'], NULL),
    ('Hippo Insurance', 'hippo-insurance-home', 'home_insurance', 'https://hippo.com', ARRAY['US'], NULL),
    ('COUNTRY Financial', 'country-financial-home', 'home_insurance', 'https://countryfinancial.com', ARRAY['US'], NULL),
    ('Heritage Insurance', 'heritage-insurance-home', 'home_insurance', 'https://heritagepci.com', ARRAY['US'], NULL),
    ('ASI Insurance', 'asi-insurance-home', 'home_insurance', 'https://americanstrategic.com', ARRAY['US'], NULL),
    ('Stillwater Insurance', 'stillwater-insurance-home', 'home_insurance', 'https://stillwaterinsurance.com', ARRAY['US'], NULL),
    ('Citizens Property', 'citizens-property-home', 'home_insurance', 'https://citizensfla.com', ARRAY['FL'], NULL),
    ('Cincinnati Insurance', 'cincinnati-insurance-home', 'home_insurance', 'https://cinfin.com', ARRAY['US'], NULL),
    ('The Hanover', 'the-hanover-home', 'home_insurance', 'https://hanover.com', ARRAY['US'], NULL),
    ('Westfield Insurance', 'westfield-insurance-home', 'home_insurance', 'https://westfieldinsurance.com', ARRAY['US'], NULL),
    ('Openly Insurance', 'openly-insurance-home', 'home_insurance', 'https://openly.com', ARRAY['US'], NULL),
    ('Branch Insurance', 'branch-insurance-home', 'home_insurance', 'https://ourbranch.com', ARRAY['US'], NULL),
    ('Neptune Flood', 'neptune-flood-home', 'home_insurance', 'https://neptuneflood.com', ARRAY['US'], NULL),
    ('Universal Property', 'universal-property-home', 'home_insurance', 'https://universalproperty.com', ARRAY['FL'], NULL),
    ('People''s Trust', 'peoples-trust-home', 'home_insurance', 'https://peoplestrustinsurance.com', ARRAY['FL'], NULL),
    ('Tower Hill', 'tower-hill-home', 'home_insurance', 'https://thig.com', ARRAY['FL'], NULL),
    ('Armed Forces Insurance', 'armed-forces-insurance-home', 'home_insurance', 'https://afi.org', ARRAY['US'], NULL),
    ('Plymouth Rock', 'plymouth-rock-home', 'home_insurance', 'https://plymouthrock.com', ARRAY['US'], NULL),
    ('NJM Insurance', 'njm-insurance-home', 'home_insurance', 'https://njm.com', ARRAY['US'], NULL),
    ('Grange Insurance', 'grange-insurance-home', 'home_insurance', 'https://grangeinsurance.com', ARRAY['US'], NULL),
    ('Pekin Insurance', 'pekin-insurance-home', 'home_insurance', 'https://pekininsurance.com', ARRAY['US'], NULL),
    ('Encompass Insurance', 'encompass-insurance-home', 'home_insurance', 'https://encompassinsurance.com', ARRAY['US'], NULL),
    ('Foremost Insurance', 'foremost-insurance-home', 'home_insurance', 'https://foremost.com', ARRAY['US'], NULL),
    ('Vermont Mutual', 'vermont-mutual-home', 'home_insurance', 'https://vermontmutual.com', ARRAY['US'], NULL),
    ('Central Insurance', 'central-insurance-home', 'home_insurance', 'https://central-insurance.com', ARRAY['US'], NULL),
    ('ICW Group', 'icw-group-home', 'home_insurance', 'https://icwgroup.com', ARRAY['US'], NULL),
    ('Homeowners of America', 'homeowners-of-america-home', 'home_insurance', 'https://hoaic.com', ARRAY['TX'], NULL),
    ('Frontline Insurance', 'frontline-insurance-home', 'home_insurance', 'https://frontlineins.com', ARRAY['US'], NULL),
    ('UPC Insurance', 'upc-insurance-home', 'home_insurance', 'https://upcinsurance.com', ARRAY['US'], NULL),
    ('Narragansett Bay', 'narragansett-bay-home', 'home_insurance', 'https://nbic.com', ARRAY['US'], NULL)
ON CONFLICT (slug) DO NOTHING;
