-- Phase 18.5: Comprehensive expansion of the utility + insurance provider database.
-- Goal: every common US homeowner can find their provider in the search without
-- needing to type a custom entry. Aim is 50+ rows per category.
--
-- Logo URLs are NULL at seed time. The lazy enrichment background task fetches
-- them from Brandfetch on first picker render.
--
-- All inserts use ON CONFLICT (slug) DO NOTHING so this is safe to re-run and
-- safe to land on top of existing rows.
--
-- Slug convention:
--   - utilities/services: bare slug (e.g. "duke-energy")
--   - companies that span multiple types: type suffix (e.g. "eversource-gas")
--   - insurance: -auto / -home suffix (matches Phase 16a)

-- ============================================================================
-- ELECTRIC PROVIDERS (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('American Electric Power', 'american-electric-power', 'electric', 'https://aep.com', ARRAY['OH','TX','VA','WV','KY','TN','IN','MI','OK','AR','LA'], NULL),
    ('Exelon', 'exelon', 'electric', 'https://exeloncorp.com', ARRAY['IL','PA','MD','NJ','DC','DE'], NULL),
    ('NextEra Energy', 'nextera-energy', 'electric', 'https://nexteraenergy.com', ARRAY['FL','US'], NULL),
    ('Southern Company', 'southern-company', 'electric', 'https://southerncompany.com', ARRAY['AL','GA','MS'], NULL),
    ('PPL Corporation', 'ppl-corporation', 'electric', 'https://pplweb.com', ARRAY['PA','KY','RI'], NULL),
    ('WEC Energy Group', 'wec-energy', 'electric', 'https://wecenergygroup.com', ARRAY['WI','IL','MI','MN'], NULL),
    ('DTE Energy', 'dte-energy', 'electric', 'https://dteenergy.com', ARRAY['MI'], NULL),
    ('Ameren', 'ameren', 'electric', 'https://ameren.com', ARRAY['MO','IL'], NULL),
    ('Edison International', 'edison-international', 'electric', 'https://edison.com', ARRAY['CA'], NULL),
    ('CMS Energy', 'cms-energy', 'electric', 'https://cmsenergy.com', ARRAY['MI'], NULL),
    ('Pinnacle West Capital (APS)', 'aps-arizona', 'electric', 'https://aps.com', ARRAY['AZ'], NULL),
    ('Avista Utilities', 'avista', 'electric', 'https://myavista.com', ARRAY['WA','ID','OR'], NULL),
    ('Black Hills Energy', 'black-hills-energy', 'electric', 'https://blackhillsenergy.com', ARRAY['SD','WY','MT','CO','NE','KS','IA','AR'], NULL),
    ('Alliant Energy', 'alliant-energy', 'electric', 'https://alliantenergy.com', ARRAY['IA','WI','MN','IL'], NULL),
    ('Idaho Power', 'idaho-power', 'electric', 'https://idahopower.com', ARRAY['ID','OR'], NULL),
    ('Salt River Project', 'salt-river-project', 'electric', 'https://srpnet.com', ARRAY['AZ'], NULL),
    ('Tampa Electric (TECO)', 'tampa-electric', 'electric', 'https://tampaelectric.com', ARRAY['FL'], NULL),
    ('We Energies', 'we-energies', 'electric', 'https://we-energies.com', ARRAY['WI'], NULL),
    ('Oncor Electric Delivery', 'oncor', 'electric', 'https://oncor.com', ARRAY['TX'], NULL),
    ('Pepco', 'pepco', 'electric', 'https://pepco.com', ARRAY['DC','MD'], NULL),
    ('PECO Energy', 'peco-energy', 'electric', 'https://peco.com', ARRAY['PA'], NULL),
    ('Baltimore Gas & Electric', 'bge', 'electric', 'https://bge.com', ARRAY['MD'], NULL),
    ('Commonwealth Edison', 'commonwealth-edison', 'electric', 'https://comed.com', ARRAY['IL'], NULL),
    ('Atlantic City Electric', 'atlantic-city-electric', 'electric', 'https://atlanticcityelectric.com', ARRAY['NJ'], NULL),
    ('Delmarva Power', 'delmarva-power', 'electric', 'https://delmarva.com', ARRAY['DE','MD','VA'], NULL),
    ('Potomac Edison', 'potomac-edison', 'electric', 'https://firstenergycorp.com', ARRAY['MD','WV','VA'], NULL),
    ('Ohio Edison', 'ohio-edison', 'electric', 'https://firstenergycorp.com', ARRAY['OH','PA'], NULL),
    ('Toledo Edison', 'toledo-edison', 'electric', 'https://firstenergycorp.com', ARRAY['OH','MI'], NULL),
    ('Cleveland Electric Illuminating', 'cei', 'electric', 'https://firstenergycorp.com', ARRAY['OH'], NULL),
    ('Met-Ed (Metropolitan Edison)', 'met-ed', 'electric', 'https://firstenergycorp.com', ARRAY['PA'], NULL),
    ('Penelec (Pennsylvania Electric)', 'penelec', 'electric', 'https://firstenergycorp.com', ARRAY['PA'], NULL),
    ('Penn Power', 'penn-power', 'electric', 'https://firstenergycorp.com', ARRAY['PA'], NULL),
    ('Jersey Central Power & Light', 'jcpl', 'electric', 'https://firstenergycorp.com', ARRAY['NJ'], NULL),
    ('West Penn Power', 'west-penn-power', 'electric', 'https://firstenergycorp.com', ARRAY['PA'], NULL),
    ('Mon Power', 'mon-power', 'electric', 'https://firstenergycorp.com', ARRAY['WV'], NULL),
    ('Public Service of New Hampshire', 'psnh', 'electric', 'https://eversource.com', ARRAY['NH'], NULL),
    ('United Illuminating', 'united-illuminating', 'electric', 'https://uinet.com', ARRAY['CT'], NULL),
    ('Avangrid', 'avangrid', 'electric', 'https://avangrid.com', ARRAY['NY','ME','CT','MA'], NULL),
    ('Central Maine Power', 'central-maine-power', 'electric', 'https://cmpco.com', ARRAY['ME'], NULL),
    ('NYSEG', 'nyseg', 'electric', 'https://nyseg.com', ARRAY['NY'], NULL),
    ('Rochester Gas & Electric', 'rochester-gas-electric', 'electric', 'https://rge.com', ARRAY['NY'], NULL),
    ('Orange & Rockland Utilities', 'orange-rockland', 'electric', 'https://oru.com', ARRAY['NY','NJ','PA'], NULL),
    ('Long Island Power Authority', 'lipa', 'electric', 'https://lipower.org', ARRAY['NY'], NULL),
    ('Austin Energy', 'austin-energy', 'electric', 'https://austinenergy.com', ARRAY['TX'], NULL),
    ('CPS Energy', 'cps-energy', 'electric', 'https://cpsenergy.com', ARRAY['TX'], NULL),
    ('JEA', 'jea-jacksonville', 'electric', 'https://jea.com', ARRAY['FL'], NULL),
    ('Sacramento Municipal Utility District', 'smud', 'electric', 'https://smud.org', ARRAY['CA'], NULL),
    ('Los Angeles Department of Water & Power', 'ladwp', 'electric', 'https://ladwp.com', ARRAY['CA'], NULL),
    ('Memphis Light, Gas and Water', 'mlgw', 'electric', 'https://mlgw.com', ARRAY['TN'], NULL),
    ('Tennessee Valley Authority', 'tva', 'electric', 'https://tva.com', ARRAY['TN','AL','MS','KY','GA','NC','VA'], NULL),
    ('San Diego Gas & Electric', 'sdge', 'electric', 'https://sdge.com', ARRAY['CA'], NULL),
    ('NV Energy', 'nv-energy', 'electric', 'https://nvenergy.com', ARRAY['NV'], NULL),
    ('PacifiCorp', 'pacificorp', 'electric', 'https://pacificorp.com', ARRAY['UT','OR','WY','WA','CA','ID'], NULL),
    ('Portland General Electric', 'pge-portland', 'electric', 'https://portlandgeneral.com', ARRAY['OR'], NULL),
    ('Puget Sound Energy', 'puget-sound-energy', 'electric', 'https://pse.com', ARRAY['WA'], NULL),
    ('Seattle City Light', 'seattle-city-light', 'electric', 'https://seattle.gov/city-light', ARRAY['WA'], NULL),
    ('Snohomish PUD', 'snohomish-pud', 'electric', 'https://snopud.com', ARRAY['WA'], NULL),
    ('Tacoma Power', 'tacoma-power', 'electric', 'https://mytpu.org', ARRAY['WA'], NULL),
    ('Hawaiian Electric', 'hawaiian-electric', 'electric', 'https://hawaiianelectric.com', ARRAY['HI'], NULL),
    ('Direct Energy', 'direct-energy', 'electric', 'https://directenergy.com', ARRAY['TX','PA','NY','OH','IL'], NULL),
    ('Reliant Energy', 'reliant-energy', 'electric', 'https://reliant.com', ARRAY['TX'], NULL),
    ('TXU Energy', 'txu-energy', 'electric', 'https://txu.com', ARRAY['TX'], NULL),
    ('Constellation Energy', 'constellation', 'electric', 'https://constellation.com', ARRAY['US'], NULL),
    ('Green Mountain Energy', 'green-mountain-energy', 'electric', 'https://greenmountainenergy.com', ARRAY['TX','NJ','MA','PA'], NULL),
    ('Just Energy', 'just-energy', 'electric', 'https://justenergy.com', ARRAY['US'], NULL),
    ('Gexa Energy', 'gexa-energy', 'electric', 'https://gexaenergy.com', ARRAY['TX'], NULL),
    ('Frontier Utilities', 'frontier-utilities', 'electric', 'https://frontierutilities.com', ARRAY['TX'], NULL),
    ('Champion Energy', 'champion-energy', 'electric', 'https://championenergyservices.com', ARRAY['TX'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- INTERNET / CABLE PROVIDERS (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Comcast Business', 'comcast-business', 'internet_cable', 'https://business.comcast.com', ARRAY['US'], NULL),
    ('Mediacom', 'mediacom', 'internet_cable', 'https://mediacomcable.com', ARRAY['IA','GA','MN','MO','IL','AL'], NULL),
    ('Sparklight', 'sparklight', 'internet_cable', 'https://sparklight.com', ARRAY['US'], NULL),
    ('Suddenlink', 'suddenlink', 'internet_cable', 'https://suddenlink.com', ARRAY['US'], NULL),
    ('Atlantic Broadband', 'atlantic-broadband', 'internet_cable', 'https://atlanticbb.com', ARRAY['PA','MD','DE','NH','ME','SC','FL','VA'], NULL),
    ('Astound Broadband (RCN)', 'astound-rcn', 'internet_cable', 'https://astound.com', ARRAY['IL','MA','NY','PA','DC','VA'], NULL),
    ('WOW! (WideOpenWest)', 'wow-internet', 'internet_cable', 'https://wowway.com', ARRAY['MI','OH','IL','IN','TN','SC','GA','AL','FL'], NULL),
    ('Earthlink', 'earthlink', 'internet_cable', 'https://earthlink.net', ARRAY['US'], NULL),
    ('CenturyLink', 'centurylink', 'internet_cable', 'https://centurylink.com', ARRAY['US'], NULL),
    ('Lumen', 'lumen', 'internet_cable', 'https://lumen.com', ARRAY['US'], NULL),
    ('Windstream / Kinetic', 'windstream-kinetic', 'internet_cable', 'https://windstream.com', ARRAY['US'], NULL),
    ('Consolidated Communications', 'consolidated-communications', 'internet_cable', 'https://consolidated.com', ARRAY['US'], NULL),
    ('TDS Telecom', 'tds-telecom', 'internet_cable', 'https://tdstelecom.com', ARRAY['US'], NULL),
    ('Cincinnati Bell', 'cincinnati-bell', 'internet_cable', 'https://cincinnatibell.com', ARRAY['OH','KY','IN'], NULL),
    ('Hawaiian Telcom', 'hawaiian-telcom', 'internet_cable', 'https://hawaiiantel.com', ARRAY['HI'], NULL),
    ('Allo Communications', 'allo-communications', 'internet_cable', 'https://allofiber.com', ARRAY['NE','CO','AZ'], NULL),
    ('Wave Broadband', 'wave-broadband', 'internet_cable', 'https://wavebroadband.com', ARRAY['CA','OR','WA'], NULL),
    ('Grande Communications', 'grande-communications', 'internet_cable', 'https://mygrande.com', ARRAY['TX'], NULL),
    ('Service Electric', 'service-electric', 'internet_cable', 'https://sectv.com', ARRAY['PA','NJ'], NULL),
    ('Blue Ridge Communications', 'blue-ridge', 'internet_cable', 'https://brctv.com', ARRAY['PA'], NULL),
    ('Armstrong', 'armstrong', 'internet_cable', 'https://armstrongonewire.com', ARRAY['PA','OH','WV','MD','NY','KY'], NULL),
    ('Hotwire Communications', 'hotwire', 'internet_cable', 'https://hotwirecommunications.com', ARRAY['FL','PA','NJ','NC','SC'], NULL),
    ('Summit Broadband', 'summit-broadband', 'internet_cable', 'https://summit-broadband.com', ARRAY['FL'], NULL),
    ('GVTC Communications', 'gvtc', 'internet_cable', 'https://gvtc.com', ARRAY['TX'], NULL),
    ('Mid-Hudson Cablevision', 'mid-hudson-cablevision', 'internet_cable', 'https://mhcable.com', ARRAY['NY'], NULL),
    ('Vyve Broadband', 'vyve-broadband', 'internet_cable', 'https://vyvebroadband.com', ARRAY['US'], NULL),
    ('HughesNet', 'hughesnet', 'internet_cable', 'https://hughesnet.com', ARRAY['US'], NULL),
    ('Viasat', 'viasat', 'internet_cable', 'https://viasat.com', ARRAY['US'], NULL),
    ('Rise Broadband', 'rise-broadband', 'internet_cable', 'https://risebroadband.com', ARRAY['US'], NULL),
    ('Verizon 5G Home Internet', 'verizon-5g-home', 'internet_cable', 'https://verizon.com/home/5g', ARRAY['US'], NULL),
    ('AT&T Fiber', 'att-fiber', 'internet_cable', 'https://att.com/internet', ARRAY['US'], NULL),
    ('Ziply Fiber', 'ziply-fiber', 'internet_cable', 'https://ziplyfiber.com', ARRAY['WA','OR','ID','MT'], NULL),
    ('Quantum Fiber', 'quantum-fiber', 'internet_cable', 'https://quantumfiber.com', ARRAY['US'], NULL),
    ('MetroNet', 'metronet', 'internet_cable', 'https://metronet.com', ARRAY['IN','IL','IA','OH','MI','KY'], NULL),
    ('Sonic', 'sonic', 'internet_cable', 'https://sonic.com', ARRAY['CA'], NULL),
    ('Webpass', 'webpass', 'internet_cable', 'https://webpass.net', ARRAY['CA','IL','FL','MA','CO'], NULL),
    ('Greenlight Networks', 'greenlight-networks', 'internet_cable', 'https://greenlightnetworks.com', ARRAY['NY'], NULL),
    ('Fidium Fiber', 'fidium-fiber', 'internet_cable', 'https://fidiumfiber.com', ARRAY['ME','NH','VT','MA'], NULL),
    ('Brightspeed', 'brightspeed', 'internet_cable', 'https://brightspeed.com', ARRAY['US'], NULL),
    ('US Cellular Home Internet', 'uscellular-home', 'internet_cable', 'https://uscellular.com', ARRAY['US'], NULL),
    ('Cable ONE', 'cable-one', 'internet_cable', 'https://cableone.net', ARRAY['US'], NULL),
    ('Buckeye Broadband', 'buckeye-broadband', 'internet_cable', 'https://buckeyebroadband.com', ARRAY['OH','MI'], NULL),
    ('Hargray', 'hargray', 'internet_cable', 'https://hargray.com', ARRAY['SC','GA','FL','AL'], NULL),
    ('North State Communications', 'north-state', 'internet_cable', 'https://northstate.net', ARRAY['NC'], NULL),
    ('Solarus', 'solarus', 'internet_cable', 'https://solarus.com', ARRAY['WI'], NULL),
    ('Nuvera', 'nuvera', 'internet_cable', 'https://nuvera.net', ARRAY['MN','IA'], NULL),
    ('Arvig', 'arvig', 'internet_cable', 'https://arvig.com', ARRAY['MN'], NULL),
    ('Paul Bunyan Communications', 'paul-bunyan', 'internet_cable', 'https://paulbunyan.net', ARRAY['MN'], NULL),
    ('LUS Fiber', 'lus-fiber', 'internet_cable', 'https://lusfiber.com', ARRAY['LA'], NULL),
    ('EPB', 'epb', 'internet_cable', 'https://epb.com', ARRAY['TN'], NULL),
    ('Chattanooga Gig', 'chattanooga-gig', 'internet_cable', 'https://epb.com/fi-speed', ARRAY['TN'], NULL),
    ('Cox Business', 'cox-business', 'internet_cable', 'https://coxbusiness.com', ARRAY['US'], NULL),
    ('Spectrum Business', 'spectrum-business', 'internet_cable', 'https://enterprise.spectrum.com', ARRAY['US'], NULL),
    ('Conterra', 'conterra', 'internet_cable', 'https://conterra.com', ARRAY['US'], NULL),
    ('NetWest Online', 'netwest-online', 'internet_cable', 'https://netwest.com', ARRAY['US'], NULL),
    ('GeoLinks', 'geolinks', 'internet_cable', 'https://geolinks.com', ARRAY['CA','NV','AZ'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- NATURAL GAS UTILITIES (25+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Pacific Gas & Electric (Gas)', 'pge-gas', 'natural_gas', 'https://pge.com', ARRAY['CA'], NULL),
    ('Atmos Energy', 'atmos-energy', 'natural_gas', 'https://atmosenergy.com', ARRAY['TX','LA','MS','TN','KS','CO','KY','VA'], NULL),
    ('NW Natural', 'nw-natural', 'natural_gas', 'https://nwnatural.com', ARRAY['OR','WA'], NULL),
    ('Spire Inc.', 'spire', 'natural_gas', 'https://spireenergy.com', ARRAY['MO','MS','AL'], NULL),
    ('Texas Gas Service', 'texas-gas-service', 'natural_gas', 'https://texasgasservice.com', ARRAY['TX'], NULL),
    ('CenterPoint Energy Gas', 'centerpoint-gas', 'natural_gas', 'https://centerpointenergy.com', ARRAY['MN','MS','OK','TX','AR','LA','OH'], NULL),
    ('Dominion Energy Gas', 'dominion-gas', 'natural_gas', 'https://dominionenergy.com', ARRAY['NC','SC','OH','UT','WV'], NULL),
    ('Piedmont Natural Gas (Duke)', 'piedmont-natural-gas', 'natural_gas', 'https://piedmontng.com', ARRAY['NC','SC','TN'], NULL),
    ('New Jersey Resources', 'njr', 'natural_gas', 'https://njresources.com', ARRAY['NJ'], NULL),
    ('South Jersey Industries', 'sji', 'natural_gas', 'https://sjindustries.com', ARRAY['NJ'], NULL),
    ('UGI Utilities', 'ugi', 'natural_gas', 'https://ugi.com', ARRAY['PA'], NULL),
    ('Washington Gas', 'washington-gas', 'natural_gas', 'https://washingtongas.com', ARRAY['DC','MD','VA'], NULL),
    ('Xcel Energy Gas', 'xcel-energy-gas', 'natural_gas', 'https://xcelenergy.com', ARRAY['CO','MN','ND','SD','MI','WI'], NULL),
    ('Berkshire Gas', 'berkshire-gas', 'natural_gas', 'https://berkshiregas.com', ARRAY['MA'], NULL),
    ('Eversource Gas', 'eversource-gas', 'natural_gas', 'https://eversource.com', ARRAY['CT','MA'], NULL),
    ('Yankee Gas Services', 'yankee-gas', 'natural_gas', 'https://eversource.com', ARRAY['CT'], NULL),
    ('Columbia Gas', 'columbia-gas', 'natural_gas', 'https://columbiagas.com', ARRAY['OH','PA','VA','MD','MA','KY'], NULL),
    ('Vectren', 'vectren', 'natural_gas', 'https://vectren.com', ARRAY['IN','OH'], NULL),
    ('NiSource', 'nisource', 'natural_gas', 'https://nisource.com', ARRAY['IN','OH','PA','VA','MD','KY','MA'], NULL),
    ('Peoples Gas (Chicago)', 'peoples-gas-chicago', 'natural_gas', 'https://peoplesgasdelivery.com', ARRAY['IL'], NULL),
    ('Nicor Gas', 'nicor-gas', 'natural_gas', 'https://nicorgas.com', ARRAY['IL'], NULL),
    ('Questar Gas (Dominion)', 'questar-gas', 'natural_gas', 'https://dominionenergy.com', ARRAY['UT','WY','ID'], NULL),
    ('Southwest Gas', 'southwest-gas', 'natural_gas', 'https://swgas.com', ARRAY['NV','AZ','CA'], NULL),
    ('Cascade Natural Gas', 'cascade-natural-gas', 'natural_gas', 'https://cngc.com', ARRAY['WA','OR'], NULL),
    ('Alagasco', 'alagasco', 'natural_gas', 'https://alagasco.com', ARRAY['AL'], NULL),
    ('Chesapeake Utilities', 'chesapeake-utilities', 'natural_gas', 'https://chpk.com', ARRAY['DE','MD','FL'], NULL),
    ('NSTAR Gas', 'nstar-gas', 'natural_gas', 'https://eversource.com', ARRAY['MA'], NULL),
    ('PSE&G Gas', 'pseg-gas', 'natural_gas', 'https://pseg.com', ARRAY['NJ'], NULL),
    ('Brooklyn Union Gas (National Grid)', 'brooklyn-union-gas', 'natural_gas', 'https://nationalgridus.com', ARRAY['NY'], NULL),
    ('KeySpan Energy Delivery', 'keyspan', 'natural_gas', 'https://nationalgridus.com', ARRAY['NY','MA','RI'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- HEATING OIL PROVIDERS (35+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Approved Oil', 'approved-oil', 'oil', 'https://approvedoil.com', ARRAY['NY'], NULL),
    ('Robison Oil', 'robison-oil', 'oil', 'https://robisonoil.com', ARRAY['NY','CT'], NULL),
    ('Castle Oil Corporation', 'castle-oil', 'oil', 'https://castleoil.com', ARRAY['NY','CT','NJ','PA'], NULL),
    ('Sprague Operating Resources', 'sprague-operating', 'oil', 'https://spragueenergy.com', ARRAY['NH','ME','MA','NY','CT'], NULL),
    ('R.E. Schwartz Oil', 're-schwartz-oil', 'oil', 'https://reschwartz.com', ARRAY['NY'], NULL),
    ('Eastern Propane & Oil', 'eastern-propane-oil', 'oil', 'https://eastenergy.com', ARRAY['NH','ME','MA','VT'], NULL),
    ('Bourne Energy', 'bourne-energy', 'oil', 'https://bourneenergy.com', ARRAY['MA'], NULL),
    ('Penn Heating', 'penn-heating', 'oil', 'https://pennheating.com', ARRAY['PA'], NULL),
    ('Direct Energy Oil', 'direct-energy-oil', 'oil', 'https://directenergy.com', ARRAY['CT','MA','NH','RI','PA','NY','NJ'], NULL),
    ('M&M Energy', 'mm-energy', 'oil', 'https://mmenergy.com', ARRAY['NY'], NULL),
    ('Hocon Heating Oil', 'hocon-oil', 'oil', 'https://hocon.com', ARRAY['CT'], NULL),
    ('Rural Energy Solutions', 'rural-energy-solutions', 'oil', 'https://ruralenergy.com', ARRAY['ME','VT','NH'], NULL),
    ('Webster Oil', 'webster-oil', 'oil', 'https://websteroil.com', ARRAY['MA'], NULL),
    ('Ross Refrigeration & Heating', 'ross-refrigeration', 'oil', 'https://rossrefrigeration.com', ARRAY['NJ'], NULL),
    ('R.E. Lyons & Sons', 'relyons', 'oil', 'https://relyons.com', ARRAY['CT'], NULL),
    ('Cubby Oil & Energy', 'cubby-oil', 'oil', 'https://cubbyoil.com', ARRAY['MA'], NULL),
    ('Atlas Oil', 'atlas-oil', 'oil', 'https://atlasoil.com', ARRAY['MI','OH','TX'], NULL),
    ('Cape Cod Oil', 'cape-cod-oil', 'oil', 'https://capecodoil.com', ARRAY['MA'], NULL),
    ('Burnham Holdings', 'burnham-holdings', 'oil', 'https://burnham.com', ARRAY['PA'], NULL),
    ('Energy Express', 'energy-express', 'oil', 'https://energyexpress.com', ARRAY['NJ','NY','PA','CT'], NULL),
    ('Tom''s Oil', 'toms-oil', 'oil', 'https://tomsoil.com', ARRAY['NY'], NULL),
    ('Suburban Heating Oil', 'suburban-heating-oil', 'oil', 'https://suburbanheating.com', ARRAY['NJ','NY'], NULL),
    ('Valley Energy', 'valley-energy', 'oil', 'https://valleyenergyinc.com', ARRAY['PA','NY'], NULL),
    ('Devine Energy', 'devine-energy', 'oil', 'https://devineenergy.com', ARRAY['NJ','PA'], NULL),
    ('McGee & McGee', 'mcgee-mcgee', 'oil', 'https://mcgeeoil.com', ARRAY['CT'], NULL),
    ('All Seasons Oil', 'all-seasons-oil', 'oil', 'https://allseasonsoil.com', ARRAY['NJ','NY'], NULL),
    ('Crowley Fuels', 'crowley-fuels', 'oil', 'https://crowleyfuels.com', ARRAY['AK'], NULL),
    ('Maine Standard', 'maine-standard', 'oil', 'https://mainestandard.com', ARRAY['ME'], NULL),
    ('Dead River Company', 'dead-river-company', 'oil', 'https://deadriver.com', ARRAY['ME','NH','VT'], NULL),
    ('Fred Cook Oil', 'fred-cook-oil', 'oil', 'https://fredcookoil.com', ARRAY['MA'], NULL),
    ('Polar Industries', 'polar-industries', 'oil', 'https://polarindustries.com', ARRAY['NJ'], NULL),
    ('Combined Energy', 'combined-energy', 'oil', 'https://combinedenergy.com', ARRAY['NJ','NY'], NULL),
    ('CITGO Petroleum', 'citgo-petroleum', 'oil', 'https://citgo.com', ARRAY['US'], NULL),
    ('Phillips 66', 'phillips-66', 'oil', 'https://phillips66.com', ARRAY['US'], NULL),
    ('Heritage Heating Oil', 'heritage-heating-oil', 'oil', 'https://heritagepower.com', ARRAY['NY','NJ'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- PROPANE PROVIDERS (30+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Heritage Propane', 'heritage-propane', 'propane', 'https://heritagepropane.com', ARRAY['US'], NULL),
    ('Inergy Propane', 'inergy-propane', 'propane', 'https://inergypropane.com', ARRAY['US'], NULL),
    ('Northern Energy', 'northern-energy', 'propane', 'https://northernenergy.com', ARRAY['WA','OR'], NULL),
    ('Star Gas Partners', 'star-gas', 'propane', 'https://stargaspartners.com', ARRAY['NY','CT','MA','NJ','PA'], NULL),
    ('Diversified Energy', 'diversified-energy-propane', 'propane', 'https://diversifiedenergy.com', ARRAY['US'], NULL),
    ('Tarantin Tank Sales & Service', 'tarantin-tank', 'propane', 'https://tarantin.com', ARRAY['NJ','PA','DE'], NULL),
    ('Synergy Gas', 'synergy-gas', 'propane', 'https://synergygas.com', ARRAY['NY','NJ','PA'], NULL),
    ('Cherry Hill Propane', 'cherry-hill-propane', 'propane', 'https://cherryhillpropane.com', ARRAY['NJ'], NULL),
    ('Lake Springs Propane', 'lake-springs-propane', 'propane', 'https://lakespringspropane.com', ARRAY['VA','MD'], NULL),
    ('Glasgow Propane', 'glasgow-propane', 'propane', 'https://glasgowpropane.com', ARRAY['MO','IL','KS'], NULL),
    ('Proflame Propane', 'proflame-propane', 'propane', 'https://proflamepropane.com', ARRAY['CA','OR'], NULL),
    ('Bourne Propane', 'bourne-propane', 'propane', 'https://bourneenergy.com', ARRAY['MA'], NULL),
    ('Energy Distribution Partners', 'edp', 'propane', 'https://energydistributionpartners.com', ARRAY['IL','TX','OK','AR'], NULL),
    ('Foster Fuels', 'foster-fuels', 'propane', 'https://fosterfuels.com', ARRAY['VA','NC','SC'], NULL),
    ('Holtzople Heating', 'holtzople-heating', 'propane', 'https://holtzople.com', ARRAY['MD'], NULL),
    ('Ireland Energy Solutions', 'ireland-energy', 'propane', 'https://irelandenergysolutions.com', ARRAY['NJ'], NULL),
    ('Northern Propane Gas', 'northern-propane-gas', 'propane', 'https://northernpropane.com', ARRAY['NY'], NULL),
    ('Park Propane', 'park-propane', 'propane', 'https://parkpropane.com', ARRAY['UT','ID'], NULL),
    ('Propane Carriers', 'propane-carriers', 'propane', 'https://propanecarriers.com', ARRAY['US'], NULL),
    ('Reading Energy Group', 'reading-energy', 'propane', 'https://readingenergy.com', ARRAY['PA'], NULL),
    ('Roush Hardware & Propane', 'roush-propane', 'propane', 'https://roushhardware.com', ARRAY['OH'], NULL),
    ('SemGas', 'semgas', 'propane', 'https://semgas.com', ARRAY['US'], NULL),
    ('Western Propane Gas', 'western-propane', 'propane', 'https://westernpropane.com', ARRAY['CA','NV','AZ'], NULL),
    ('Williams Propane', 'williams-propane', 'propane', 'https://williamspropane.com', ARRAY['NC','SC','VA'], NULL),
    ('Yost Propane', 'yost-propane', 'propane', 'https://yostpropane.com', ARRAY['PA'], NULL),
    ('Sharp Energy', 'sharp-energy', 'propane', 'https://sharpenergy.com', ARRAY['DE','MD','VA','PA'], NULL),
    ('Buchanan Energy', 'buchanan-energy', 'propane', 'https://buchananenergy.com', ARRAY['NE','IA','SD'], NULL),
    ('Conger Industries (Forklift propane)', 'conger', 'propane', 'https://congerindustries.com', ARRAY['US'], NULL),
    ('Dixie Gas & Oil', 'dixie-gas-oil', 'propane', 'https://dixiegasandoil.com', ARRAY['VA','NC'], NULL),
    ('Pinnacle Propane', 'pinnacle-propane', 'propane', 'https://pinnaclepropane.com', ARRAY['TX','OK','LA','AR'], NULL),
    ('Pico Propane', 'pico-propane', 'propane', 'https://picopropane.com', ARRAY['TX','OK','MS','LA'], NULL),
    ('Hilltop Propane', 'hilltop-propane', 'propane', 'https://hilltoppropane.com', ARRAY['ID','UT'], NULL),
    ('Twin Rivers Energy', 'twin-rivers-energy', 'propane', 'https://twinriversenergy.com', ARRAY['MA','RI','CT'], NULL),
    ('Mansfield Energy', 'mansfield-energy', 'propane', 'https://mansfield.energy', ARRAY['US'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- LANDSCAPING / LAWN CARE COMPANIES (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('BrightView Landscapes', 'brightview-landscapes', 'landscaping', 'https://brightview.com', ARRAY['US'], NULL),
    ('The Davey Tree Expert Co.', 'davey-tree', 'landscaping', 'https://davey.com', ARRAY['US'], NULL),
    ('Yellowstone Landscape', 'yellowstone-landscape', 'landscaping', 'https://yellowstonelandscape.com', ARRAY['US'], NULL),
    ('US Lawns', 'us-lawns', 'landscaping', 'https://uslawns.com', ARRAY['US'], NULL),
    ('LawnStarter', 'lawnstarter', 'landscaping', 'https://lawnstarter.com', ARRAY['US'], NULL),
    ('GreenPal', 'greenpal', 'landscaping', 'https://yourgreenpal.com', ARRAY['US'], NULL),
    ('Lawn Love', 'lawn-love', 'landscaping', 'https://lawnlove.com', ARRAY['US'], NULL),
    ('Plowz & Mowz', 'plowz-mowz', 'landscaping', 'https://plowzandmowz.com', ARRAY['US'], NULL),
    ('Scotts Lawn Service', 'scotts-lawn-service', 'landscaping', 'https://scotts.com', ARRAY['US'], NULL),
    ('Massey Services', 'massey-services-lawn', 'landscaping', 'https://masseyservices.com', ARRAY['FL','GA','TX','LA','OK','SC','NC'], NULL),
    ('NaturaLawn of America', 'naturalawn', 'landscaping', 'https://nl-amer.com', ARRAY['US'], NULL),
    ('Heartland Lawns', 'heartland-lawns', 'landscaping', 'https://heartlandlawns.com', ARRAY['NE','IA','MO','KS'], NULL),
    ('The Grounds Guys', 'grounds-guys', 'landscaping', 'https://groundsguys.com', ARRAY['US'], NULL),
    ('Greenscape', 'greenscape', 'landscaping', 'https://greenscapeinc.com', ARRAY['NC','SC','VA'], NULL),
    ('Mariani Landscape', 'mariani-landscape', 'landscaping', 'https://marianilandscape.com', ARRAY['IL'], NULL),
    ('Cagwin & Dorward', 'cagwin-dorward', 'landscaping', 'https://cagwin.com', ARRAY['CA'], NULL),
    ('Schill Grounds Management', 'schill-grounds', 'landscaping', 'https://schillgrounds.com', ARRAY['OH','PA','MI'], NULL),
    ('Russell Landscape', 'russell-landscape', 'landscaping', 'https://russelllandscape.com', ARRAY['GA','SC','FL'], NULL),
    ('McHale Landscape Design', 'mchale-landscape-design', 'landscaping', 'https://mchalelandscape.com', ARRAY['MD','VA','DC'], NULL),
    ('ArtisTree', 'artistree-landscape', 'landscaping', 'https://artistreelm.com', ARRAY['FL'], NULL),
    ('Lambert Landscape Company', 'lambert-landscape', 'landscaping', 'https://lambertlandscape.com', ARRAY['TX'], NULL),
    ('Heads Up Landscaping', 'heads-up-landscaping', 'landscaping', 'https://headsuplandscape.com', ARRAY['NM','TX','CO'], NULL),
    ('Greenleaf Lawn Care', 'greenleaf-lawn-care', 'landscaping', 'https://greenleaflawncare.com', ARRAY['US'], NULL),
    ('Lawn Pride', 'lawn-pride', 'landscaping', 'https://lawnpride.com', ARRAY['IN','OH','KY','TN','GA','FL'], NULL),
    ('Mr. Lawn Care', 'mr-lawn-care', 'landscaping', 'https://mrlawncare.com', ARRAY['US'], NULL),
    ('LawnGuru', 'lawnguru', 'landscaping', 'https://lawnguru.com', ARRAY['US'], NULL),
    ('Mowdo', 'mowdo', 'landscaping', 'https://mowdo.com', ARRAY['US'], NULL),
    ('LawnChamps', 'lawnchamps', 'landscaping', 'https://lawnchamps.com', ARRAY['US'], NULL),
    ('Royal Greens', 'royal-greens', 'landscaping', 'https://royalgreens.com', ARRAY['MD','PA','DE'], NULL),
    ('Tomlinson Bomberger', 'tomlinson-bomberger', 'landscaping', 'https://tomlinsonbomberger.com', ARRAY['PA'], NULL),
    ('Greenforce Landscape', 'greenforce-landscape', 'landscaping', 'https://greenforcelandscape.com', ARRAY['CA'], NULL),
    ('Earth Tones Landscape', 'earth-tones-landscape', 'landscaping', 'https://earthtoneslandscape.com', ARRAY['US'], NULL),
    ('Sunrise Landscape', 'sunrise-landscape', 'landscaping', 'https://sunriselandscape.com', ARRAY['US'], NULL),
    ('Pro-Lawns', 'pro-lawns', 'landscaping', 'https://prolawnscompany.com', ARRAY['US'], NULL),
    ('Garden Design Group', 'garden-design-group', 'landscaping', 'https://gardendesigngroup.com', ARRAY['US'], NULL),
    ('Greenbrier Landscape', 'greenbrier-landscape', 'landscaping', 'https://greenbrierlandscape.com', ARRAY['US'], NULL),
    ('Estate Master Lawn Care', 'estate-master-lawn', 'landscaping', 'https://estatemasterlawncare.com', ARRAY['US'], NULL),
    ('Aspen Grove Landscape', 'aspen-grove-landscape', 'landscaping', 'https://aspengrovelandscape.com', ARRAY['CO'], NULL),
    ('GreenWise Landscaping', 'greenwise-landscaping', 'landscaping', 'https://greenwiseorganic.com', ARRAY['IL','WI','IN'], NULL),
    ('Eden Lawns', 'eden-lawns', 'landscaping', 'https://edenlawns.com', ARRAY['US'], NULL),
    ('Yardly', 'yardly', 'landscaping', 'https://yardly.com', ARRAY['US'], NULL),
    ('SiteOne Landscape Supply', 'siteone-landscape-supply', 'landscaping', 'https://siteone.com', ARRAY['US'], NULL),
    ('Husqvarna Lawn Services', 'husqvarna-lawn', 'landscaping', 'https://husqvarna.com', ARRAY['US'], NULL),
    ('Lawn-A-Mat', 'lawn-a-mat', 'landscaping', 'https://lawnamat.com', ARRAY['US'], NULL),
    ('Handee Lawn', 'handee-lawn', 'landscaping', 'https://handeelawn.com', ARRAY['US'], NULL),
    ('Landscape Workshop', 'landscape-workshop', 'landscaping', 'https://landscapeworkshop.com', ARRAY['AL','TN','GA','MS','FL'], NULL),
    ('Bemus Landscape', 'bemus-landscape', 'landscaping', 'https://bemus.com', ARRAY['CA'], NULL),
    ('Gachina Landscape Management', 'gachina-landscape', 'landscaping', 'https://gachina.com', ARRAY['CA'], NULL),
    ('Park West Companies', 'park-west', 'landscaping', 'https://parkwest.us', ARRAY['CA'], NULL),
    ('Caretaker Landscape', 'caretaker-landscape', 'landscaping', 'https://caretaker-landscape.com', ARRAY['AZ'], NULL),
    ('JBL Landscape', 'jbl-landscape', 'landscaping', 'https://jbllandscaping.com', ARRAY['MA'], NULL),
    ('Blackmore Company', 'blackmore-company', 'landscaping', 'https://blackmoreco.com', ARRAY['MI','OH'], NULL),
    ('Yard Works', 'yard-works-landscaping', 'landscaping', 'https://yardworks-landscape.com', ARRAY['US'], NULL),
    ('Pacific Landscape Management', 'pacific-landscape', 'landscaping', 'https://pacificlandscape.com', ARRAY['OR','WA'], NULL),
    ('NaturalGreen', 'naturalgreen', 'landscaping', 'https://naturalgreen.com', ARRAY['US'], NULL),
    ('Lawn Doctor', 'lawn-doctor-extended', 'landscaping', 'https://lawndoctor.com', ARRAY['US'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- PEST CONTROL COMPANIES (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Rollins Inc.', 'rollins-pest', 'pest_control', 'https://rollins.com', ARRAY['US'], NULL),
    ('Ehrlich Pest Control', 'ehrlich-pest-control', 'pest_control', 'https://jcehrlich.com', ARRAY['US'], NULL),
    ('Rentokil', 'rentokil', 'pest_control', 'https://rentokil-na.com', ARRAY['US'], NULL),
    ('Western Exterminator', 'western-exterminator', 'pest_control', 'https://west.com', ARRAY['CA','AZ','NV','OR','WA'], NULL),
    ('Western Pest Services', 'western-pest-services', 'pest_control', 'https://westernpest.com', ARRAY['NJ','NY','PA','CT'], NULL),
    ('Cook''s Pest Control', 'cooks-pest-control', 'pest_control', 'https://cookspest.com', ARRAY['AL','TN','MS','GA','FL'], NULL),
    ('Arrow Exterminators', 'arrow-exterminators', 'pest_control', 'https://arrowexterminators.com', ARRAY['GA','TN','AL','SC','NC','FL'], NULL),
    ('McCall Service', 'mccall-service', 'pest_control', 'https://mccallservice.com', ARRAY['FL','GA'], NULL),
    ('Hulett Environmental', 'hulett-environmental', 'pest_control', 'https://bugs.com', ARRAY['FL'], NULL),
    ('Northwest Exterminating', 'northwest-exterminating', 'pest_control', 'https://callnorthwest.com', ARRAY['GA'], NULL),
    ('Sprague Pest Solutions', 'sprague-pest', 'pest_control', 'https://spraguepest.com', ARRAY['WA','OR','ID','CA','NV','AZ'], NULL),
    ('Mosquito Squad', 'mosquito-squad', 'pest_control', 'https://mosquitosquad.com', ARRAY['US'], NULL),
    ('Mosquito Joe', 'mosquito-joe', 'pest_control', 'https://mosquitojoe.com', ARRAY['US'], NULL),
    ('Mosquito Authority', 'mosquito-authority', 'pest_control', 'https://mosquitoauthority.com', ARRAY['US'], NULL),
    ('Bug Out Service', 'bug-out-service', 'pest_control', 'https://bugoutservice.com', ARRAY['FL','GA'], NULL),
    ('Bayer Environmental Science', 'bayer-environmental', 'pest_control', 'https://bayer.com', ARRAY['US'], NULL),
    ('Dewey Pest Control', 'dewey-pest-control', 'pest_control', 'https://deweypest.com', ARRAY['CA'], NULL),
    ('Action Termite & Pest Control', 'action-termite', 'pest_control', 'https://actiontermite.com', ARRAY['AZ'], NULL),
    ('PermaTreat Pest Control', 'permatreat', 'pest_control', 'https://permatreat.com', ARRAY['VA'], NULL),
    ('Plunkett''s Pest Control', 'plunketts', 'pest_control', 'https://plunketts.net', ARRAY['MN','WI','IA','ND','SD','NE'], NULL),
    ('Rove Pest Control', 'rove-pest-control', 'pest_control', 'https://rovepestcontrol.com', ARRAY['MN','WI','IA','MO','IL'], NULL),
    ('Adam''s Pest Control', 'adams-pest-control', 'pest_control', 'https://adamspestcontrol.com', ARRAY['MN','WI'], NULL),
    ('Active Pest Control', 'active-pest-control', 'pest_control', 'https://activepestcontrol.com', ARRAY['GA','TN'], NULL),
    ('All American Pest Control', 'all-american-pest', 'pest_control', 'https://allamericanpestcontrol.com', ARRAY['TN'], NULL),
    ('Fox Pest Control', 'fox-pest-control', 'pest_control', 'https://foxpest.com', ARRAY['US'], NULL),
    ('Greenix Pest Control', 'greenix-pest', 'pest_control', 'https://greenixpest.com', ARRAY['US'], NULL),
    ('PestNow', 'pestnow', 'pest_control', 'https://pestnow.com', ARRAY['VA','MD','DC','WV'], NULL),
    ('Senate Termite & Pest Control', 'senate-termite', 'pest_control', 'https://senatetermite.com', ARRAY['NJ','NY','PA','CT'], NULL),
    ('Stark Exterminators', 'stark-exterminators', 'pest_control', 'https://starkexterminators.com', ARRAY['GA','TN','AL'], NULL),
    ('Steritech', 'steritech', 'pest_control', 'https://steritech.com', ARRAY['US'], NULL),
    ('Truly Green Pest Control', 'truly-green', 'pest_control', 'https://trulygreenpestcontrol.com', ARRAY['US'], NULL),
    ('Viking Termite & Pest Control', 'viking-termite', 'pest_control', 'https://vikingpest.com', ARRAY['NJ','NY','PA','DE'], NULL),
    ('Waltham Services', 'waltham-services', 'pest_control', 'https://walthamservices.com', ARRAY['MA','RI'], NULL),
    ('Witt Pest Management', 'witt-pest', 'pest_control', 'https://wittpestmanagement.com', ARRAY['PA','OH'], NULL),
    ('Bulwark Exterminating', 'bulwark-exterminating', 'pest_control', 'https://bulwarkpestcontrol.com', ARRAY['US'], NULL),
    ('EcoLab', 'ecolab', 'pest_control', 'https://ecolab.com', ARRAY['US'], NULL),
    ('Beapco Products', 'beapco', 'pest_control', 'https://beapco.com', ARRAY['US'], NULL),
    ('Trio Pest Control', 'trio-pest', 'pest_control', 'https://triopestcontrol.com', ARRAY['US'], NULL),
    ('Western Termite & Pest Control', 'western-termite', 'pest_control', 'https://westernpest.com', ARRAY['CA'], NULL),
    ('Suburban Pest Control', 'suburban-pest', 'pest_control', 'https://suburbanpest.net', ARRAY['NJ','NY','PA'], NULL),
    ('Aronson Pest Control', 'aronson-pest', 'pest_control', 'https://aronsonpest.com', ARRAY['CT'], NULL),
    ('Connor''s Termite & Pest Control', 'connors-termite', 'pest_control', 'https://connorspest.com', ARRAY['IL'], NULL),
    ('Gregory Pest Solutions', 'gregory-pest', 'pest_control', 'https://gregorypestcontrol.com', ARRAY['SC','NC','GA','FL','TN'], NULL),
    ('Holder''s Pest Solutions', 'holders-pest', 'pest_control', 'https://holderspestcontrol.com', ARRAY['TX'], NULL),
    ('Insect IQ', 'insect-iq', 'pest_control', 'https://insectiq.com', ARRAY['CA'], NULL),
    ('Killingsworth Environmental', 'killingsworth', 'pest_control', 'https://killingsworth.com', ARRAY['NC','SC'], NULL),
    ('Mug-A-Bug', 'mug-a-bug', 'pest_control', 'https://mugabug.net', ARRAY['MO','IL'], NULL),
    ('Naturepest', 'naturepest', 'pest_control', 'https://naturepest.com', ARRAY['FL'], NULL),
    ('OPC Pest Services', 'opc-pest', 'pest_control', 'https://opcpest.com', ARRAY['OK','AR'], NULL),
    ('Paragon Pest Control', 'paragon-pest', 'pest_control', 'https://paragon-pest.com', ARRAY['NV','UT'], NULL),
    ('Patriot Pest Solutions', 'patriot-pest', 'pest_control', 'https://patriotpestsolutions.com', ARRAY['NJ','PA','DE'], NULL),
    ('Pest Solutions Inc.', 'pest-solutions-inc', 'pest_control', 'https://pestsolutions.com', ARRAY['US'], NULL),
    ('Pointe Pest Control', 'pointe-pest', 'pest_control', 'https://pointepest.com', ARRAY['IL','WA','OR','CO'], NULL),
    ('Presto-X', 'presto-x', 'pest_control', 'https://presto-x.com', ARRAY['US'], NULL),
    ('Springer Professional Home Services', 'springer-pest', 'pest_control', 'https://springerpest.com', ARRAY['IA'], NULL),
    ('Wallflower Pest Control', 'wallflower-pest', 'pest_control', 'https://wallflowerpest.com', ARRAY['NY','NJ','PA'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- SECURITY / ALARM COMPANIES (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Frontpoint Security', 'frontpoint-security', 'security', 'https://frontpointsecurity.com', ARRAY['US'], NULL),
    ('Cove Security', 'cove-security', 'security', 'https://covesmart.com', ARRAY['US'], NULL),
    ('Link Interactive', 'link-interactive', 'security', 'https://linkinteractive.com', ARRAY['US'], NULL),
    ('LiveWatch Security', 'livewatch', 'security', 'https://livewatch.com', ARRAY['US'], NULL),
    ('Protect America', 'protect-america', 'security', 'https://protectamerica.com', ARRAY['US'], NULL),
    ('Tyco Integrated Security', 'tyco-integrated', 'security', 'https://tycois.com', ARRAY['US'], NULL),
    ('CPI Security', 'cpi-security', 'security', 'https://cpisecurity.com', ARRAY['NC','SC','TN','GA','FL'], NULL),
    ('Slomin''s', 'slomins', 'security', 'https://slomins.com', ARRAY['NY','NJ','CT','PA','MD'], NULL),
    ('ADS Security', 'ads-security', 'security', 'https://adssecurity.com', ARRAY['TN','KY','AL','MS','GA'], NULL),
    ('Guardian Protection Services', 'guardian-protection', 'security', 'https://guardianprotection.com', ARRAY['PA','OH','MD','DC','VA','NC','SC','GA','FL'], NULL),
    ('ASG Security (Vector)', 'asg-security', 'security', 'https://asgsecurity.com', ARRAY['US'], NULL),
    ('Safe Home Security', 'safe-home-security', 'security', 'https://safehomesecurity.com', ARRAY['US'], NULL),
    ('Bay Alarm', 'bay-alarm', 'security', 'https://bayalarm.com', ARRAY['CA'], NULL),
    ('Sonitrol', 'sonitrol', 'security', 'https://sonitrol.com', ARRAY['US'], NULL),
    ('Stanley Security', 'stanley-security', 'security', 'https://stanleysecurity.com', ARRAY['US'], NULL),
    ('Securitas Security Services', 'securitas-security', 'security', 'https://securitasinc.com', ARRAY['US'], NULL),
    ('Allied Universal', 'allied-universal', 'security', 'https://aus.com', ARRAY['US'], NULL),
    ('Westec Intelligent Surveillance', 'westec-surveillance', 'security', 'https://westecsurveillance.com', ARRAY['CA'], NULL),
    ('Honeywell Security', 'honeywell-security', 'security', 'https://honeywell.com', ARRAY['US'], NULL),
    ('DSC (Digital Security Controls)', 'dsc-security', 'security', 'https://dsc.com', ARRAY['US'], NULL),
    ('Ackerman Security', 'ackerman-security', 'security', 'https://ackermansecurity.com', ARRAY['GA','TN','AL','SC','NC','FL'], NULL),
    ('American Alarm', 'american-alarm', 'security', 'https://americanalarm.com', ARRAY['MA','NH','RI','CT'], NULL),
    ('Knight Security Systems', 'knight-security', 'security', 'https://knightsecurity.com', ARRAY['TX'], NULL),
    ('NorthStar Alarm Services', 'northstar-alarm', 'security', 'https://northstaralarm.com', ARRAY['UT','ID','WY','NV','AZ'], NULL),
    ('Habitec Security', 'habitec-security', 'security', 'https://habitec.com', ARRAY['OH','MI'], NULL),
    ('Per Mar Security Services', 'per-mar-security', 'security', 'https://permar.com', ARRAY['IA','IL','MO','WI','NE','SD','MN'], NULL),
    ('Smith Monitoring', 'smith-monitoring', 'security', 'https://smithmonitoring.com', ARRAY['TX','OK'], NULL),
    ('Vector Security', 'vector-security', 'security', 'https://vectorsecurity.com', ARRAY['US'], NULL),
    ('Westchester Burglar Alarm', 'westchester-burglar-alarm', 'security', 'https://westchesterburglar.com', ARRAY['NY','CT'], NULL),
    ('Alarm.com', 'alarm-com', 'security', 'https://alarm.com', ARRAY['US'], NULL),
    ('Resideo (Honeywell Home)', 'resideo', 'security', 'https://resideo.com', ARRAY['US'], NULL),
    ('Eufy Security', 'eufy-security', 'security', 'https://us.eufy.com', ARRAY['US'], NULL),
    ('Wyze', 'wyze', 'security', 'https://wyze.com', ARRAY['US'], NULL),
    ('Arlo', 'arlo', 'security', 'https://arlo.com', ARRAY['US'], NULL),
    ('Nest (Google)', 'nest-google', 'security', 'https://store.google.com/category/connected_home', ARRAY['US'], NULL),
    ('Blink (Amazon)', 'blink-security', 'security', 'https://blinkforhome.com', ARRAY['US'], NULL),
    ('Reolink', 'reolink', 'security', 'https://reolink.com', ARRAY['US'], NULL),
    ('Lorex', 'lorex', 'security', 'https://lorex.com', ARRAY['US'], NULL),
    ('Swann Security', 'swann-security', 'security', 'https://swann.com', ARRAY['US'], NULL),
    ('Hikvision', 'hikvision', 'security', 'https://hikvision.com', ARRAY['US'], NULL),
    ('Dahua Technology', 'dahua', 'security', 'https://dahuasecurity.com', ARRAY['US'], NULL),
    ('Axis Communications', 'axis-communications', 'security', 'https://axis.com', ARRAY['US'], NULL),
    ('Bosch Security Systems', 'bosch-security', 'security', 'https://boschsecurity.com', ARRAY['US'], NULL),
    ('Verisure', 'verisure', 'security', 'https://verisure.com', ARRAY['US'], NULL),
    ('Total Security Integration (ATSI)', 'atsi', 'security', 'https://totalsecurityintegration.com', ARRAY['NY','NJ','CT'], NULL),
    ('Doyle Security Systems', 'doyle-security', 'security', 'https://doylesecurity.com', ARRAY['NY','PA'], NULL),
    ('Dynamark Security', 'dynamark', 'security', 'https://dynamark.com', ARRAY['US'], NULL),
    ('EMC Security', 'emc-security', 'security', 'https://emcsecurity.com', ARRAY['GA','SC'], NULL),
    ('Engineered Protection Systems', 'engineered-protection', 'security', 'https://eps-security.com', ARRAY['MI','OH','IN'], NULL),
    ('General Security', 'general-security', 'security', 'https://generalsecurity.com', ARRAY['NY','NJ'], NULL),
    ('IntelliSentry', 'intellisentry', 'security', 'https://intellisentry.com', ARRAY['US'], NULL),
    ('Magnum Protection', 'magnum-protection', 'security', 'https://magnumprotection.com', ARRAY['US'], NULL),
    ('National Monitoring Center', 'national-monitoring', 'security', 'https://nmccentral.com', ARRAY['US'], NULL),
    ('NTI National Telesystems', 'nti-telesystems', 'security', 'https://ntiservices.com', ARRAY['US'], NULL),
    ('Pinnacle Security', 'pinnacle-security', 'security', 'https://pinnaclesecurity.com', ARRAY['US'], NULL),
    ('Stealth Monitoring', 'stealth-monitoring', 'security', 'https://stealthmonitoring.com', ARRAY['US'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- TRASH / WASTE COMPANIES (50+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Waste Connections', 'waste-connections', 'trash', 'https://wasteconnections.com', ARRAY['US'], NULL),
    ('Casella Waste Systems', 'casella-waste', 'trash', 'https://casella.com', ARRAY['VT','NH','NY','MA','ME','CT','PA'], NULL),
    ('Clean Harbors', 'clean-harbors', 'trash', 'https://cleanharbors.com', ARRAY['US'], NULL),
    ('Stericycle', 'stericycle', 'trash', 'https://stericycle.com', ARRAY['US'], NULL),
    ('Covanta', 'covanta', 'trash', 'https://covanta.com', ARRAY['US'], NULL),
    ('Recology', 'recology', 'trash', 'https://recology.com', ARRAY['CA','OR','WA'], NULL),
    ('Rubicon', 'rubicon', 'trash', 'https://rubicon.com', ARRAY['US'], NULL),
    ('GFL Environmental', 'gfl-environmental', 'trash', 'https://gflenv.com', ARRAY['US'], NULL),
    ('Waste Industries', 'waste-industries', 'trash', 'https://wasteindustries.com', ARRAY['NC','SC','VA','GA','TN'], NULL),
    ('Waste Pro USA', 'waste-pro-usa', 'trash', 'https://wasteprousa.com', ARRAY['FL','AL','GA','SC','NC','MS','LA','TN'], NULL),
    ('Lakeshore Recycling Systems', 'lakeshore-recycling', 'trash', 'https://lrsrecycles.com', ARRAY['IL','IN','WI'], NULL),
    ('Meridian Waste Solutions', 'meridian-waste', 'trash', 'https://meridianwaste.com', ARRAY['MO','VA','NC','GA'], NULL),
    ('NEDT (New England Disposal Technologies)', 'nedt', 'trash', 'https://nedt.com', ARRAY['MA','NH','RI','CT'], NULL),
    ('Atlas Disposal', 'atlas-disposal', 'trash', 'https://atlasdisposal.com', ARRAY['CA'], NULL),
    ('Suburban Disposal', 'suburban-disposal', 'trash', 'https://suburbandisposal.com', ARRAY['NJ','PA'], NULL),
    ('American Disposal Services', 'american-disposal', 'trash', 'https://americandisposal.com', ARRAY['VA','GA','MD'], NULL),
    ('1-800-GOT-JUNK?', '1800-got-junk', 'trash', 'https://1800gotjunk.com', ARRAY['US'], NULL),
    ('College Hunks Hauling Junk', 'college-hunks', 'trash', 'https://collegehunkshaulingjunk.com', ARRAY['US'], NULL),
    ('Junk King', 'junk-king', 'trash', 'https://junk-king.com', ARRAY['US'], NULL),
    ('Ridwell', 'ridwell', 'trash', 'https://ridwell.com', ARRAY['WA','OR','CO','MN','TX','CA'], NULL),
    ('Recyclops', 'recyclops', 'trash', 'https://recyclops.com', ARRAY['US'], NULL),
    ('TerraCycle', 'terracycle', 'trash', 'https://terracycle.com', ARRAY['US'], NULL),
    ('WIN Waste Innovations', 'win-waste', 'trash', 'https://winwaste.com', ARRAY['MA','NH','NY','PA','OH','MD','VA','NC','FL'], NULL),
    ('Penn Waste', 'penn-waste', 'trash', 'https://pennwaste.com', ARRAY['PA','MD'], NULL),
    ('Connecticut Disposal Services', 'ct-disposal', 'trash', 'https://ctdisposal.com', ARRAY['CT'], NULL),
    ('Suburban Sanitation', 'suburban-sanitation', 'trash', 'https://suburban-sanitation.com', ARRAY['CT'], NULL),
    ('Town & Country Waste', 'town-country-waste', 'trash', 'https://townandcountrywaste.com', ARRAY['NJ','NY'], NULL),
    ('Bestway Disposal', 'bestway-disposal', 'trash', 'https://bestwaydisposal.com', ARRAY['PA'], NULL),
    ('Premium Waste Services', 'premium-waste', 'trash', 'https://premiumwasteservices.com', ARRAY['US'], NULL),
    ('Curbside Composting', 'curbside-composting', 'trash', 'https://curbsidecomposting.com', ARRAY['US'], NULL),
    ('Compost Crew', 'compost-crew', 'trash', 'https://compostcrew.com', ARRAY['MD','DC','VA'], NULL),
    ('Bootstrap Compost', 'bootstrap-compost', 'trash', 'https://bootstrapcompost.com', ARRAY['MA'], NULL),
    ('Black Earth Compost', 'black-earth-compost', 'trash', 'https://blackearthcompost.com', ARRAY['MA'], NULL),
    ('Atlas Organics', 'atlas-organics', 'trash', 'https://atlasorganics.net', ARRAY['SC','NC','GA','TN'], NULL),
    ('Rumpke Waste & Recycling', 'rumpke', 'trash', 'https://rumpke.com', ARRAY['OH','KY','IN','WV'], NULL),
    ('Waste Pro of New England', 'waste-pro-new-england', 'trash', 'https://wasteprousa.com', ARRAY['MA','RI','CT','NH','VT','ME'], NULL),
    ('Lakeshore Disposal', 'lakeshore-disposal', 'trash', 'https://lakeshoredisposal.com', ARRAY['MI'], NULL),
    ('Allied Waste (now Republic)', 'allied-waste', 'trash', 'https://republicservices.com', ARRAY['US'], NULL),
    ('Eastern Waste Solutions', 'eastern-waste', 'trash', 'https://easternwaste.com', ARRAY['MA','RI','CT'], NULL),
    ('Carolina Waste Services', 'carolina-waste', 'trash', 'https://carolinawaste.com', ARRAY['NC','SC'], NULL),
    ('Florida Refuse Service', 'florida-refuse', 'trash', 'https://floridarefuse.com', ARRAY['FL'], NULL),
    ('JP Mascaro & Sons', 'jp-mascaro', 'trash', 'https://jpmascaro.com', ARRAY['PA','NJ','DE','MD'], NULL),
    ('Southern Waste Systems', 'southern-waste', 'trash', 'https://southernwastesystems.com', ARRAY['FL'], NULL),
    ('TLC Disposal', 'tlc-disposal', 'trash', 'https://tlcdisposal.com', ARRAY['IL','IN'], NULL),
    ('Waste Industries (USA Waste)', 'usa-waste', 'trash', 'https://wasteindustries.com', ARRAY['US'], NULL),
    ('Penngrove Waste', 'penngrove-waste', 'trash', 'https://penngrovewaste.com', ARRAY['PA'], NULL),
    ('Blossman Waste', 'blossman-waste', 'trash', 'https://blossmanwaste.com', ARRAY['AL','GA','MS'], NULL),
    ('Tellico Plains Disposal', 'tellico-disposal', 'trash', 'https://tellicodisposal.com', ARRAY['TN'], NULL),
    ('Modern Waste Services', 'modern-waste', 'trash', 'https://modernwaste.com', ARRAY['NY','NJ'], NULL),
    ('Best Disposal Services', 'best-disposal', 'trash', 'https://bestdisposalservices.com', ARRAY['US'], NULL),
    ('Royal Waste Services', 'royal-waste', 'trash', 'https://royalwaste.com', ARRAY['NY','NJ'], NULL),
    ('Clean Earth Recycling', 'clean-earth-recycling', 'trash', 'https://cleanearthinc.com', ARRAY['US'], NULL),
    ('Action Environmental Services', 'action-environmental', 'trash', 'https://actionenviro.com', ARRAY['NY','NJ','PA','CT'], NULL),
    ('Boston Carting', 'boston-carting', 'trash', 'https://bostoncarting.com', ARRAY['MA'], NULL),
    ('Northstar Recycling', 'northstar-recycling', 'trash', 'https://northstarrecycling.com', ARRAY['MA','NY'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- SOLAR COMPANIES (50+ NEW provider type)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Sunrun', 'sunrun', 'solar', 'https://sunrun.com', ARRAY['US'], NULL),
    ('SunPower', 'sunpower', 'solar', 'https://sunpower.com', ARRAY['US'], NULL),
    ('Tesla Energy', 'tesla-energy', 'solar', 'https://tesla.com/solar', ARRAY['US'], NULL),
    ('Sunnova Energy', 'sunnova-energy', 'solar', 'https://sunnova.com', ARRAY['US'], NULL),
    ('Trinity Solar', 'trinity-solar', 'solar', 'https://trinity-solar.com', ARRAY['NJ','PA','NY','CT','MA','RI','MD'], NULL),
    ('Momentum Solar', 'momentum-solar', 'solar', 'https://momentumsolar.com', ARRAY['NJ','NY','PA','CT','FL','TX','CA','AZ','NV'], NULL),
    ('Palmetto Solar', 'palmetto-solar', 'solar', 'https://palmetto.com', ARRAY['US'], NULL),
    ('Freedom Forever Solar', 'freedom-forever-solar', 'solar', 'https://freedomforever.com', ARRAY['US'], NULL),
    ('ADT Solar', 'adt-solar', 'solar', 'https://adtsolar.com', ARRAY['US'], NULL),
    ('Erus Energy', 'erus-energy', 'solar', 'https://erusenergy.com', ARRAY['AZ','TX','NV'], NULL),
    ('Solar Optimum', 'solar-optimum', 'solar', 'https://solaroptimum.com', ARRAY['CA','NV'], NULL),
    ('Renu Energy Solutions', 'renu-energy', 'solar', 'https://renuenergysolutions.com', ARRAY['NC','SC','GA'], NULL),
    ('Solar Energy World', 'solar-energy-world', 'solar', 'https://solarenergyworld.com', ARRAY['MD','VA','DE','PA','DC','NJ','FL'], NULL),
    ('Pink Energy (formerly Power Home Solar)', 'pink-energy', 'solar', 'https://pinkenergy.com', ARRAY['US'], NULL),
    ('Brio Energy', 'brio-energy', 'solar', 'https://brioenergy.com', ARRAY['UT','TX'], NULL),
    ('Lumio Solar', 'lumio-solar', 'solar', 'https://lumio.com', ARRAY['US'], NULL),
    ('Solaria', 'solaria', 'solar', 'https://solaria.com', ARRAY['US'], NULL),
    ('PosiGen', 'posigen', 'solar', 'https://posigen.com', ARRAY['LA','MS','CT','NY','NJ','PA'], NULL),
    ('Lightsource bp', 'lightsource-bp', 'solar', 'https://lightsourcebp.com', ARRAY['US'], NULL),
    ('Sunworks', 'sunworks-usa', 'solar', 'https://sunworksusa.com', ARRAY['CA','NV'], NULL),
    ('American Solar Direct', 'american-solar-direct', 'solar', 'https://americansolardirect.com', ARRAY['CA','AZ','NV'], NULL),
    ('Treeium', 'treeium', 'solar', 'https://treeium.com', ARRAY['CA'], NULL),
    ('SunCommon', 'suncommon', 'solar', 'https://suncommon.com', ARRAY['VT','NY'], NULL),
    ('NRG Energy Solar', 'nrg-energy-solar', 'solar', 'https://nrg.com', ARRAY['US'], NULL),
    ('Direct Energy Solar', 'direct-energy-solar', 'solar', 'https://directenergysolar.com', ARRAY['US'], NULL),
    ('Q CELLS / Hanwha', 'q-cells', 'solar', 'https://qcells.com', ARRAY['US'], NULL),
    ('Canadian Solar', 'canadian-solar', 'solar', 'https://canadiansolar.com', ARRAY['US'], NULL),
    ('Mission Solar', 'mission-solar', 'solar', 'https://missionsolar.com', ARRAY['TX'], NULL),
    ('Generac PWRcell', 'generac-pwrcell', 'solar', 'https://generac.com', ARRAY['US'], NULL),
    ('Enphase Energy', 'enphase-energy', 'solar', 'https://enphase.com', ARRAY['US'], NULL),
    ('SolarEdge', 'solaredge', 'solar', 'https://solaredge.com', ARRAY['US'], NULL),
    ('Tigo Energy', 'tigo-energy', 'solar', 'https://tigoenergy.com', ARRAY['US'], NULL),
    ('Solar Liberty', 'solar-liberty', 'solar', 'https://solarliberty.com', ARRAY['NY'], NULL),
    ('Sun Tribe Solar', 'sun-tribe-solar', 'solar', 'https://suntribesolar.com', ARRAY['VA','NC','SC'], NULL),
    ('Smart Solar', 'smart-solar', 'solar', 'https://smartsolarofflorida.com', ARRAY['FL'], NULL),
    ('PetersenDean Roofing & Solar', 'petersendean', 'solar', 'https://petersendean.com', ARRAY['CA','NV','AZ'], NULL),
    ('Sunline Energy', 'sunline-energy', 'solar', 'https://sunlineenergy.com', ARRAY['CA'], NULL),
    ('Sunrise Solar Solutions', 'sunrise-solar-solutions', 'solar', 'https://sunrisesolarsolutions.com', ARRAY['NY','CT','NJ'], NULL),
    ('Sun Badger Solar', 'sun-badger-solar', 'solar', 'https://sunbadgersolar.com', ARRAY['WI','IL','MN','IA'], NULL),
    ('Power & Solar Group', 'power-solar-group', 'solar', 'https://powerandsolargroup.com', ARRAY['US'], NULL),
    ('GoodLeap Solar', 'goodleap-solar', 'solar', 'https://goodleap.com', ARRAY['US'], NULL),
    ('Sungage Financial', 'sungage-financial', 'solar', 'https://sungage.com', ARRAY['US'], NULL),
    ('Mosaic Solar', 'mosaic-solar', 'solar', 'https://joinmosaic.com', ARRAY['US'], NULL),
    ('LGCY Power', 'lgcy-power', 'solar', 'https://lgcypower.com', ARRAY['US'], NULL),
    ('Vision Solar', 'vision-solar', 'solar', 'https://visionsolar.com', ARRAY['NJ','PA','MA','FL'], NULL),
    ('Sun Solar', 'sun-solar', 'solar', 'https://gosunsolar.com', ARRAY['MO','AR','KS','OK','TX','TN','KY'], NULL),
    ('SolarMax Technology', 'solarmax-technology', 'solar', 'https://solarmaxtech.com', ARRAY['CA','NV'], NULL),
    ('Semper Solaris', 'semper-solaris', 'solar', 'https://sempersolaris.com', ARRAY['CA','TX'], NULL),
    ('Rec Solar', 'rec-solar', 'solar', 'https://recsolar.com', ARRAY['US'], NULL),
    ('Independent Power Systems', 'independent-power-systems', 'solar', 'https://ips-solar.com', ARRAY['MN','WI','IA','CO'], NULL),
    ('Solar Holler', 'solar-holler', 'solar', 'https://solarholler.com', ARRAY['WV','VA','OH','KY','MD'], NULL),
    ('Spruce Power', 'spruce-power', 'solar', 'https://sprucepower.com', ARRAY['US'], NULL),
    ('GRID Alternatives', 'grid-alternatives', 'solar', 'https://gridalternatives.org', ARRAY['US'], NULL),
    ('SolarCraft', 'solarcraft', 'solar', 'https://solarcraft.com', ARRAY['CA'], NULL),
    ('Cinnamon Energy Systems', 'cinnamon-energy', 'solar', 'https://cinnamonenergysystems.com', ARRAY['CA'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- AUTO INSURANCE (50+ additions, beyond Phase 16a's 50)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url, bundles_with_home) VALUES
    ('Cumberland Insurance Group', 'cumberland-insurance-auto', 'auto_insurance', 'https://cumberlandgroup.com', ARRAY['NJ','PA','DE','MD','VA'], NULL, true),
    ('Selective Insurance', 'selective-insurance-auto', 'auto_insurance', 'https://selective.com', ARRAY['US'], NULL, true),
    ('Sagamore Insurance', 'sagamore-insurance-auto', 'auto_insurance', 'https://sagamoreinsurance.com', ARRAY['IN','OH','IL','KY'], NULL, false),
    ('Direct General', 'direct-general-auto', 'auto_insurance', 'https://directgeneral.com', ARRAY['US'], NULL, false),
    ('Foremost Insurance', 'foremost-insurance-auto', 'auto_insurance', 'https://foremost.com', ARRAY['US'], NULL, true),
    ('Bristol West Insurance', 'bristol-west-auto', 'auto_insurance', 'https://bristolwest.com', ARRAY['US'], NULL, false),
    ('21st Century Insurance', '21st-century-auto', 'auto_insurance', 'https://21st.com', ARRAY['US'], NULL, false),
    ('Encompass Insurance', 'encompass-insurance-auto', 'auto_insurance', 'https://encompassinsurance.com', ARRAY['US'], NULL, true),
    ('EMC Insurance', 'emc-insurance-auto', 'auto_insurance', 'https://emcins.com', ARRAY['US'], NULL, true),
    ('Frankenmuth Insurance', 'frankenmuth-auto', 'auto_insurance', 'https://fmins.com', ARRAY['MI','OH','IN','IL','TN','KY','PA','WI'], NULL, true),
    ('Grange Mutual', 'grange-mutual-auto', 'auto_insurance', 'https://grangeinsurance.com', ARRAY['OH','PA','IN','KY','TN','GA','SC'], NULL, true),
    ('Hastings Mutual', 'hastings-mutual-auto', 'auto_insurance', 'https://hastingsmutual.com', ARRAY['MI','IN','IL','OH','WI','IA'], NULL, true),
    ('Indiana Farmers Mutual', 'indiana-farmers-mutual-auto', 'auto_insurance', 'https://indianafarmers.com', ARRAY['IN','IL','OH','KY','TN'], NULL, true),
    ('Kentucky Farm Bureau', 'kentucky-farm-bureau-auto', 'auto_insurance', 'https://kyfb.com', ARRAY['KY'], NULL, true),
    ('Merchants Insurance', 'merchants-insurance-auto', 'auto_insurance', 'https://merchantsgroup.com', ARRAY['NY','NH','VT','PA','NJ','CT','MA','ME','RI'], NULL, true),
    ('Nodak Insurance', 'nodak-insurance-auto', 'auto_insurance', 'https://nodakins.com', ARRAY['ND','SD','MN','WY','MT'], NULL, true),
    ('NC Farm Bureau', 'nc-farm-bureau-auto', 'auto_insurance', 'https://ncfbins.com', ARRAY['NC'], NULL, true),
    ('NJ Manufacturers Insurance', 'njm-insurance-auto', 'auto_insurance', 'https://njm.com', ARRAY['NJ','PA','OH','MD','CT'], NULL, true),
    ('Ohio Mutual', 'ohio-mutual-auto', 'auto_insurance', 'https://omig.com', ARRAY['OH','IN','MI','PA','RI','VT','NH','ME','CT','MA'], NULL, true),
    ('Oregon Mutual', 'oregon-mutual-auto', 'auto_insurance', 'https://ormutual.com', ARRAY['OR','WA','ID','NV','CA'], NULL, true),
    ('Penn National Insurance', 'penn-national-auto', 'auto_insurance', 'https://pnat.com', ARRAY['PA','NC','SC','VA','WV','TN','MD','AL'], NULL, true),
    ('Rural Mutual Insurance', 'rural-mutual-auto', 'auto_insurance', 'https://ruralmutual.com', ARRAY['WI'], NULL, true),
    ('SafeAuto', 'safeauto-insurance', 'auto_insurance', 'https://safeauto.com', ARRAY['US'], NULL, false),
    ('United Auto Insurance', 'united-auto-insurance', 'auto_insurance', 'https://uaig.net', ARRAY['IL','IN','TX','MI','GA','TN','MO','OH'], NULL, false),
    ('Wawanesa Insurance', 'wawanesa-auto', 'auto_insurance', 'https://wawanesa.com', ARRAY['CA','OR'], NULL, false),
    ('West Bend Mutual', 'west-bend-mutual-auto', 'auto_insurance', 'https://thesilverlining.com', ARRAY['WI','MN','IL','IA','IN','MI','OH','PA'], NULL, true),
    ('Western United Insurance', 'western-united-auto', 'auto_insurance', 'https://westernunitedinsurance.com', ARRAY['CA','NV','WA'], NULL, false),
    ('Auto Club of Southern California', 'auto-club-socal', 'auto_insurance', 'https://aaa.com/socal', ARRAY['CA'], NULL, true),
    ('AAA Northern California', 'aaa-norcal', 'auto_insurance', 'https://aaa.com/norcal', ARRAY['CA','NV','UT','AZ'], NULL, true),
    ('AAA Mid-Atlantic', 'aaa-mid-atlantic', 'auto_insurance', 'https://aaa.com', ARRAY['DE','MD','NJ','PA','VA','DC','WV'], NULL, true),
    ('AAA Texas', 'aaa-texas', 'auto_insurance', 'https://aaa.com/texas', ARRAY['TX'], NULL, true),
    ('Acceptance Insurance', 'acceptance-insurance-auto', 'auto_insurance', 'https://acceptanceinsurance.com', ARRAY['US'], NULL, false),
    ('Assurance America', 'assurance-america-auto', 'auto_insurance', 'https://assuranceamerica.com', ARRAY['US'], NULL, false),
    ('Dairyland Insurance', 'dairyland-insurance-auto', 'auto_insurance', 'https://dairylandinsurance.com', ARRAY['US'], NULL, false),
    ('Farm Bureau Financial Services', 'fbfs-auto', 'auto_insurance', 'https://fbfs.com', ARRAY['US'], NULL, true),
    ('Farmers Mutual of Nebraska', 'farmers-mutual-nebraska-auto', 'auto_insurance', 'https://fmne.com', ARRAY['NE'], NULL, true),
    ('First Acceptance', 'first-acceptance-auto', 'auto_insurance', 'https://firstacceptance.com', ARRAY['US'], NULL, false),
    ('Fred Loya Insurance', 'fred-loya-auto', 'auto_insurance', 'https://fredloya.com', ARRAY['TX','CA','NV','NM','AZ','CO','IL'], NULL, false),
    ('GAINSCO Auto Insurance', 'gainsco-extended-auto', 'auto_insurance', 'https://gainsco.com', ARRAY['US'], NULL, false),
    ('Imperial Fire & Casualty', 'imperial-fire-auto', 'auto_insurance', 'https://imperialfire.com', ARRAY['LA','MS','TX'], NULL, false),
    ('Kemper Personal Insurance', 'kemper-personal-auto', 'auto_insurance', 'https://kemper.com', ARRAY['US'], NULL, true),
    ('Liberty Bankers Insurance', 'liberty-bankers-auto', 'auto_insurance', 'https://libertybankers.com', ARRAY['US'], NULL, false),
    ('National General Premier', 'national-general-premier-auto', 'auto_insurance', 'https://nationalgeneral.com', ARRAY['US'], NULL, true),
    ('Permanent General Assurance (The General)', 'permanent-general-auto', 'auto_insurance', 'https://thegeneral.com', ARRAY['US'], NULL, false),
    ('Republic Indemnity', 'republic-indemnity-auto', 'auto_insurance', 'https://republicindemnity.com', ARRAY['CA'], NULL, false),
    ('Stillwater Insurance', 'stillwater-insurance-auto', 'auto_insurance', 'https://stillwater.com', ARRAY['US'], NULL, true),
    ('Tower Hill Insurance', 'tower-hill-auto', 'auto_insurance', 'https://thig.com', ARRAY['FL'], NULL, true),
    ('Universal North America', 'universal-north-america-auto', 'auto_insurance', 'https://universalnorthamerica.com', ARRAY['US'], NULL, false),
    ('UPC Insurance', 'upc-insurance-auto', 'auto_insurance', 'https://upcinsurance.com', ARRAY['FL','LA','SC','NC','GA','TX','MA','CT','RI','NJ','NY'], NULL, true),
    ('Workmen''s Auto Insurance', 'workmens-auto', 'auto_insurance', 'https://workmensauto.com', ARRAY['CA'], NULL, false),
    ('Erie Family Life Insurance', 'erie-family-life-auto', 'auto_insurance', 'https://erieinsurance.com', ARRAY['US'], NULL, true),
    ('Tradition American Family', 'tradition-american-family-auto', 'auto_insurance', 'https://amfam.com', ARRAY['US'], NULL, true)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- HOME INSURANCE (50+ additions, beyond Phase 16a's 50)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url, bundles_with_auto) VALUES
    ('Cumberland Insurance Group', 'cumberland-insurance-home', 'home_insurance', 'https://cumberlandgroup.com', ARRAY['NJ','PA','DE','MD','VA'], NULL, true),
    ('Selective Insurance', 'selective-insurance-home', 'home_insurance', 'https://selective.com', ARRAY['US'], NULL, true),
    ('Foremost Insurance', 'foremost-insurance-home', 'home_insurance', 'https://foremost.com', ARRAY['US'], NULL, true),
    ('21st Century Insurance', '21st-century-home', 'home_insurance', 'https://21st.com', ARRAY['US'], NULL, false),
    ('Encompass Insurance', 'encompass-insurance-home', 'home_insurance', 'https://encompassinsurance.com', ARRAY['US'], NULL, true),
    ('EMC Insurance', 'emc-insurance-home', 'home_insurance', 'https://emcins.com', ARRAY['US'], NULL, true),
    ('Frankenmuth Insurance', 'frankenmuth-home', 'home_insurance', 'https://fmins.com', ARRAY['MI','OH','IN','IL','TN','KY','PA','WI'], NULL, true),
    ('Grange Mutual', 'grange-mutual-home', 'home_insurance', 'https://grangeinsurance.com', ARRAY['OH','PA','IN','KY','TN','GA','SC'], NULL, true),
    ('Hastings Mutual', 'hastings-mutual-home', 'home_insurance', 'https://hastingsmutual.com', ARRAY['MI','IN','IL','OH','WI','IA'], NULL, true),
    ('Indiana Farmers Mutual', 'indiana-farmers-mutual-home', 'home_insurance', 'https://indianafarmers.com', ARRAY['IN','IL','OH','KY','TN'], NULL, true),
    ('Kentucky Farm Bureau', 'kentucky-farm-bureau-home', 'home_insurance', 'https://kyfb.com', ARRAY['KY'], NULL, true),
    ('Merchants Insurance', 'merchants-insurance-home', 'home_insurance', 'https://merchantsgroup.com', ARRAY['NY','NH','VT','PA','NJ','CT','MA','ME','RI'], NULL, true),
    ('Nodak Insurance', 'nodak-insurance-home', 'home_insurance', 'https://nodakins.com', ARRAY['ND','SD','MN','WY','MT'], NULL, true),
    ('NC Farm Bureau', 'nc-farm-bureau-home', 'home_insurance', 'https://ncfbins.com', ARRAY['NC'], NULL, true),
    ('Ohio Mutual', 'ohio-mutual-home', 'home_insurance', 'https://omig.com', ARRAY['OH','IN','MI','PA','RI','VT','NH','ME','CT','MA'], NULL, true),
    ('Oregon Mutual', 'oregon-mutual-home', 'home_insurance', 'https://ormutual.com', ARRAY['OR','WA','ID','NV','CA'], NULL, true),
    ('Penn National Insurance', 'penn-national-home', 'home_insurance', 'https://pnat.com', ARRAY['PA','NC','SC','VA','WV','TN','MD','AL'], NULL, true),
    ('Rural Mutual Insurance', 'rural-mutual-home', 'home_insurance', 'https://ruralmutual.com', ARRAY['WI'], NULL, true),
    ('West Bend Mutual', 'west-bend-mutual-home', 'home_insurance', 'https://thesilverlining.com', ARRAY['WI','MN','IL','IA','IN','MI','OH','PA'], NULL, true),
    ('AAA Mid-Atlantic Home', 'aaa-mid-atlantic-home', 'home_insurance', 'https://aaa.com', ARRAY['DE','MD','NJ','PA','VA','DC','WV'], NULL, true),
    ('AAA Northern California Home', 'aaa-norcal-home', 'home_insurance', 'https://aaa.com/norcal', ARRAY['CA','NV','UT','AZ'], NULL, true),
    ('AAA Texas Home', 'aaa-texas-home', 'home_insurance', 'https://aaa.com/texas', ARRAY['TX'], NULL, true),
    ('Auto Club of Southern California Home', 'auto-club-socal-home', 'home_insurance', 'https://aaa.com/socal', ARRAY['CA'], NULL, true),
    ('Farm Bureau Financial Services Home', 'fbfs-home', 'home_insurance', 'https://fbfs.com', ARRAY['US'], NULL, true),
    ('Farmers Mutual of Nebraska Home', 'farmers-mutual-nebraska-home', 'home_insurance', 'https://fmne.com', ARRAY['NE'], NULL, true),
    ('Tradition American Family Home', 'tradition-american-family-home', 'home_insurance', 'https://amfam.com', ARRAY['US'], NULL, true),
    ('Wawanesa Home Insurance', 'wawanesa-home', 'home_insurance', 'https://wawanesa.com', ARRAY['CA','OR'], NULL, true),
    ('AmTrust Financial', 'amtrust-financial-home', 'home_insurance', 'https://amtrustfinancial.com', ARRAY['US'], NULL, false),
    ('Cypress Property & Casualty', 'cypress-pc-home', 'home_insurance', 'https://cypressins.com', ARRAY['FL','TX','LA'], NULL, false),
    ('FedNat', 'fednat-home', 'home_insurance', 'https://fednat.com', ARRAY['FL','LA','TX','SC','AL'], NULL, false),
    ('First American Home Warranty', 'first-american-home-warranty', 'home_insurance', 'https://firstamrealestate.com', ARRAY['US'], NULL, false),
    ('Florida Peninsula', 'florida-peninsula-home', 'home_insurance', 'https://floridapeninsula.com', ARRAY['FL'], NULL, false),
    ('GeoVera', 'geovera-home', 'home_insurance', 'https://geovera.com', ARRAY['CA','HI','OR','WA','AL','MS','LA','TX'], NULL, false),
    ('Hartford Steam Boiler', 'hartford-steam-boiler-home', 'home_insurance', 'https://hsb.com', ARRAY['US'], NULL, false),
    ('Heritage Property & Casualty', 'heritage-pc-home', 'home_insurance', 'https://heritagepci.com', ARRAY['FL','HI','NC','SC','VA','GA','AL','MS','LA'], NULL, false),
    ('Kingstone Insurance', 'kingstone-insurance-home', 'home_insurance', 'https://kingstoneinsurance.com', ARRAY['NY','NJ','PA','MA','CT','RI','NH'], NULL, false),
    ('Liberty Mutual Affinity', 'liberty-mutual-affinity-home', 'home_insurance', 'https://libertymutual.com', ARRAY['US'], NULL, true),
    ('Lighthouse Property Insurance', 'lighthouse-property-home', 'home_insurance', 'https://lighthousepropertyinsurance.com', ARRAY['LA','TX','MS'], NULL, false),
    ('Maison Insurance', 'maison-insurance-home', 'home_insurance', 'https://maisoninsurance.com', ARRAY['LA','TX','FL'], NULL, false),
    ('Olympus Insurance', 'olympus-insurance-home', 'home_insurance', 'https://olympusinsurance.com', ARRAY['FL'], NULL, false),
    ('Pacific Specialty Insurance', 'pacific-specialty-home', 'home_insurance', 'https://pacificspecialty.com', ARRAY['CA','OR','WA','AZ','NV'], NULL, false),
    ('PURE Insurance', 'pure-insurance-home', 'home_insurance', 'https://pureinsurance.com', ARRAY['US'], NULL, true),
    ('QBE Insurance', 'qbe-insurance-home', 'home_insurance', 'https://qbe.com', ARRAY['US'], NULL, true),
    ('Selective Auto Plus', 'selective-auto-plus-home', 'home_insurance', 'https://selective.com', ARRAY['US'], NULL, true),
    ('Tower Hill Specialty', 'tower-hill-specialty-home', 'home_insurance', 'https://thig.com', ARRAY['FL'], NULL, false),
    ('UPCIC (Universal P&C)', 'upcic-home', 'home_insurance', 'https://universalproperty.com', ARRAY['FL','SC','NC','GA','MA','MN','MD','DE','VA','HI','PA','IL','MI','AL','IN'], NULL, false),
    ('Velocity Risk Underwriters', 'velocity-risk-home', 'home_insurance', 'https://velocityrisk.com', ARRAY['US'], NULL, false),
    ('Vyrd Insurance', 'vyrd-insurance-home', 'home_insurance', 'https://vyrdinsurance.com', ARRAY['FL'], NULL, false),
    ('Weston Property & Casualty', 'weston-pc-home', 'home_insurance', 'https://westonpci.com', ARRAY['FL','LA','SC','GA','MS','AL','HI','TX'], NULL, false),
    ('Wright National Flood', 'wright-national-flood-home', 'home_insurance', 'https://wrightflood.com', ARRAY['US'], NULL, false),
    ('Privilege Underwriters Reciprocal Exchange', 'pure-reciprocal-home', 'home_insurance', 'https://pureinsurance.com', ARRAY['US'], NULL, true),
    ('Cabrillo Coastal General Insurance', 'cabrillo-coastal-home', 'home_insurance', 'https://cabrillocoastal.com', ARRAY['FL','TX','LA','MS','AL'], NULL, false)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- WATER UTILITIES (a few key additions for major markets)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Suez Water (Veolia)', 'suez-water', 'water', 'https://veolianorthamerica.com', ARRAY['US'], NULL),
    ('California Water Service', 'cal-water', 'water', 'https://calwater.com', ARRAY['CA','NM','HI','WA'], NULL),
    ('Essential Utilities (Aqua America)', 'aqua-america', 'water', 'https://essential.co', ARRAY['PA','OH','TX','NC','IL','VA','WV','NJ','IN'], NULL),
    ('NJ American Water', 'nj-american-water', 'water', 'https://amwater.com/njaw', ARRAY['NJ'], NULL),
    ('PA American Water', 'pa-american-water', 'water', 'https://amwater.com/paaw', ARRAY['PA'], NULL),
    ('CT Water', 'ct-water', 'water', 'https://ctwater.com', ARRAY['CT','MA'], NULL),
    ('DC Water', 'dc-water', 'water', 'https://dcwater.com', ARRAY['DC'], NULL),
    ('NYC Department of Environmental Protection', 'nyc-dep', 'water', 'https://nyc.gov/dep', ARRAY['NY'], NULL),
    ('San Diego Water Authority', 'san-diego-water', 'water', 'https://sdcwa.org', ARRAY['CA'], NULL),
    ('Denver Water', 'denver-water', 'water', 'https://denverwater.org', ARRAY['CO'], NULL),
    ('Tampa Bay Water', 'tampa-bay-water', 'water', 'https://tampabaywater.org', ARRAY['FL'], NULL),
    ('Miami-Dade Water and Sewer', 'miami-dade-water', 'water', 'https://miamidade.gov/water', ARRAY['FL'], NULL),
    ('Houston Public Works', 'houston-public-works', 'water', 'https://houstonpublicworks.org', ARRAY['TX'], NULL),
    ('San Antonio Water System', 'saws', 'water', 'https://saws.org', ARRAY['TX'], NULL),
    ('Austin Water', 'austin-water', 'water', 'https://austintexas.gov/water', ARRAY['TX'], NULL),
    ('Las Vegas Valley Water District', 'lvvwd', 'water', 'https://lvvwd.com', ARRAY['NV'], NULL),
    ('Atlanta Watershed Management', 'atlanta-watershed', 'water', 'https://atlantawatershed.org', ARRAY['GA'], NULL),
    ('Charlotte Water', 'charlotte-water', 'water', 'https://charlottewater.org', ARRAY['NC'], NULL),
    ('Boston Water and Sewer', 'boston-water-sewer', 'water', 'https://bwsc.org', ARRAY['MA'], NULL),
    ('MWRA (Mass Water Resources)', 'mwra', 'water', 'https://mwra.com', ARRAY['MA'], NULL),
    ('CT Water Company', 'ct-water-company', 'water', 'https://ctwater.com', ARRAY['CT'], NULL),
    ('Suez Water Connecticut', 'suez-water-ct', 'water', 'https://veolianorthamerica.com', ARRAY['CT'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- POOL SERVICE COMPANIES (30+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Crystal Clear Pool Service', 'crystal-clear-pool', 'pool_service', 'https://crystalclearpool.com', ARRAY['US'], NULL),
    ('Pool Scouts', 'pool-scouts', 'pool_service', 'https://poolscouts.com', ARRAY['US'], NULL),
    ('Aqua Quip', 'aqua-quip', 'pool_service', 'https://aquaquip.com', ARRAY['WA'], NULL),
    ('Splash Pool & Spa', 'splash-pool-spa', 'pool_service', 'https://splashpoolspa.com', ARRAY['US'], NULL),
    ('Aquatech Pool Management', 'aquatech-pool', 'pool_service', 'https://aquatechpool.com', ARRAY['US'], NULL),
    ('Galaxy Pools', 'galaxy-pools', 'pool_service', 'https://galaxypools.com', ARRAY['NJ','NY','PA'], NULL),
    ('Aqua-Tots Pool Service', 'aqua-tots-pool', 'pool_service', 'https://aquatotspool.com', ARRAY['US'], NULL),
    ('Diamond Pool Service', 'diamond-pool', 'pool_service', 'https://diamondpoolservice.com', ARRAY['US'], NULL),
    ('Sunsational Pool Service', 'sunsational-pool', 'pool_service', 'https://sunsationalpoolservice.com', ARRAY['FL','TX','AZ','CA'], NULL),
    ('Underwater Pool Masters', 'underwater-pool-masters', 'pool_service', 'https://underwaterpoolmasters.com', ARRAY['CA'], NULL),
    ('Bel-Aqua Pool Supply', 'bel-aqua-pool', 'pool_service', 'https://belaquapoolsupply.com', ARRAY['NY','NJ','CT'], NULL),
    ('Patio Pleasures', 'patio-pleasures', 'pool_service', 'https://patiopleasures.com', ARRAY['MD','VA','DC'], NULL),
    ('Holiday Pools', 'holiday-pools', 'pool_service', 'https://holidaypools.com', ARRAY['SC','NC','VA'], NULL),
    ('All Seasons Pools & Spas', 'all-seasons-pools', 'pool_service', 'https://allseasonspoolsandspas.com', ARRAY['IL'], NULL),
    ('Aqua Pools', 'aqua-pools', 'pool_service', 'https://aquapools.com', ARRAY['IL'], NULL),
    ('Atlas Pools', 'atlas-pools', 'pool_service', 'https://atlaspoolsofcfl.com', ARRAY['FL'], NULL),
    ('Aviva Pools', 'aviva-pools', 'pool_service', 'https://avivapools.com', ARRAY['TX'], NULL),
    ('Bee Cave Pool Builders', 'bee-cave-pool', 'pool_service', 'https://beecavepoolbuilders.com', ARRAY['TX'], NULL),
    ('Cinderella Pools', 'cinderella-pools', 'pool_service', 'https://cinderellapools.com', ARRAY['TX'], NULL),
    ('Cody Pools', 'cody-pools', 'pool_service', 'https://codypools.com', ARRAY['TX','OK'], NULL),
    ('Crystal Pools', 'crystal-pools', 'pool_service', 'https://crystalpools.com', ARRAY['PA'], NULL),
    ('Diamond Spas', 'diamond-spas', 'pool_service', 'https://diamondspas.com', ARRAY['US'], NULL),
    ('Endless Pools', 'endless-pools', 'pool_service', 'https://endlesspools.com', ARRAY['US'], NULL),
    ('Fronheiser Pools', 'fronheiser-pools', 'pool_service', 'https://fronheiserpools.com', ARRAY['PA'], NULL),
    ('Gohlke Pools', 'gohlke-pools', 'pool_service', 'https://gohlkepools.com', ARRAY['TX'], NULL),
    ('Latham Pool Products', 'latham-pool', 'pool_service', 'https://lathampool.com', ARRAY['US'], NULL),
    ('Pacific Pools', 'pacific-pools', 'pool_service', 'https://pacificpools.com', ARRAY['US'], NULL),
    ('Pioneer Pools', 'pioneer-pools', 'pool_service', 'https://pioneerpools.com', ARRAY['CA'], NULL),
    ('Pool Tek Florida', 'pool-tek-florida', 'pool_service', 'https://pooltekflorida.com', ARRAY['FL'], NULL),
    ('Riverbend Sandler Pools', 'riverbend-sandler', 'pool_service', 'https://riverbendsandler.com', ARRAY['TX'], NULL),
    ('Royal Swimming Pools', 'royal-swimming-pools', 'pool_service', 'https://royalswimmingpools.com', ARRAY['US'], NULL),
    ('Shasta Pools', 'shasta-pools', 'pool_service', 'https://shastapools.com', ARRAY['AZ'], NULL),
    ('Soake Pools', 'soake-pools', 'pool_service', 'https://soakepools.com', ARRAY['US'], NULL),
    ('Tropic Isle Pools', 'tropic-isle-pools', 'pool_service', 'https://tropicislepools.com', ARRAY['FL'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- IRRIGATION COMPANIES (20+ additions)
-- ============================================================================

INSERT INTO public.utility_providers (name, slug, provider_type, website, regions, logo_url) VALUES
    ('Conserva Irrigation', 'conserva-irrigation-extended', 'irrigation', 'https://conservairrigation.com', ARRAY['US'], NULL),
    ('Aqua-Bright Irrigation', 'aqua-bright-irrigation-extended', 'irrigation', 'https://aquabrightirrigation.com', ARRAY['MD','VA','DC'], NULL),
    ('A-One Sprinkler', 'a-one-sprinkler', 'irrigation', 'https://aonesprinkler.com', ARRAY['CO'], NULL),
    ('Always Green Irrigation', 'always-green-irrigation', 'irrigation', 'https://alwaysgreenirrigation.com', ARRAY['US'], NULL),
    ('Atlas Lawn Sprinkler', 'atlas-lawn-sprinkler', 'irrigation', 'https://atlaslawnsprinkler.com', ARRAY['CT','NY'], NULL),
    ('Bartle Irrigation', 'bartle-irrigation', 'irrigation', 'https://bartleirrigation.com', ARRAY['NJ'], NULL),
    ('Dahler Irrigation', 'dahler-irrigation', 'irrigation', 'https://dahlerirrigation.com', ARRAY['MN'], NULL),
    ('Flo Pro Irrigation', 'flo-pro-irrigation', 'irrigation', 'https://floproirrigation.com', ARRAY['US'], NULL),
    ('GreenLawn Sprinkler', 'greenlawn-sprinkler', 'irrigation', 'https://greenlawnsprinkler.com', ARRAY['NC','SC'], NULL),
    ('Hydro-Tech Irrigation', 'hydro-tech-irrigation', 'irrigation', 'https://hydrotechirrigation.com', ARRAY['DC','MD','VA'], NULL),
    ('Irrigation Doctor', 'irrigation-doctor', 'irrigation', 'https://irrigationdoctor.com', ARRAY['US'], NULL),
    ('Lawn Sprinkler Services', 'lawn-sprinkler-services', 'irrigation', 'https://lawnsprinklerservices.com', ARRAY['US'], NULL),
    ('Lush Lawn Sprinklers', 'lush-lawn-sprinklers', 'irrigation', 'https://lushlawnsprinklers.com', ARRAY['MI'], NULL),
    ('Nutri-Lawn Irrigation', 'nutri-lawn-irrigation', 'irrigation', 'https://nutri-lawn.com', ARRAY['US'], NULL),
    ('Precision Irrigation', 'precision-irrigation', 'irrigation', 'https://precisionirrigation.com', ARRAY['US'], NULL),
    ('R&R Sprinkler', 'rr-sprinkler', 'irrigation', 'https://rrsprinkler.com', ARRAY['US'], NULL),
    ('SoCal Sprinkler Repair', 'socal-sprinkler-repair', 'irrigation', 'https://socalsprinklerrepair.com', ARRAY['CA'], NULL),
    ('Southern Irrigation', 'southern-irrigation', 'irrigation', 'https://southernirrigation.com', ARRAY['NC','SC','GA'], NULL),
    ('Sprinkler Magician', 'sprinkler-magician', 'irrigation', 'https://sprinklermagician.com', ARRAY['CO'], NULL),
    ('Sprinkler Pro', 'sprinkler-pro', 'irrigation', 'https://sprinklerpro.com', ARRAY['US'], NULL),
    ('Sprinkler Warehouse', 'sprinkler-warehouse', 'irrigation', 'https://sprinklerwarehouse.com', ARRAY['US'], NULL),
    ('Sun Sprinkler Systems', 'sun-sprinkler-systems', 'irrigation', 'https://sunsprinklersystems.com', ARRAY['US'], NULL),
    ('Texas Best Sprinkler', 'texas-best-sprinkler', 'irrigation', 'https://texasbestsprinkler.com', ARRAY['TX'], NULL),
    ('Tri-State Water Works', 'tri-state-water-works', 'irrigation', 'https://tristatewaterworks.com', ARRAY['NJ','NY','PA'], NULL)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================================
-- DONE
-- ============================================================================

-- Note: All inserted rows have logo_url = NULL. The lazy enrichment background
-- task fetches logos from Brandfetch on first picker render, OR a one-time
-- backfill can be triggered via the enrich-provider-logos edge function.
